### ISSUE TITLE
e4m2 & e4m4 issues/suggestions

### ISSUE THREAD

**Issue by nful2** [freedoom/freedoom#1004]
E4m2 - Enemies wake up inside the plus symbol near red door if player shoots, before pressing the switch, which fails to surprise player for a trap after pressing switch.
![Issue e4m2](https://github.com/freedoom/freedoom/assets/100768714/92ea9b14-72e0-4e73-88c4-b71b601b6bdf)

E4m4 - Flesh worms get stuck forever. Tried to go near them to make them attack, but still stuck in that state.
https://github.com/freedoom/freedoom/assets/100768714/c9fca018-5216-4ffd-9281-a7ba5ea9e7d9

**Comment by mc776** [comment]
Can't replicate E4M4 problem - I got up the stairs and they'll come over and bite just fine.

Re E4M2, how certain are we that this is not the intended behaviour? It works the same way for me in the original Double Impact (E1M3).

**Comment by nful2** [comment]
@mc776 e4m4: yeah, I think it can occur in rare cases only.
E4m2 is optional suggestion. You can change it if you wish to.
