### ISSUE TITLE
Freedoom wads cannot be built with python-pillow 10.x.

### ISSUE THREAD

**Issue by FredBezies** [freedoom/freedoom#1015]
I tried to build revision 15b03eb3, but it does not work. It stops with this error log:

```
make[1]: Leaving directory '/home/fred/freedoom-git/src/freedoom/lumps/dehacked'
make VERSION=v0.12.0-512-g15b03eb3 -C graphics/text
echo v0.12.0-512-g15b03eb3 > lumps/freedoom.lmp
make[1]: Entering directory '/home/fred/freedoom-git/src/freedoom/graphics/text'
./textgen
./create_caption ../titlepic/freedm_titlepic.png fdmtitle.png
echo v0.12.0-512-g15b03eb3 > lumps/freedm.lmp
Traceback (most recent call last):
  File "/home/fred/freedoom-git/src/freedoom/graphics/text/./create_caption", line 21, in <module>
    txt1_size = draw.textsize(txt1, font=font)
                ^^^^^^^^^^^^^
AttributeError: 'ImageDraw' object has no attribute 'textsize'
make[1]: *** [Makefile:157: fdmtitle.png] Error 1
make[1]: *** Waiting for unfinished jobs....
```

Any idea?

**Comment by mc776** [comment]
Works fine for me and I have no idea how to unpack that.

What's the last commit that builds successfully?

**Comment by FredBezies** [comment]
Last time I build it was on June 6, 2023. Commit: 4b002550

**Comment by mc776** [comment]
The first commit after that one is just some updates to maps... I'm not sure the build system even looks into those files at all.

Did you try any of the commits in between then and now?

**Comment by mc776** [comment]
Can you try this commit first? https://github.com/freedoom/freedoom/tree/e88e10208bfe290ee475d3a2c74dd3e17b7052bc

Immediately after this commit is a change to the build process.

**Comment by FredBezies** [comment]
> Can you try this commit first? https://github.com/freedoom/freedoom/tree/e88e10208bfe290ee475d3a2c74dd3e17b7052bc
> 
> Immediately after this commit is a change to the build process.

Broken. Here is the output:

```

cp wivctms.png ../
./create_caption ../titlepic/freedm_titlepic.png fdmtitle.png
./rotate wikilrs_horiz.png 270 wikilrs.png
Traceback (most recent call last):
  File "/home/fred/freedoom-git/src/freedoom/graphics/text/./create_caption", line 21, in <module>
    txt1_size = draw.textsize(txt1, font=font)
                ^^^^^^^^^^^^^
AttributeError: 'ImageDraw' object has no attribute 'textsize'
cp wikilrs.png ../
make[1]: *** [Makefile:157: fdmtitle.png] Error 1

```

**Comment by FredBezies** [comment]
Could be a bug with python-pillow 10. Archlinux updates it on july 3rd, 2023.

https://archlinux.org/packages/extra/x86_64/python-pillow/

I will try downgrading python-pillow and try again.

**Comment by selliott512** [comment]
I've opened a [pull request](https://github.com/freedoom/freedoom/pull/1027) for this.

**Comment by FredBezies** [comment]
> I've opened a [pull request](https://github.com/freedoom/freedoom/pull/1027) for this.

FWIW, it worked from me on my archlinux with python pillow 10.x. Thanks a lot for the patch

**Comment by mc776** [comment]
I was about to link this to #1027 but I'd like someone who knows what they're doing to confirm it's fine before this gets closed.
