### ISSUE TITLE
rename rapid-fire melee weapon to "ripsaw"

### ISSUE THREAD

**Issue by mc776** [freedoom/freedoom#1022]
On the one hand, the sprite obviously looks more like a [circular rip saw](https://www.rona.ca/en/product/craftsman-circular-rip-saw-blade-10-in-dia-24t-atb-grind-geometry-carbide-teeth-cmas21024-00276813) than an angle grinder (a proposed but never submitted replacement sprite from a few years ago notwithstanding).

On the other, I can only infer that folks would rather avoid calling it a "saw" as a way to differentiate FD from Doom. (And we haven't lost hope that someone out there might eventually submit an actual angle grinder.)

The only discussion about this I can find on the repository is a brief mention in #694 with one person concurring unmitigatedly that it should be called a saw.

Searching the discord for "grinder" reveals no discussion about this at all. Searching "chainsaw" reveals a bunch of people just... calling it that out of force of habit, and the one time anyone corrects anyone with "angle grinder" it's with a ":p" followed by the corrector saying they normally just call it the chainsaw anyway. (And the person in question did not know the canonical name for the thing, just saw the picture, and called it a saw)

Thoughts?

**Comment by andOlga** [comment]
> On the other, I can only infer that folks would rather avoid calling it a "saw" as a way to differentiate FD from Doom

By that notion we should also rename the pistol and the shotgun to something else.
So I don't think that matters too much, I'm in favor of changing the name.

**Comment by mc776** [comment]
That was my thought as well.

Sure, we've got a lot more room for *designing* something totaly un-chainsaw-like here\* than we do for the pistol and shotguns, but we'll need the sprites for that anyway... and the sprites we *do* have right now look pretty plainly like a saw.

\*one idea is some kind of electric cattle prod pain compliance thing - maybe something that might've been used in the prison - that's just been permanently set to maximum power.

**Comment by mc776** [comment]
> * If you encounter a horde of flesh worms or stealth worms, The angle
>  grinder is a great weapon to use both to conserve ammo and avoid
>  taking damage.  Worms can’t attack while being sawed,

lol

**Comment by mc776** [comment]
> By that notion we should also rename the pistol and the shotgun to something else. So I don't think that matters too much, I'm in favor of changing the name.

To be fair, most of the documentation does trend towards "Handgun"... but that distinction completely disappears in the Spanish translation of the manual so nevermind!
