### ISSUE TITLE
New Punch sprites

### ISSUE THREAD

**Issue by superdave938** [freedoom/freedoom#1031]
![ezgif-5-f92a4d8a77](https://github.com/freedoom/freedoom/assets/71569097/0bdbebed-9bbf-4b48-a5de-5873c927a197)
[Fdnewpunch.zip](https://github.com/freedoom/freedoom/files/12074816/Fdnewpunch.zip)
I made new punch sprites

**Comment by mc776** [comment]
I just saw this issue after I made this comment seeing the ingame video on Discord:

> The animation looks as good as the doom fist will get, though the sprite itself is going to need work to look more like other Freedoom assets and less clearly like it was cut out from photos... I've actually commissioned a friend to try to touch up another fist animation I tried to make and depending on how that turns out I might be able to get her to give this set a try too

But that said, we could commit this now and any additional improvements to the sprite can be done later...

**Comment by mc776** [comment]
(adding the "bug" label since this would also fix the widescreen problem the current fist sprite has)

**Comment by Xindage** [comment]
que quality seems low, maybe it still need some touch up.

**Comment by mc776** [comment]
Just gave it an actual try ingame.

Here's a small edit that limits the left hand to be visible only on the A frame, and makes it less visible (and uses the hand position of the B frame). The reason for this edit is that when you hold down fire and punch continuously you never see the A frame, so with only one frame it just looks like the left hand is constantly blinking in and out of existence. The A frame fist is lower just so the transition isn't as abrupt.

I've also tweaked some of the offsets so there's a bit more of a contrast to imply some speed.
[fdpunch-edited.zip](https://github.com/freedoom/freedoom/files/12101536/fdpunch-edited.zip)

Thoughts?

**Comment by mc776** [comment]
> The reason for this edit is that when you hold down fire and punch continuously you never see the A frame, so with only one frame it just looks like the left hand is constantly blinking in and out of existence with no apparent motion.

I just noticed that this happens with the current sprite, it's just only visible if you disable the status bar.

Anyway, here's an attempt to clean up some of the photo artifact edges, scale down the height of the images to compensate for pixel scaling and add some highlights to make it look a little more like skin again. I think it's as good as the current sprite at this point - if no one points out any major glaring errors I may post a PR soon.
[pung.zip](https://github.com/freedoom/freedoom/files/12208534/pung.zip)

**Comment by mc776** [comment]
I'd have posted a PR by now, but with #1041 still outstanding I'm afraid of accidentally overwriting the offsets from that or vice versa...
