### ISSUE TITLE
New LOGO textures

### ISSUE THREAD

**Issue by superdave938** [freedoom/freedoom#1033]
I redid the logo textures
![Screenshot_20230721_155012](https://github.com/freedoom/freedoom/assets/71569097/667fd95e-3fe8-4cc9-a442-a6e3ffbcd843)
![Screenshot_20230721_160936](https://github.com/freedoom/freedoom/assets/71569097/de827339-0f61-4203-9330-b335bc7a5501)
[fdmnewpatch.zip](https://github.com/freedoom/freedoom/files/12134721/fdmnewpatch.zip)

**Comment by mc776** [comment]
I can turn this into a PR but how should you be credited in the [credits file](https://github.com/freedoom/freedoom/blob/master/CREDITS)?

**Comment by superdave938** [comment]
S: SuperDave938
D: textures
