### ISSUE TITLE
textures: consider making more stuff at least 128 tall.

### ISSUE THREAD

**Issue by mc776** [freedoom/freedoom#1035]
We've got a few textures that are 64 units tall. Which is fine for most cases, except when you try to put them on anything more than 64 units you end up with tutti-frutti.

Why not just make all of these tile at least once on a 128-unit-tall texture?

Is there an actual technical reason why that might not be a good idea?

**Comment by Talon1024** [comment]
> Is there an actual technical reason why that might not be a good idea?

High-res texture replacements, perhaps?

**Comment by mc776** [comment]
I'm reminded that textures.cfg already sorts everything in a logical fashion.

Nothing that is not found in an id IWAD is less than 128 tall.

No action both needs and can be taken on this issue.
