### ISSUE TITLE
100% secrets not possible on MAP19

### ISSUE THREAD

**Issue by Talon1024** [freedoom/freedoom#1070]
It is not possible to get 100% secrets on MAP19, unless you turn on noclip. One of the secrets is behind the newly-added guard rails.

**Comment by selliott512** [comment]
Good catch. Are there other cases where barriers have recently been added to levels that could make either 100% kills or secrets impossible? I can try a quick run through of recently modified levels, but I thought I'd ask if anything comes to mind.

**Comment by mc776** [comment]
This is just a case of editing an area where there was a secret and new sectors inherited the secret flag... we'd cleared a whole bunch of them before but this got re-introduced with the relatively recent edit.

**Comment by mc776** [comment]
[map19.zip](https://github.com/freedoom/freedoom/files/12373821/map19.zip)

Here's one possible alternative. It's still a relatively easy secret to find, but getting there without taking any damage might be another issue.

This un-solves the problem of the pinkies blocking you from below though...
