### ISSUE TITLE
Phase 1 - C2M3: Archaeology Site - "gotcha" switch denying access to secret exit

### ISSUE THREAD

**Issue by GrayFace** [freedoom/freedoom#1072]
Linedef 1970 causes the stairs to raise, which denies access to linedef 1974. The switch can't be switched off, thus ruining the run. Such cheap "gotcha" so deep into the level shouldn't exist IMO.

**Comment by GrayFace** [comment]
Also, for some reason the secret exit takes you to the same level as normal exit.

**Comment by mc776** [comment]
E2M3 has 1600 linedefs.

Please do not submit bug reports for the release version.

Daily builds are here: http://freedoom.soulsphere.org/
