### ISSUE TITLE
Is it possible to credit music authors + music titles individually?

### ISSUE THREAD

**Issue by unithecutie** [freedoom/freedoom#1074]
--Phase 1--

Title: untitled by Tyler "Picklehammer" Pantella
Title (OPL): "I Hate Fredrik Johansson" by Toby "Tobester" Collins Jr.
Intermission: ? by Jeremy "Vandalorian" Emerson
Victory: "Distance" by Korp
Bunny: "Sweet Little Dead Planet" by Goji

Episode 1 - Outpost Outbreak
	E1M1: untitled (e1m1.mid) by Ralph "Ralphis" Vickers
	E1M2: untitled (map02.mid) by Mark "TheMisterCat" McGill-Smith
	E1M3: "Alone with Colors" by Kevin "Velvetic" Martins & Jonathan "julnen" Martins
		E1M9: "Derelict" by continuum.mid
	E1M4: "Flood the City" by Kevin "Velvetic" Martins & Jonathan "julnen" Martins
	E1M5: "The Raging Sun" by Kevin "Velvetic" Martins & Jonathan "julnen" Martins
	E1M6: "Panic" by Anthony "Ajanddino" Pierce
	E1M7: "Sewers" by Discoholic, originally by Samuel "Blastfrog" Oliver
	E1M8: "On the Next Day" by Kevin "Velvetic" Martins

Episode 2 - Military Labs
	E2M1: "Moonstone" by Korp
	E2M2: "Voidgaze" by Korp
	E2M3: "Reminiscence" by Korp
	E2M4: "Concept of Technology" by Korp
	E2M5: "Nightstorm" by Korp
		E2M9: "Tunnel" by Anthony "Ajanddino" Pierce
	E2M6: "Diodine" by Korp
	E2M7: "Ribcage" by Korp
	E2M8: "Treble Dissension" by Korp

Episode 3 - Event Horizon
	E3M1: untitled by Tyler "Picklehammer" Pantella, modified by Obsidian Plague and m
	E3M2: ? by Lola "BlueWorrior" Harvey
	E3M3: ? by Lola "BlueWorrior" Harvey
	E3M4: ? by Lola "BlueWorrior" Harvey
	E3M5: ? by Lola "BlueWorrior" Harvey
	E3M6: ? by Lola "BlueWorrior" Harvey
		E3M9: "Lipstick" by Jeremy "Vandalorian" Emerson
	E3M7: ? by Lola "BlueWorrior" Harvey
	E3M8: ? by Lola "BlueWorrior" Harvey

Episode 4 - Double Impact
	E4M1: "Liberate the Stars" by continuum.mid
	E4M2: "Fight Harder... To Obtain a Better Victory" by Proxy-MIDI
		E4M9: "The Deepest Secrets" by continuum.mid
	E4M3: "Space Spectre" by Matzu
	E4M4: "Deliberate Concealment" by continuum.mid
	E4M5: "Main Code" by Korp
	E4M6: "Andromeda" by ZeMystic
	E4M7: "Ambiguity" by Korp
	E4M8: "Vs. The Assault Quindecapod" by continuum.mid

--Phase 2--

Title: untitled by Tyler "Picklehammer" Pantella
Intermission: untitled by Tyler "Picklehammer" Pantella
Story: "Dave3D07" by jute

Cluster 1
	MAP01: ? by Lola "BlueWorrior" Harvey
	MAP02: ? by Lola "BlueWorrior" Harvey
	MAP03: "Demon Dance" by Discoholic
	MAP04: "Indigo" by Korp
	MAP05: ? by Lola "BlueWorrior" Harvey
	MAP06: "Refrigeration" by Korp
	MAP07: untitled (map01.mid) by Ralph "Ralphis" Vickers
	MAP08: ? by Lola "BlueWorrior" Harvey
	MAP09: ? by Lola "BlueWorrior" Harvey
	MAP10: "Soviet Porno" by Jeremy "Vandalorian" Emerson
	MAP11: "Inside the Ruins" by Korp

Cluster 2
	MAP12: ? by Bradley "BobFromReboot" Lavigne
	MAP13: "Fear" by Discoholic
	MAP14: "About the Summer" by Kevin "Velvetic" Martins & Jonathan "julnen" Martins
	MAP15: ? by Lola "BlueWorrior" Harvey
		MAP31: ? by Lola "BlueWorrior" Harvey
			MAP32: "Black Mountain" by Kevin "Velvetic" Martins & Jonathan "julnen" Martins
	MAP16: "Reflection" by Scragadelic
	MAP17: ? by Lola "BlueWorrior" Harvey
	MAP18: "Realistic Approach" by Kevin "Velvetic" Martins
	MAP19: ? by Julian "Julian Hope" Aubourg, modified by m
	MAP20: "Dave3D05" by jute

Cluster 3
	MAP21: "Rough Landing" by Korp
	MAP22: "Alien Waltz" by Korp
	MAP23: "Within the Trilo's Den" by FrostByte and Korp
	MAP24: "Space's Despair" by Korp
	MAP25: "I Sought Wisdom in the Chalice But There Was None" by Jeremy "Vandalorian" Emerson
	MAP26: "Stormer" by Korp, originally by Samuel "Blastfrog" Oliver
	MAP27: "Dreamcatcher (Black and Blue)" by Kevin "Velvetic" Martins & Jonathan "julnen" Martins
	MAP28: ? by Lola "BlueWorrior" Harvey
	MAP29: untitled by Varis Alpha
	MAP30: "Devoured by the Jaws of Defeat" by Korp

--FreeDM--

Title: (same as Phase 2)
Intermission: (same as Phase 2)
Story: (same as Phase 2)

DM01: untitled (crudreams2.mid) by Ralph "Ralphis" Vickers
DM02: untitled (crudreams3.mid) by Ralph "Ralphis" Vickers
DM03: "Dynamite!" by Korp
DM04: "Rush" by Kevin "Velvetic" Martins and Simone Alauk
DM05: ? by Tyler "Picklehammer" Pantella
DM06: "Workout" by Korp
DM07: "I Fell Off The Stairs" by Korp
DM08: "Jump Is Not Allowed!" by Korp
DM09: ? by Matias "jupiter_ex" Roldan
DM10: ? by Bradley "BobFromReboot" Lavigne
DM11: untitled (map01.mid) by Mark "TheMisterCat" McGill-Smith
DM12: "Parallax" by Korp
DM13: "Shut It" by Korp
DM14: "Munt Battle" by Mark "TheMisterCat" McGill-Smith
DM15: "Neat" by Ralph "Ralphis" Vickers
DM16: "Deathmatch Construct" by Korp
DM17: untitled (d_stlks3.mid) by Vincent "Vicious" Fong
DM18: "Metadata" by Korp
DM19: "Tap Water" by Korp
DM20: "Quirkspitter" by Korp
DM21: "Friendly Fire" by Korp
DM22: "Red Foot" by Kevin "Velvetic" Martins and Simone Alauk
DM23: "White Lights" by Kevin "Velvetic" Martins and Jonathan "julnen" Martins
DM24: ? by Matias "jupiter_ex" Roldan
DM25: "Shoot 'em All" by rostuhan
DM26: "Dave3D09" by jute
DM27: ? by Jeremy "Vandalorian" Emerson
DM28: untitled (ctf2.mid) by Ralph "Ralphis" Vickers
DM29: untitled (crudreams.mid) by Ralph "Ralphis" Vickers
DM30: "Freedom for Your Shooting Skills" by rostuhan
DM31: "The Syntax of Time" by Kevin "Velvetic" Martins
DM32: "Bullet Hell" by rostuhan

**Comment by EnzoCarozza** [comment]
Can someone help find more of these?

@KorpKat what is the name of your MAP07 track?

**Comment by EnzoCarozza** [comment]
I've got a near complete list now! I just need the track titles. :D

MAP01: unknown - Lewis "BlueWorrior" Harvey
MAP02: unknown - Lewis "BlueWorrior" Harvey
MAP03: unknown - Lewis "BlueWorrior" Harvey
MAP04: MogulFreedoomMusic8 - Jeremy "Mogul" Emerson
MAP05: unknown - Lewis "BlueWorrior" Harvey
MAP06: Refrigeration - @KorpKat 
MAP07: unknown - Ralph "Ralphis" Vickers
MAP08: unknown - Lewis "BlueWorrior" Harvey
MAP09: unknown - Lewis "BlueWorrior" Harvey
MAP10: unknown - Tyler "Picklehammer" Patella
MAP11: Inside the Ruins - @KorpKat 
MAP12: unknown - Bradley Lavigne
MAP13: unknown - bytebeats
MAP14: About the Summer - Isotype (Kevin & Jonathan Martins)
MAP15: unknown - Lewis "BlueWorrior" Harvey
MAP31: unknown - Lewis "BlueWorrior" Harvey
MAP32: Black Mountain - Isotype
MAP16: Reflection - Scragadelic
MAP17: unknown - Lewis "BlueWorrior" Harvey
MAP18: Realistic Approach - Isotype
MAP19: unknown - (author possibly deadname of @jnechaevsky according to https://github.com/freedoom/freedoom/tree/d320d4d00456c96729e811e0a81acdeb7ea06c69/musics/julian or is this a different julian?)
MAP20: Dave3D05 - jute
MAP21: Rough Landing - @KorpKat 
MAP22: Alien Waltz - @KorpKat 
MAP23: Within the Trilo's Den - AxelMoon & @KorpKat 
MAP24: Space's Despair - @KorpKat 
MAP25: MogulFreedoomMusic11  - Jeremy "Mogul" Emerson
MAP26: Stormer - @KorpKat 
MAP27: Dreamcatcher (Black and Blue) - Isotype
MAP28: unknown - Lewis "BlueWorrior" Harvey
MAP29: unknown - Varis Alpha
MAP30: Devoured by the Jaws of Defeat - @KorpKat 

Title: unknown - Tyler "Picklehammer" Patella
Intermission: unknown - Tyler "Picklehammer" Patella
Read Me: Dave3D07 - jute

**Comment by EnzoCarozza** [comment]
https://doomwiki.org/wiki/Freedoom:_Phase_2_music
Currently working on a Doomwiki page.

**Comment by unithecutie** [comment]
Edited the credits here, "?" means the title is unknown as of now.
If these could be arranged in the credits file, that would be great.
If you are to credit me as well;
`N: Enzo Carozza, S: uni, E: dudetank4@gmail.com`

**Comment by mc776** [comment]
I think the best thing to do would be to add this as a separate music credits file...

**Comment by unithecutie** [comment]
[fdmuscredits.txt](https://github.com/freedoom/freedoom/files/12702126/fdmuscredits.txt)
I've no idea on how to use GitHub, so here's the text file currently.

**Comment by rostuhan** [comment]
I approve the titles of my music (FreeDM), that's just how I titled them in that one message on Discord.
