### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by chungy** [freedoom/freedoom#109]
Eventually Python 2.7 is going to become less common or decreasingly used as the default Python interpreter for many installations and distributions (Arch Linux already uses python3 by default), we really ought to upgrade all of the programs part of the build system to be compatible with Python 3.x, hopefully while still supporting Python 2.7.

Right now, this isn't too critical as it is not hard to just use virtualenv-2.7 to force Python 2.7 to be used by default in your environment, but it's an extra step that ideally needs to not exist.

**Comment by chungy** [comment]
This was fixed a long time ago. :)

**Comment by jmtd** [comment]
> This was fixed a long time ago. :)

Except, all your shebangs are still `/usr/bin/env python`, so on a pure Python 3 system, they will not work, with the exception of Arch, which installs `python3` with the name  `python`, against upstream's advice.

You probably want to move the shebangs to `python3`.

**Comment by chungy** [comment]
Our scripts have been made to be compatible with both 2.7 and 3.x, and that's perfectly in accordance with [PEP 394](https://www.python.org/dev/peps/pep-0394/). I wouldn't be bothered much if we want to go 3-only, but I don't think there's any advantage.

**Comment by fragglet** [comment]
Looks like Fedora also just switched `/usr/bin/python` to point to `python3`.

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/ZXP6BQWXRTVJRVUTRWNMUTLLSQGPHCAS/
