### ISSUE TITLE
Why are yellow keys orange?

### ISSUE THREAD

**Issue by mc776** [freedoom/freedoom#1103]
Is there some kind of historical reason for it, or is there an accessibility issue, or... ?

**Comment by mc776** [comment]
Here are the commits where it happened:
https://github.com/freedoom/freedoom/commit/43aae112e7728754445dc4278733a0a5869b16f7
https://github.com/freedoom/freedoom/commit/59342c6e5f1a7a2bc33de93b2749883851e0e381

2016-17. I can't find anything in the forum thread or the PRs about the change in hue. I thought it might've been some kind of technical issue but I guess not???

**Comment by selliott512** [comment]
Good question. PLAYPAL does have a a few yellow options that I would think would work.

**Comment by mc776** [comment]
It seems the only real answer is that the "pure" yellow is too limited in its palette.

In my PR the dark parts tend to go into the deep orange parts of the palette with a bit of brown here and there, but it should still give a more distinct yellow that can't be confused with red for anyone with full colour vision.
