### ISSUE TITLE
E4M2 - The safe path back from blue key area is inaccessible.

### ISSUE THREAD

**Issue by GrayFace** [freedoom/freedoom#1109]
Here is the place on the map: 
![screenshot 386](https://github.com/freedoom/freedoom/assets/5989806/4887daf8-1ce4-430a-b559-9b0bd99aff0e)

When you get the blue key and go out through toxic waste, you can go back (through a teleporter or do it the normal way). When you do so, you can open the blue door, but it's blocked by a platform:
![screenshot 385](https://github.com/freedoom/freedoom/assets/5989806/9e877689-e6b8-43cd-897d-1ffedb10b8e7)

The only way out is to through the toxic waste again, this time without a hazard suit.

**Comment by mc776** [comment]
...what in the world even *is* this supposed to be

Looking at the map editor there doesn't seem to be any way to get into that room, it's just this bullshit gotcha fakeout with the blue door that at best might kill or softlock you even if you managed to get inside.

Trying to play from the beginning to see how all this is supposed to work I'm completely stuck after hitting the switch after the lowering cross room...

**Comment by mc776** [comment]
I think I understand.

There's an optional bridge that lets you access that area before you get the blue key. Once you get in there, the bridge collapses again. This is a one-time thing so if you miss it the first time you'll never get it.

Ideally both actions should just be made repeatable indefinitely...

**Comment by mc776** [comment]
Confirmed just changing both specials to their "R" equivalents works in Chocolate.
[e4m2.zip](https://github.com/freedoom/freedoom/files/12563957/e4m2.zip)

**Comment by mc776** [comment]
Logic fail right there. The bridge needs to remain available - making the *collapse* also repeated defeats the purpose.

Here's a much more thoroughly tested attempt. Get the blue key, take the radsuit, go through the nukage, re-activate the bridge, cross the bridge, let the blocker-room unblock, retrace steps to blue key, take teleport back up to boardwalk, go back into old blocker-room and cross the bridge back whence you came.
[e4m2.wad.zip](https://github.com/freedoom/freedoom/files/12565184/e4m2.wad.zip)
