### ISSUE TITLE
E4M9 - You can accidentally lock yourself out of an area

### ISSUE THREAD

**Issue by GrayFace** [freedoom/freedoom#1110]
In an area at the end of the map you get ambushed and have cell door closed behind you. Here is the place:
![screenshot 392](https://github.com/freedoom/freedoom/assets/5989806/6ea02517-a773-48c6-868e-0f13aada0c2b)

You can escape the place without opening the cell door by dropping into toxic waste and riding the lift up. If you do so, the cell door stays closed and you can't go back into the area:
![screenshot 391](https://github.com/freedoom/freedoom/assets/5989806/6b7ef6f7-068e-4f5c-a557-4e513ce0261b)

**Comment by mc776** [comment]
I think the best solution is to make the southern ledge of that slime pit a 1-use trigger for lowering the force field.

How's this? [e4m9.zip](https://github.com/freedoom/freedoom/files/12563367/e4m9.zip)
