### ISSUE TITLE
[Workflow Suggestion] Have you considered using "Obsidian" to fill in the "still blank" levels?

### ISSUE THREAD

**Issue by SecularSteve** [freedoom/freedoom#1119]
Not entirely [Obsidian](https://github.com/obsidian-level-maker/Obsidian) of course, but modifying the generated maps as a base.

Maybe even for FreeDM to fix some of the panned maps.

But of course, that's just a suggestion.

**Comment by mc776** [comment]
We have more maps than we have slots for right now.

What was the last version of Freedoom you've played?

**Comment by SecularSteve** [comment]
0.12.1

**Comment by SecularSteve** [comment]
I apologise for being an asshole. I made an impulsive decision.

In that case, I think the "[Help Freedom!](https://freedoom.github.io/help.html)" page needs to be updated.

I just started playing it like yesterday, and I was not aware of how far on the roadmap it came.

I don't want to make enemies here. I just did something stupid.

**Comment by mc776** [comment]
I've been told by another maintainer that I'm being a dick here.

Just some unsolicited general advice about unsolicited advice: before giving it, poke around the site, the forums, the issues and PRs, the recent commits, the person in question's profile* etc., and see if that has been considered before, or if the underlying problem you're imagining yourself providing help on actually exists or is actually the kind of problem you think it is. Only after understanding that should the advice be considered as a candidate for something to post - which may take anywhere from a few minutes to a few weeks, but then if this had been a matter of any genuine urgency the person posting about the problem would have made that abundantly clear.

*You might be surprised at how often "[the advice you were going to give] gets instantly blocked" on people's personal social media accounts
