### ISSUE TITLE
replacing FLAT4

### ISSUE THREAD

**Issue by mc776** [freedoom/freedoom#1129]
![_](https://github.com/freedoom/freedoom/assets/24984517/1d183b2e-5437-4bb4-8441-b70f1c8c6639)
Here is the FLAT4 from Doom, compared with the FLAT4 currently in Freedoom. Try and guess which one's which. (hint: rot13 SQ vf ba gur yrsg.)

It's not really used for much in FD anyway, but it should be replaced.

PGE came up with a nice, fairly straightforward original alternative on Discord:
[removed by request]

but it was also mentioned that the Aquatex grid meshes don't have any flat equivalent that isn't 2 grids combined into one texture, so this might see more use:
![flat4-aq](https://github.com/freedoom/freedoom/assets/24984517/3528728f-3a63-44d1-b300-6b5b43c55411)

I think FLAT4 needs to be replaced in any event, but what are people's preferences here as to which the replacement should be?

Or is it time to add a new flat?

**Comment by mc776** [comment]
I think the best course of action is to add PGE's FLAT4 *and* a new AQF077.

This does raise some potential concerns about getting too close to the maximum possible number of lumps in a vanilla-compatible IWAD though...

**Comment by mc776** [comment]
Still thinking about that new AQ flat but it's not about replacing FLAT4 at this point.

**Comment by Talon1024** [comment]
I think the Aquatex-based FLAT4 should replace FD's existing FLAT4, and PGE's FLAT4 would work better in Blasphemer as a base for a FLOOR08 replacement.

**Comment by mc776** [comment]
Yeah, now that I think about it that's probably the best way to go... the current FLAT4 is hardly used at all and the only reason to make the new flat take up a different slot is so it can be named similarly to the other Aquatex flats, which as far as problems go is a drop in the ocean compared to how everything else is named.

Fastest way to get such a replacement merged is for you to post the PR and for me to approve it, for what it's worth...
