### ISSUE TITLE
Additional music credits.

### ISSUE THREAD

**Issue by unithecutie** [freedoom/freedoom#1134]
Korp's current E1M6 track is a remix of "Dave3D35" by jute.
Korp's current E1M9 track is a remix of "Dave3D42" by jute.

I've no idea how to use GitHub - so I don't know how to PR this myself.

**Comment by unithecutie** [comment]
More titles for Mark "TheMisterCat" McGill-Smith

map01.mid = DM11
map02.mid = E1M2

![image](https://github.com/freedoom/freedoom/assets/139153158/02881889-fef1-4189-88a4-2471d854257a)

**Comment by unithecutie** [comment]
Korp's current MAP24 track is a remix (?) of "Balancing Act" by Andrew Bassett.

**Comment by unithecutie** [comment]
Discoholic's current MAP12 track is a remix of "Wasteland Scavengers" by Samuel "Blastfrog" Oliver - use instead of "originally by x" for here.

**Comment by unithecutie** [comment]
Replace "jute" with full name "Jute Gyte".

**Comment by unithecutie** [comment]
And another one - Jute's real name is "Adam Kalmbach".

**Comment by mc776** [comment]
Has he confirmed which name and formatting thereof is preferred?

**Comment by unithecutie** [comment]
Nope, Xymph added this to DoomWiki just now from his Bandcamp page - and I doubt he'll randomly show up out of nowhere with his Doomworld account being inactive since 2018.

**Comment by mc776** [comment]
....let's just leave it as is for now

**Comment by unithecutie** [comment]
![image](https://github.com/freedoom/freedoom/assets/139153158/d00a397d-ca89-4dba-8462-004740a1446c)
Alright, managed to actually contact them; credit them as just "jute" per their request and change all "dave3d##" tracks to `untitled (dave3d##.mid) by jute`.

**Comment by unithecutie** [comment]
Update `Scragadelic` to be `Josef "Moonflower" Griffiths`? Can't find a working contact anywhere so I don't know if there's a preferred way for them to be credited.
https://www.doomworld.com/news/scragadelic-mp3s-r1935/
![image](https://github.com/freedoom/freedoom/assets/139153158/69df6d90-d129-4a12-adfb-736a45a18903)

**Comment by mc776** [comment]
Please just stick with information people have somehow indicated their consent to be put on the FD credits - proactively tracking people down like this is not a good look.

**Comment by mc776** [comment]
On the othe hand, I just noticed a deadname in the main credits file...

**Comment by unithecutie** [comment]
Alright.

And if you want to add the MIDI file names for Picklehammer's tracks;
"ph-doom.mid" for E3M1
"ph-dm2ttl.mid" for Phase 2 title
"ph-dm2int.mid" for Phase 2 intermission
"ph-untitled.mid" for Phase 1 title

**Comment by mc776** [comment]
I wonder if we could just, like, somehow blast an announcement to everyone who's contributed to FD to see if they want anything updated... still kinda wondering about this whole thing with old handles or old emails (or old walletnames for that matter) in some of these really old entries...

**Comment by unithecutie** [comment]
And there's BlueWorrior's track names.
![image](https://github.com/freedoom/freedoom/assets/139153158/c4b9c4bd-6939-435a-93c2-41084e87c4a3)

**Comment by unithecutie** [comment]
![image](https://github.com/freedoom/freedoom/assets/139153158/40968522-7f2f-47f1-a451-3818271b9d1e)
Completely remove her pseudonym as per request.

**Comment by unithecutie** [comment]
![image](https://github.com/freedoom/freedoom/assets/139153158/a569d947-f19e-4aaf-8e4a-7ea987d51fbf)
Nevermind, reject.

**Comment by unithecutie** [comment]
Oops, forgot about this; BobFromReboot's tracks are untitled.
![image](https://github.com/freedoom/freedoom/assets/139153158/9a0d5613-c443-4742-8922-cedfdfeee671)

**Comment by unithecutie** [comment]
The MIDI names are "Doom1.mid" for DM11 and "Doom2Alt.mid" for the former MAP12.

**Comment by mc776** [comment]
Updated but I assume you meant DM10

**Comment by unithecutie** [comment]
Yeah, my mistake.

**Comment by unithecutie** [comment]
![image](https://github.com/freedoom/freedoom/assets/139153158/1363b7d2-e698-4747-9380-aa1e9698881b)
DM27: "Music for Freedoom 7"
PH1 Intermission: "Music for Freedoom 10"

**Comment by unithecutie** [comment]
![image](https://github.com/freedoom/freedoom/assets/139153158/2e715648-e318-41f3-b060-c53b355c016a)
Picklehammer track titles!

**Comment by unithecutie** [comment]
MAP29: untitled (freedoom.mid) by Varis Alpha

DM09: untitled (freedoom2.mid) by Matias "jupiter_ex" Roldan
DM23: untitled (freedoom3.mid) by Matias "jupiter_ex" Roldan

**Comment by mc776** [comment]
> Picklehammer track titles!

Any idea which of these d_dm05 is?

**Comment by unithecutie** [comment]
> Any idea which of these d_dm05 is?

ph-shawn.mid, "Riders of Hell"

**Comment by mc776** [comment]
I did notice the naming convention, but those tracks have been swapped around so many times I couldn't make sense of the git history.

So right now the only "?" is d_map19. I'll set #1135 to ready and if Julian gives us a name later we can deal with it then.

**Comment by unithecutie** [comment]
Should we push the title "Deceit" instead, like I mentioned in the Discord server? (the one me and Korp (?) went for)
It works for the piano and tremolo strings versions.

It's going to be a PITA if we leave this one unknown and I don't think it's a good idea to bother Julian about it again from what Fraggle's said.
![image](https://github.com/freedoom/freedoom/assets/139153158/500ee291-dd9a-4fbe-bff1-cd8d0e8f87ff)

**Comment by mc776** [comment]
> Deceit

Absolutely unacceptable. I will be deleting the PR immediately.
