### ISSUE TITLE
Any plans to use Haaslok's circular saw design?

### ISSUE THREAD

**Issue by SenhorFlibble** [freedoom/freedoom#1152]
Apologies if this is not the right place to bring this up -- I'm not sure how often you guys check the forums nowadays -- but a while ago @Haaslok made an unfinished (looks like one frame only) new circular saw sprite that looks really good (IMO):
![83ad6439-703c-4457-a61f-a5984216db41 png 2007e8e980fc933c3a06544864845ae2](https://github.com/freedoom/freedoom/assets/26299789/d52b4802-1533-4bfd-909c-d6e4c0e2bcd1)
It was posted in [this thread](https://www.doomworld.com/forum/post/1904022), but apparently never completed. Since most of the weapons recently received a touch-up and visual upgrade, I was wondering if this version could be made a base for a new circular saw, or are you going to just touch-up the old _Freed∞m_ version?

**Comment by mc776** [comment]
Assuming Haaslok's still okay with using this, who's in charge of finishing the sprites?

**Comment by mc776** [comment]
I don't think this is going anywhere anytime soon... if Haaslok or anyone else really does have a set of sprites ready to go a PR can be posted then.
