### ISSUE TITLE
M_PAUSE off center

### ISSUE THREAD

**Issue by fawtytoo** [freedoom/freedoom#1153]
Doom's source code has a hard coded width value for the pause graphic of 68 pixels. Freedoom's is only 52 pixels wide.

**Comment by mc776** [comment]
added the fonts tag because right now FD's M_PAUSE is generated through the text-graphic system but i think the best solution is to... not do that.

Could be nice to have an all-new original pause graphic...

**Comment by mc776** [comment]
thoughts?
![Clipboard01](https://github.com/freedoom/freedoom/assets/24984517/073dd9d6-69a0-4466-86f6-9a0d6784ac25)

**Comment by fawtytoo** [comment]
![m_pause2](https://github.com/freedoom/freedoom/assets/17235825/f329ad50-c571-4e3b-bf38-d2b57e2fda4c)

**Comment by mc776** [comment]
So it turns out that we can just edit buildcfg to give the pause graphic an X offset of -8:
![curr](https://github.com/freedoom/freedoom/assets/24984517/883bf704-e447-45e8-b20c-0937dc5df898)
![buildcfg-8](https://github.com/freedoom/freedoom/assets/24984517/db7860c4-591f-4110-8166-f869aee4f508)

**Comment by fawtytoo** [comment]
Either way, it just needs to be central. I guess it must offset every column to be drawn. This way, it would maintain it's aesthetics with other text.

**Comment by fawtytoo** [comment]
Just a thought, but what about source ports that might use the width of m_pause instead of the hard coded 68. The x offset will only make m_pause 60 pixels wide.

**Comment by mc776** [comment]
That's why I've got the new PR.

**Comment by fragglet** [comment]
It looks weird to see the text in that one graphic spaced differently to all the other text graphics. What was wrong with the offset-based approach?

> Just a thought, but what about source ports that might use the width of m_pause instead of the hard coded 68. The x offset will only make m_pause 60 pixels wide. Or is the width still 52 pixels?

Do any exist? We shouldn't jump through hoops to work around things that are entirely hypothetical.

**Comment by mc776** [comment]
GZDoom not only uses the width, but it also ignores the graphic's own offset.

My own preference would be a whole new custom pause graphic but I am low on ideas.
