### ISSUE TITLE
Jaws of Defeat textures contain copyrighted material

### ISSUE THREAD

**Issue by fragglet** [freedoom/freedoom#1158]
They contain parts of a Hexen metal texture. Thanks to Talon1024 on Discord for noticing this and PGE for the following illustrative GIFs.

![JoD_Hx1](https://github.com/freedoom/freedoom/assets/96821/680f72e2-3b76-47aa-9b40-184565e8f767)
![JoD_Hx2](https://github.com/freedoom/freedoom/assets/96821/be41b33d-d0b8-4161-b4f9-803232b8f2b6)

Texture patch filenames are:

* rwdmon1.png (small parts)
* rwdmon4.png
* rwdmon5.png
* rwdmon7.png
* rwdmon8.png
* rwdmon9.png
* rwdmon10.png

**Comment by fragglet** [comment]
Obviously we need to replace these textures but I'm not sure how much work is going to be involved. If someone doesn't step up to provide immediate replacements then I recommend we either replace them with blank textures or copy a different similar texture.

**Comment by mc776** [comment]
Has anyone volunteered to do new ones yet?

**Comment by fragglet** [comment]
Putting together a PR now.

**Comment by mc776** [comment]
Should BOSSBACK be replaced? I can't quite see it but it does seem to have a bit of that original panelling: https://github.com/freedoom/freedoom/blob/master/graphics/bossback.png
