### ISSUE TITLE
make script is reporting missing files.

### ISSUE THREAD

**Issue by Xindage** [freedoom/freedoom#1170]
while i was building the wads to test i noticed that the builder reported me 2 warning when compiling each iwad, they're the same on all compilations:

w PC90 could not find file ./patches/snak5_1.wad, .png, .ppm, .bmp or .gif
w PC90 could not find file ./patches/snak6_1.wad, .png, .ppm, .bmp or .gif

Should we worry about it?

**Comment by mc776** [comment]
I may have accidentally copypasted something from #1140...

**Comment by mc776** [comment]
Found it, accidentally included it in #1144.

I think the error should just go away if we merged #1140 now - all it does is introduce new usable content so I don't see any reason why anything would break if we did.
