### ISSUE TITLE
phase 1 map issues.

### ISSUE THREAD

**Issue by Xindage** [freedoom/freedoom#1181]
bugs present after the map tweaks pull https://github.com/freedoom/freedoom/pull/1121
freedoom1 on complevel 3
e1m2:
linedef 1944: pillar texture misaling
sector 359: bugged shadow sector
e1m5:
sector 105: monsters will likely get stuck on the edge of this lift
e1m9:
linedef 572: you can run into the fence to take armour before you're meant to
e1m6:
thing 62: floating stimpak when the lift is activated
e1m7:
sector 303: the secret sector is so thin you can walk in and out without activating it
e1m8:
doom-style crosses and hell theme instead of freedoom
e2m9:
linedef 1334: door bugged and unusable if W1 in front of it not spent
e3m4:
linedef 2133: missing exit action on the front of the exit
e3m5:
doom-style hell church theme
e3m6:
thing 46: annoying torch blocking the path above it
e3m9:
thing 17: floating candle
linedef 3243: misaligned face texture
e4m1:
thing 67: shotgunner likely to bring the lift down and get himself stuck on the ledge
sector 109: thin secret sector, can run over without tagging
e4m2:
sector 190: thin secret sector, can run over without tagging
sector 363: thin secret sector, can run over without tagging
sector 347: thin secret sector, can run over without tagging
sector 752: thin secret sector, can run over without tagging
e4m3:
linedef 2087: broken shadow detail
sector 273: thin secret sector, can run over without tagging
e4m6:
linedef 800: texture misalignment?
e4m7:
sector 709: thin secret sector, can run over without tagging
sector 568: node builder error causing light distortions on the floor

Note from xindage: I'll probably be locking edits on this chapter of freedoom today after i finish the demos so if someone wants to present a fix, sorry but it would be need to be fast (around 4-6 hours left from when i posted it)

**Comment by mc776** [comment]
What does "bugged shadow sector" mean?

**Comment by mc776** [comment]
Not fixing E1M8 in this time frame...

**Comment by mc776** [comment]
e4m7:
> sector 709: thin secret sector, can run over without tagging
I can't find this sector.

> sector 568: node builder error causing light distortions on the floor
This seems to be impossible to fix.

**Comment by Xindage** [comment]
> > sector 568: node builder error causing light distortions on the floor
> 
> This seems to be impossible to fix.

Sometimes copying all the stuff, deleting and pasting again solve these kind of errors, not sure why tho.

**Comment by mc776** [comment]
It just kinda looks like this weirdly shiny wet floor at this point, nothing too breaking...

**Comment by mc776** [comment]
I don't really see anything particularly "hell-style church theme" for E3M5, besides the overall gore stuff that's common to pretty much all of E3. Is there any specific area in question?

**Comment by mc776** [comment]
> Not fixing E1M8 or E3M5 in this time frame...

Neither of these maps is in any of the demos from #1183, so if anyone wants to address these we've still got time.

(Same for E4M7 in case anyone who has any clue why that glitch is happening wants to take a stab at it)

**Comment by mc776** [comment]
[e1m8.zip](https://github.com/freedoom/freedoom/files/13312719/e1m8.zip)
![DOOM00](https://github.com/freedoom/freedoom/assets/24984517/7469b72c-178c-476a-bbe3-2c8d07f0a48e)

**Comment by mc776** [comment]
[e3m5.zip](https://github.com/freedoom/freedoom/files/13313091/e3m5.zip)
Figured since we've already got that "AGM" sign there...
![DOOM04](https://github.com/freedoom/freedoom/assets/24984517/9cb77f9f-935d-4ca5-96dc-046632dfb1a8)
![DOOM03](https://github.com/freedoom/freedoom/assets/24984517/25071890-825b-4314-88ec-a59c2bc4204b)

**Comment by mc776** [comment]
It's been a month with no one pointing out that actually one of the listed items is still a problem, so I'll take it the only remaining live issue is the visual anomaly on E4M7 sector 568 which may or may not be fixable.
