### ISSUE TITLE
Freedoom Phase 2: Map issue

### ISSUE THREAD

**Issue by KAdamsminuteman** [freedoom/freedoom#1189]
In Freedoom Phase2: Map 03, there is a secret item you can grab though the wall (at least using Crispy Doom 6.0) here is an attached screenshot of the area in question 
![image](https://github.com/freedoom/freedoom/assets/148830647/b88c26b3-014f-4fe0-9353-7cc528014bac)

**Comment by Xindage** [comment]
Ok we can fix it post release, this map is hard locked until them because this map has a demo for version 0.13

**Comment by unithecutie** [comment]
https://github.com/freedoom/freedoom/assets/139153158/6d31542e-5b0e-4ae7-a51e-d082407d0d33

**Comment by mc776** [comment]
Generally any change is going to mess up a demo, even if there's no direct interaction, so if there is a change at minimum the demo should be checked as well.

That said, #1173 doesn't have Map03 at all, so we are free to fix this without affecting any current demos.

**Comment by Xindage** [comment]
it is map03, it was a error from my side, selliot fixed it by mentioning the first demo is map03, not 04.

**Comment by mc776** [comment]
Notwithstanding the absolute lack of urgency at this point I think this should fix it:
[map03.zip](https://github.com/freedoom/freedoom/files/13312510/map03.zip)

(I've also taken the liberty of merging a few redundant sectors and adding soundblockers and visible bars to the DM arena boundary.)

**Comment by Xindage** [comment]
i'll check if demo does not break
if it does it'll be dealayed

**Comment by mc776** [comment]
It will almost certainly break and if I PR this I will be adding the new deferred tag to it.

I'm just not 100% sure I've actually fixed it or if some much more persistent and experienced speedrunner could manage it anyway...

**Comment by mc776** [comment]
Fixed in #1191
