### ISSUE TITLE
FreeDM Needs no more than 10 DM spawns per map.

### ISSUE THREAD

**Issue by Catoptromancy** [freedoom/freedoom#122]
Our FreeDM demos found bugs on a couple ports. Which leaves another issue. 

Vanilla Doom can only handle 10 spawns. Any more spawns than that are ignored. If a mapper has the intended gameplay of 16 spawns, the map is already broken as some of those wont even work. 
All FreeDM maps need 10 player spawns at the most. 

Well this issue only affects vanilla. All the multiplayer port will support many more DM spawns. So vanilla and ports will have a different gameplay since some spawns will be disabled in vanilla.

**Comment by Proluiz** [comment]
hey guys sorry reviving it but in my freedm rework i'm taking this issue too, every map of i work only uses only 10 dm spawns.
