### ISSUE TITLE
Improve E1M2 doortrak.

### ISSUE THREAD

**Issue by MerrittK** [freedoom/freedoom#1245]
![C1M1_001](https://github.com/freedoom/freedoom/assets/83965343/6ad8d48c-8ac1-4bff-b68f-ebe1510ed6e4)

As you move towards it, or backwards from it, it really "strobes", with the lines becoming wider and thinner:
![C1M1_002](https://github.com/freedoom/freedoom/assets/83965343/5b5ffb90-0d60-4c63-99a2-d600f77c7fa8)

_Originally posted by @dftf-stu in https://github.com/freedoom/freedoom/issues/1240#issuecomment-1862870735_

**Comment by MerrittK** [comment]
In this situation, I think the sladwall could be extended a bit or a support texture could be added, instead of altering the texture itself.

**Comment by mc776** [comment]
In this particular case it's definitely better to just replace that DOORTRAK (why did we even leave it like that in the first place???) but I'm always interested in the prospect of doing something different from and better than id.

**Comment by mc776** [comment]
At first I was wondering if it might be good to make a new threshold or trim here but no, it's definitely best left as one solid sladwall:
![Clipboard01](https://github.com/freedoom/freedoom/assets/24984517/954791c6-64d1-4b1d-8436-7d56e515c404)

**Comment by MerrittK** [comment]
Looks good.

**Comment by mc776** [comment]
So, uh, one thing kinda led to another and I'm not 100% sure if this is an improvement:
![DOOM03](https://github.com/freedoom/freedoom/assets/24984517/057d80ac-ce3a-4b44-a39a-1559d4be7f95)
![DOOM01](https://github.com/freedoom/freedoom/assets/24984517/fcd4e439-2c99-4a58-b071-8b5bbb89402a)

Basically I want to lean into the quasi-outdoors-y aesthetic of that big room, and replace those floor textures with something that looks a little less awful while you move and turn in low-res software. The blocky "A" and full-descending-middle "M" seem to be more on brand for AGM as well.

Absent any major objections I would like to include this change in the PR.

**Comment by MerrittK** [comment]
I liked the flavor of that room as it is before. It wasn't played in a vacuum, you would always be looking at a major objective to pass through. I didn't particularly notice the floor.

**Comment by selliott512** [comment]
The door track "strobe" issue is similar to what was just fixed in #1240 , except it feels like the vertical lines have a stronger justification in this case.

It may be that when a software renderer is used that, apparently, rounds off to the nearest pixel instead of interpolating, Moiré patterns happen, and that's what the user should expect.

That being said I don't have strong feelings about it either way.
