### ISSUE TITLE
patches: W108_1 is just a blank wall.

### ISSUE THREAD

**Issue by mc776** [freedoom/freedoom#1253]
so I tried loading Doom maps into Freedoom and:
![DOOM00](https://github.com/freedoom/freedoom/assets/24984517/ee0e9979-df7d-46f5-91c5-be024332bca4)

Expected: *some* kind of decoration or marker here, even if it's not necessarily a dead pain lord.

Marked as "deferred" since I'm willing to bet that somewhere someone has used SP_DUDE6 as a blank wall in some Freedoom IWAD map and it will take a while to check.

**Comment by Talon1024** [comment]
> Marked as "deferred" since I'm willing to bet that somewhere someone has used SP_DUDE6 as a blank wall in some Freedoom IWAD map and it will take a while to check.

This is what I found:

    $ grep -Eri 'SP_DUDE6' levels/
    grep: levels/e3m6.wad: binary file matches
    grep: levels/map26.wad: binary file matches
    grep: levels/e3m3.wad: binary file matches
