### ISSUE TITLE
E2M3: Out-of-bounds jump possible through sector 205

### ISSUE THREAD

**Issue by andOlga** [freedoom/freedoom#1261]
You can jump out of this window into a void.
![image](https://github.com/freedoom/freedoom/assets/462484/b2c8bcb0-54b2-4de7-bc6d-a995c5de17a6)
One of its lines (maybe the inner one, so that you can't even jump onto the window) should be set to block players.

**Comment by unithecutie** [comment]
Wouldn't be a problem in vanilla, plus with source ports where you can use a jump function you would actually have to somewhat commit yourself to jumping out of the window.

**Comment by andOlga** [comment]
> Wouldn't be a problem in vanilla, plus with source ports where you can use a jump function you would actually have to somewhat commit yourself to jumping out of the window.

Irrelevant. The policy of Freedoom has for a while been to be compatible with jumping and plenty of similar issues have been fixed in the past.
