### ISSUE TITLE
Lite/Demo version of the IWAD?

### ISSUE THREAD

**Issue by mc776** [freedoom/freedoom#1273]
DOOM1.WAD: 4.1 megabytes
freedoom1.wad: 28.7 megabytes

Seven times the size.

I'm sure there have got to be some weird devices people try to run Doom on where this difference is actually prohibitive.

I've taken a [stab](https://codeberg.org/mc776/LibTech1/commit/b4594594e9c9ca173cb5d51a77e424cd436a0046#diff-836efb6e25a091dcb4ff8e1dbb2f0be6a5cbf14c) at making a smaller bare-bones version of the IWAD, basically cutting out every level and monster and sound not found in shareware and eliminating all D2/TNT/Plutonia/Freedoom-only textures.

Files that need to be edited:
- base makefile
- textures makefile
- textures.cfg
- buildcfg

Required only because E1 endtext currently uses an Aquatex flat:
- dehacked makefile
- dehacked

Required if we're using the common-titlepic-plus-generated-caption method for the titlepic, but optionally also to replace the episode 2 and 3 menu graphics with a "not available" message:
- graphics/text makefile
- graphics/text config

I am pleased (and tbh pleasantly surprised) to report that it runs on chocolate, crispy and gz without any serious issue.

It currently sits at around 7.1 megabytes with no music or non-dummy levels - still almost twice the size of shareware Doom but a quarter of the regular size of FD.

Zipped, it is [2.8 MB](https://github.com/freedoom/freedoom/files/13929793/freedemo.wad.zip).

It takes a lot of work and editing to get right, and likely a new set of maps as well that's restricted to the much more limited texture range, so I'm wondering if there's any sort of will or stomach for this additional work (and later maintenance) for the upstream project.

Under no circumstances should any work on this in earnest be committed into main before the next stable release.

**Comment by mc776** [comment]
(Ignore the `t_fdemo.png` and the `freedemo` subfolder inside `textures` in that commit, I just forgot to add them to clean and gitignore.)

**Comment by Mr795** [comment]
also i see you have a faint version of the old titlepic in the background of the title screen, nice.

**Comment by uhbooh** [comment]
Nice idea. I took a look at the wad in slade and there's several things included that aren't in the doom shareware. Sprites and sounds for the plasma weapons are in which can't be obtained in episode 1. All of the patches for TEXTURE2 are there as well which are for the registered episodes.

**Comment by mc776** [comment]
> All of the patches for TEXTURE2 are there as well which are for the registered episodes.

After some poking around and trying to delete various lines in the makefile and inserting more `ifndef FREEDEMO`s at various points along the textures.cfg file I don't think it'd be possible to separate the two sets in FD's source in a remotely sane manner without a total reorganization of the cfg file by someone who *really* knows what they're doing.
