### ISSUE TITLE
Distribute and make available on the website all languages of the Freedoom manual

### ISSUE THREAD

**Issue by selliott512** [freedoom/freedoom#1277]
Freedoom has an originally English manual that has been translated to French and Spanish. Currently both `make install` and `make dist` only include the English manual. Also, we mention the manual on the website, but we don't have a link to it, which is odd since we have a copy in the web root.

I propose the following changes take make the manual more available:

1. The website have all three translations as well links to them. This should probably either in a prominent place, like a link from the top of `index.html`, or a new `documentation.html` page that is linked to.
2. Let's rename `freedoom-manual.pdf` to `freedoom-manual-en.pdf` so there is a consistent language suffix. And while we are at it there's no reason to have a `manual` prefix in some cases and `freedoom-manual` in others. Let's use `freedoom-manual` everywhere.
3. We could continue only including the English manual in the ZIP file produced by `make dist`, but the manually really isn't that big. They are less than 1 MB each compressed in the ZIP file, so quite reasonable by modern standards. Perhaps we should include all three languages.
4. `make install`  behaves like `make dist` currently does. Perhaps it could install all three translations.

**Comment by mc776** [comment]
I agree with all of these points.

**Comment by mc776** [comment]
> This fulfills issues #1277.

I'm going to take the liberty of closing this now.
