### ISSUE TITLE
C2M3: Imps need a rework...

### ISSUE THREAD

**Issue by Proluiz** [freedoom/freedoom#128]
![screenshot_doom_20141014_120935](https://cloud.githubusercontent.com/assets/6380147/4631285/6c2c7040-53b4-11e4-8f79-0347d98ae258.png)

the dead bodies of imps is so high and some times block the sight...

**Comment by Catoptromancy** [comment]
That is just a really high doorframe, this is bound to happen sometimes. Maybe add a monster blocking line slightly father back so imps cannot die on very top step. The imp bodies are reasonable.

**Comment by NickZ** [comment]
Fixed with Raymoo's new serpent sprites
