### ISSUE TITLE
Add verification to the apps on flathub

### ISSUE THREAD

**Issue by Mr-Bajs** [freedoom/freedoom#1295]
The apps on flathub are unverified. If the apps are verified that adds some level of security. And the growth of the verification feature on flathub also make the unverified apps less attractive.

https://flathub.org/apps/io.github.freedoom.Phase1
https://flathub.org/apps/io.github.freedoom.Phase2

It seams to be s simple process of adding verification
https://docs.flathub.org/docs/for-app-authors/verification

**Comment by mc776** [comment]
Disclosure of bias: the phrase "app store" gives me the willies.

Who runs/owns Flathub specifically? I can find no information about them.

**Comment by selliott512** [comment]
I've used Flathub. It's where I got GZDoom from, as well as a few other apps. Flatpak can be thought of as a Linux distro independent repository with sandboxing, so you can install things without having to worry about updating dependencies (and somewhat about security). Flathub is where the packages actually live.

So, Flathub is a legitimate concept, but as often the case with runnable software, we have nothing to do with this. Looking at the first two links provided:
* https://flathub.org/apps/io.github.freedoom.Phase1
* https://flathub.org/apps/io.github.freedoom.Phase2

I don't like how it claims it is `by Freedoom Project`. 

I don't mean to suggest that there is anything malicious. It could well be a result of someone trying to be helpful, but I'm not aware of any Freedoom on Flathub effort.

**Comment by mc776** [comment]
[url=This comment](https://github.com/freedoom/freedoom/issues/1305#issuecomment-1919614801)

> Freedoom has a very permissive license, so ultimate people can do what they want.

reminds me that there's little point in even requiring verification for a very niche and generally unmonetizable project. Not enough, in my view, to add yet another responsibility of maintaining an entire new account on another site.

And, frankly, the whole idea of getting everyone to centralize on this one provider to "verify" themselves (how's that Twitter blue check going?) to gain more "reach" just throws up all sorts of red flags for me.

If another maintainer is really motivated to do this they're free to re-open.

**Comment by Eonfge** [comment]
Verification would only be relevant if you want to assert direct control of the Flatpaks. If you feel comfortable distributing your project on Flathub, I can ask the main administrators to make @mc776 or @selliott512 maintainer.

If you're ok with me doing it, and you don't want to engage outside of the bug reports I might have, then that's fine too.

**Comment by Eonfge** [comment]
It's not an all-or-nothing business. If you want my assistance, I'll gladly help even if you take charge
