### ISSUE TITLE
Punching walls makes sparks

### ISSUE THREAD

**Issue by AXDOOMER** [freedoom/freedoom#130]
![sparks](https://cloud.githubusercontent.com/assets/6194072/4691619/80581d78-5727-11e4-9393-cb6b66b1cb6f.gif)

At the same time, I'd like to say that I find the bullet puffs too bright. Compare them with Doom's bullet puffs, which only have a few (or one) full bright yellow pixel(s) in the middle. FreeDoom's bullet puffs (no offense meant to their author) just looks a big pile of bright yellow pixels. A full SSG blast at a wall looks like there are lights shining on the wall (they look like small suns). They need to be redrawn.  (That's my opinion, what's yours?)

![chaingunning_a_wall](https://cloud.githubusercontent.com/assets/6194072/4691677/7df8323e-572c-11e4-8c43-4c62ec44bedc.gif)
![doom65](https://cloud.githubusercontent.com/assets/6194072/4691711/4f5ce1ca-572e-11e4-9c96-82719440d8ea.gif)

**Comment by NickZ** [comment]
resolved with sodaholic's new bullet puffs.
