### ISSUE TITLE
Brightmaps and lights for use with GZDoom

### ISSUE THREAD

**Issue by Eonfge** [freedoom/freedoom#1304]
GZDoom supports brightmaps and lights, and they ship their own Doom/heretic/etc compatible files by default. They sadly don't have a set of birghtmaps and lights that are compatible with Freedoom.

Therefore, I would propose that we add a series of optional files to Freedoom, that include these brightmaps and lights, for use with engines like GZDoom.

**Comment by unithecutie** [comment]
Pretty sure these are already integrated into GZDoom for Freedoom? @mc776 
[here](https://github.com/ZDoom/gzdoom/pulls?q=is%3Apr+freedoom+is%3Aclosed)

**Comment by mc776** [comment]
I've submitted what I can of the lights but I can't do brightmaps and am not aware of anyone working on them.

**Comment by mc776** [comment]
> files

I find that having to go out of my way to load that extra file puts a pretty huge dent in my enjoyment of a thing.

I've been told in the past that putting a GLDEFS lump into Freedoom is bad because GZDoom's GLDEFS stuff might not work with other ports. I don't know what those are though. Does anyone know any specific stuff that actually causes problems (instead of the other port just ignoring it)?

**Comment by selliott512** [comment]
As per unithecutie's comment I don't know if this has been fixed or not, but in any case, not to be dismissive, but I mostly play with GZDoom and I haven't noticed a problem. As per [this explanation of brighmaps](https://www.reddit.com/r/DoomMods/comments/j2z068/can_someone_explain_to_me_what_brightmaps_are/) the consequence of it being incorrect, and defaulting to the usual Doom / Doom 2 brightmaps would be the wrong part of minigun zombie (FD's chaingunner), being lit (and likewise for any monster that produces light)?

I have noticed that GZDoom adds a significant amount of color ambient light to certain pickups, which sometimes gives away secrets in FD. I haven't taken the time to check if they match the color of the FD pickup though. That might be an issue.

**Comment by mc776** [comment]
I don't think any up-to-date FD brightmaps exist - GZDoom's brightmaps.pk3 certainly doesn't have any.

In my opinion it's *far* too much maintenance to be worth the trouble - you're basically re-doing *every frame of every affected sprite*, with every one of those needing to be checked and updated every time the sprite changes, all for what is ultimately a very subtle effect that 90% of the time gets drowned out by the dynamic lights.

Graf's already starting to complain when I post PRs updating the lights, he might just drop FD support entirely if we start spamming the GZD git with both gldefs and brightmaps.

(And to think I'm thinking about this *right* after complaining about "so much reduplicated information everywhere" in #1305...)
