### ISSUE TITLE
Spanish needed for desktop files

### ISSUE THREAD

**Issue by mc776** [freedoom/freedoom#1307]
Manual: English, French, Spanish.

Desktop: English, French, Hebrew.
https://github.com/freedoom/freedoom/blob/v0.13.0/dist/io.github.freedoom.Phase2.desktop

(not to say we shouldn't have a Hebrew translation of the FD manual but I assume a Spanish entry on the desktop has wider reach in less time for less work)

**Comment by mc776** [comment]
Here's what I got from LibreTranslate (although I had to input "battle *these* monsters" to keep it from parsing that as a compound noun like this were a Pokémon-like):

> Batalla monstruos en cuatro episodios de 9 niveles

> Batalla monstruos en un episodio masivo de 32 niveles

> Luchar amigos y enemigos en la lucha de la muerte

**Comment by UltimateCraneo** [comment]
aight lemme do it rq

Fight friends and enemies in competitive deathmatch

Lucha contra amigos y enemigos en un deathmatch competitivo

**Comment by UltimateCraneo** [comment]
I'd also change "batalla monstruos" to "pelea contra monstruos" maybe...
