### ISSUE TITLE
textures: some id definitions are changed which may affect compatibility.

### ISSUE THREAD

**Issue by mc776** [freedoom/freedoom#1317]
Here are the FD maps I can find that currently use BROVINE2 that need to be checked once the texture is corrected:

```
E2M1
E2M3
E2M6
E2M9
E4M2
E4M8
E4M9
Map11
DM09
```
[rest of original post follows]

While doing #1316 I noticed there were two BROVINE2s: one Doom 2(?) texture with the green WALL62_2 and one custom Freedoom texture with the brown WALL62_1.

Was the FD one supposed to overwrite the D2 one? Or was this supposed to be a new texture and the "2" was a mistake?

Here's D2 Map01 (loaded as a PWAD in FD) for comparison:
![DOOM01](https://github.com/freedoom/freedoom/assets/24984517/8a213e1e-d15e-4a7a-a571-853a9f6254f5)
![DOOM00](https://github.com/freedoom/freedoom/assets/24984517/730a5d8f-490d-4324-9810-bae728bdd7a1)

And if I rename FD's BROVINE2 to BROVINE3 here's the "old" BROVINE2 revealed:
![DOOM02](https://github.com/freedoom/freedoom/assets/24984517/704396ab-0aee-476c-a7cf-5bde7318664f)

**Comment by mc776** [comment]
I've also noticed that a lot of the GRAY texture definitions depart from Doom's:

FD:
```
GRAY1       		64	128
*	W33_7       	0	0
*	W33_9       	0	64
GRAY2       		64	72
*	W33_7       	0	-8
*	W31_2       	0	56
*	DUCT1       	21	16
GRAY4       		64	128
*	W33_5       	0	0
*	W33_6       	0	64
GRAY5       		64	128
*	W33_7       	0	0
*	W33_9       	0	72
*	W33_8       	0	64
```

id:
```
GRAY1       		64	128
*	W31_1       	0	64
*	W31_1       	0	0
GRAY2       		64	72
*	W33_7       	0	-8
*	W31_1       	0	56
*	DUCT1       	20	16
GRAY4       		64	128
*	W33_5       	0	0
*	W33_5       	0	64
GRAY5       		64	128
*	W33_7       	0	72
*	W33_7       	0	0
*	W33_8       	0	64
```

Has it been decided that there's no longer any functional need to follow id for these, as long as the underlying replacement patches and the resulting textures are the same dimensions?

**Comment by Xindage** [comment]
Korp create new gray patchs that don't exist in both doom and doom2, doom uses the same blocks on the grays, korp made it uses 2 slight different blocks so it's less repetitive, now the brovine needs to ne checked indeed.

**Comment by mc776** [comment]
The situation where I think the GRAY stuff would break would be where some mod replaces a couple of the W3whatevers with the intention that a bunch of textures would all be changed in a similar way, and it works fine in Doom, but in Freedoom you'll see those textures with a mix of the new patch and FD's regular patch.

I don't have a real-world example for this - frankly if I did I wouldn't have posted an issue but a PR.

**Comment by mc776** [comment]
> Try to see if doom and doom2 differs, if not then fixing is ideal.

It does not. The biggest most tedious thing is just fixing all the affected FD maps - and we're not in a rush for a new release just yet...

**Comment by mc776** [comment]
So I tried restoring the id definitions and running around in E1M5.

Pretty much everything looks fine except for GRAYTALL:

Current: perfectly tiling.
![sm_DOOM0001 png](https://github.com/freedoom/freedoom/assets/24984517/d1dec297-4183-4d1b-bccb-dbdc94e9f683)

textures-restored: the FD equivalent of a green streak found in id also has bullet holes on top of it, which makes it look really repetitive here:
![sm_DOOM0002 png](https://github.com/freedoom/freedoom/assets/24984517/8e47d210-33d2-4957-926c-c3c9a1932846)

id: absolutely gawdawful. No one in their right mind would have used that texture here if this map had been made for id textures.
![sm_DOOM0000 png](https://github.com/freedoom/freedoom/assets/24984517/2a670c7c-9ac0-49b4-8092-84a94e5758ee)

As far as badly over-repetitive textures go, this can easily be fixed on the mapper end.

**Comment by Xindage** [comment]
You don't need to change the gray or the definitions of it, most of times if a map pack use custom textures in vanilla it replace the whole texture1.lmp and it'll load the default one of his choice, not applying any of our patchs, so at the end there's no real issue.
So far we never had an wad that replaces just patches, they replace the texture file itself.

**Comment by mc776** [comment]
I used to see stuff with only custom patches without custom textures files *all the time* back in the 90s, did something major change? (I know SLADE's WYSIWYG texture editor stopped crashing on me as of the latest release but that's it)

**Comment by mc776** [comment]
> I don't have a real-world example for this

To clarify, all that we need to break the current setup is a WAD that replaces W31_1 and which uses GRAY1 with the intention of it showing the replacement W31_1. There's got to be some, I just haven't got the time or energy right now to do a deep dig through hundreds of WADs to find one.

**Comment by Xindage** [comment]
Take for example 2002ado an ultimate doom map pack, it has custon textures, if you load it you'll see that all gray definitions are the defaults of doom1 regardless what freedoom does woth its textures.
Other example on doom2 can be cyberdreams, this wad just improve few doom2 patches, but in the end it restore the default ID doom2 textures because he had to use a new textures.lmp file.
So it's certain if a wad has custon textures he have its own textures lmp.
Wanna go beyond to see the proof, load city of doom mod it has 11 maps and its vanilla format, so warp beyond these 11 maps and see what happen when you visit some freedoom levels, you'll crash with missing textures, Why that? Simple the texture lmp was completely replaced since it added graphics so it's using the default doom2 that he loaded inside the wad in order to add his data. It's how it works.

**Comment by mc776** [comment]
Big 5+ mapsets, yes. Single maps from old /idgames archives (some of which might even predate deutex), generally not.

The difference actually predates Korp's new stuff - the deleted lines #948 already show GRAY1 using W33_7 instead of W31_1. (In id and current FD W33_7 has no dark borders on the left and right edges; not sure if there was a difference in FD before.) It was W31_1 in the earliest history preserved by git https://github.com/freedoom/freedoom/commit/36658bee0ea408bf54207c2cdca33628446fb81a but Teppic changed it here:

https://github.com/freedoom/freedoom/commit/1be2eb82d7292752e78b8d6d88c2eff900ceb546
https://github.com/freedoom/freedoom/commit/d05542456ebc66737b2bbe91decb37f4ecf013af

I'm not clear what the reasoning behind this was. Was it an intentional attempt to differentiate from id, or just a mistake while reconstructing the file?

**Comment by mc776** [comment]
I can't imagine any way to proactively fix the underlying issue without copying id's texture definitions. It seems like a functionally necessary fair use in such a case, but I'll defer to Jon who's been thinking about this shit way longer than I have.

If:
1. someone really does do something with W31_1 in a WAD;
2. they play it in FD and the graphic is broken;
3. they post a bug report and we check the wad;
4. that's how we (whoever "we" are by then) orgnically work out what's wrong and fix it then,
I think it would be a sufficiently clean room and/or fairly direct demonstration of the fair use.

So until then I'm going to close this since I think we all agree about the BROVINE2/3. (that said, is BROVINE in any of the id IWADs or does that belong with the new FD textures too?)
