### ISSUE TITLE
Create a file / sheet that information about each of the 100 levels

### ISSUE THREAD

**Issue by selliott512** [freedoom/freedoom#1325]
Recent conversations in the #help channel and other places have suggested that it would be nice if we had information about each of the 100 levels in a single place.

Currently it's surprisingly difficult to learn about the history of a given level via `git log`. Levels are swapped (as in `git mv`), and they are also renamed (as in `HUSTR` DeHacked strings), so there is no easy identifier to follow their history.

What if we had a sheet (Google Doc?) or text file that had 100 rows with a few helpful columns, like `Name`, `Author`, `Created Date`, `Status`. etc.?

I can take an official automated pass at in, an empty shell that just has the 100 files and empty cells for everything else (or maybe I extract the names from DeHacked).

**Comment by mc776** [comment]
Please no Google doc.

**Comment by unithecutie** [comment]
Might be something I could join in on, I'm willing to do the painstaking effort of organizing this - like what I did with `CREDITS-MUSIC`.

**Comment by selliott512** [comment]
@unithecutie that sounds great. As a starting point I've attached `levels.csv`. It was created in Linux with:
```
echo 'Name,Author,Created Date,Status' > /tmp/levels.csv
for level in dm??.wad e?m?.wad map??.wad; do name=${level%.wad}; name=${name^^}; echo "$name,,,"; done  >> /tmp/levels.csv 
```
[levels.csv](https://github.com/freedoom/freedoom/files/14158498/levels.csv)

You can import it into a spreadsheet, or however you want to process it. A spreadsheet is a good intermediate form because it makes it helpful to add columns and such.

I'm not actually sure what the final form should be. It could be an AsciiDoc, but I think their table syntax is odd. Maybe a table in a text file with spaces so the columns align? I can help a script that converts from CSV to that.

Anyway, things are pretty open ended, including the column names.

One other possibility is that we have one text file per level, but at 100 new files that may not be the most attractive solution.

**Comment by unithecutie** [comment]
I think it should be sorted by year instead of exact date? It's a bit of a gray area for pre-0.6.4 because of Metabolist. :P

**Comment by unithecutie** [comment]
@selliott512 Here's a **very** rudimentary attempt at formatting it with only plaintext, not sure if we should keep that though...
I've done map credits on DoomWiki before too.
[CREDITS-MAPS.txt](https://github.com/freedoom/freedoom/files/14158616/CREDITS-MAPS.txt)

GitHub changing the "date modified" on it is very infuriating, so I can't add the year just yet - that would take me a long while.

**Comment by unithecutie** [comment]
@mc776 Thoughts?

**Comment by selliott512** [comment]
That's pretty neat. And you did it quickly. 

For the  file name I'm partial to `CREDITS-LEVELS` since for Freedoom we the level WADs in the `levels` directory, but what do you all think?

**Comment by unithecutie** [comment]
CREDITS-LEVELS would be better to match, yeah.
