### ISSUE TITLE
patches: consider increasing contrast of RW18_1 and 2.

### ISSUE THREAD

**Issue by mc776** [freedoom/freedoom#1334]
Posting this as an issue instead of a PR because it may well be just a matter of personal taste.

This has bothered me for months now. I've  tried to get used to it but it really does feel like the new patch with its *very* light shadows is out of place in FD:
![lowcontrast](https://github.com/freedoom/freedoom/assets/24984517/7c7cc7e2-3093-4396-85b9-36261d206c0e)
I know the cracks are intended to be shallow but my brain just Will Not Work With It and instead of a difference in depth it just senses an artistic style clash.

Here's an attempt to increase contrast and gamma while reducing brightness so the overall shade would sorta roughly match:
![highcontrast](https://github.com/freedoom/freedoom/assets/24984517/9680cc05-cbe9-4529-bf6c-322754dfecf5)

If folks agree, here are the altered images:
![rw18_1](https://github.com/freedoom/freedoom/assets/24984517/d5b98b55-2f68-4b76-aeda-faf8ace26254) ![rw18_2](https://github.com/freedoom/freedoom/assets/24984517/4b30cbac-2787-4624-a016-9d3414f0cf79)

**Comment by unithecutie** [comment]
Looks a lot nicer, having the details stick out more.

**Comment by KorpKat** [comment]
Ah, i can see now, yep i approve.
