### ISSUE TITLE
MAP19 jump compatibility issues

### ISSUE THREAD

**Issue by Talon1024** [freedoom/freedoom#1337]
At the start of MAP19, some mods such as Trailblazer and DN3Doom make it possible to jump onto this ledge to grab the ectoplasmic surge (Soulsphere):

![Screenshot_Doom_20240213_114727](https://github.com/freedoom/freedoom/assets/6550500/6b958512-f64c-46f4-b63a-9b8efd33ba6e)

It is also possible to jump up there, even without mods, if you circle around to the other side. And once you're up there, you get teleported straight to the second last room when you try to jump off the ledge.

I recommend making both sides impassable, and add the A-RAIL midtexture.

**Comment by mc776** [comment]
I don't remember how you get up there, but just off the top of my head I'd rather see it surrounded by bars that are lowered just before you walk into the teleporter that takes you up there - that way you still have options about where to go once you've reached the secret.

**Comment by mc776** [comment]
There is no space to put that kind of teleport pad, no wonder the teleportation was hidden here.

One solution: add a new line for the teleporter which basically activates immediately after you pick up the sphere:
![Clipboard01](https://github.com/freedoom/freedoom/assets/24984517/a1f54cc8-7387-4249-a176-044166c012f7)

[map19.zip](https://github.com/freedoom/freedoom/files/14271449/map19.zip)
