### ISSUE TITLE
"mobile device is not compatible" fix pls?

### ISSUE THREAD

**Issue by Doodledsandwich** [freedoom/freedoom#1364]
Im trying to install freedoom on my phone but it says it is not compatible with my device.

**Comment by Xindage** [comment]
I'll copy it directly from discord server #freedoom-the-app.

The Android app store contains an app named "Freedoom" that lets you play an old version of the Freedoom WADs. Despite the name, we have no connection with the app or its author. It is also years out of date and not representative of the current version of the project. If you have questions about or problems with this app, please contact the author, do not ask about it on this server.

**Comment by Anonysussy** [comment]
If you want to issue about it, i'd suggest you issue it here https://github.com/mkrupczak3/Freedoom-for-Android
