### ISSUE TITLE
MAP01: Switch leading to secret area can be activated through a wall

### ISSUE THREAD

**Issue by pooka109** [freedoom/freedoom#137]
In MAP01, in Freedoom 0.9, the ledge with the mega-armor (heavy armor vest) on it is marked as one of the two secret areas.  This ledge is lowered to an accessible height by hitting a switch hidden behind a wall.  However, if you face where that switch is (while it is still covered by the wall) and press the space bar, the switch will be activated regardless.

**Comment by chungy** [comment]
The move to vanilla (for Phase 1+2) has been discussed in IRC a few times, as a possible goal for 1.0. It is still not a requirement at this moment.

Anyhow, this bug was fixed in 11672b2 :)
