### ISSUE TITLE
E3M1 crashes on autobuilds

### ISSUE THREAD

**Issue by Anonysussy** [freedoom/freedoom#1386]
Initially I thought this was something from the build issue, but I'd recall there's one change made to E3M1 that could probably causes the problem, it only crashed on Choco while on other ports it's mostly fine. It was fine on 0.13.0.

**Comment by Anonysussy** [comment]
![Screenshot_20240715_071120_Device care](https://github.com/user-attachments/assets/33239293-1577-4265-9c3d-979f3b7ad31c)
Just tested the current E3M1 on 0.13.0 and it crashes on Choco.

**Comment by Xindage** [comment]
CRL prompted me to the error that chocolate are having.

ZDBSP are not supported.

**Comment by Anonysussy** [comment]
> CRL prompted me to the error that chocolate are having.
> 
> ZDBSP are not supported.

It could be a case of beginner mistake, they would probably just throw any node builder around as long as they work on their source port of choice since it wasn't really specified on what node builder should be used for the maps and how compatibility side of things worked (at least I did once).

**Comment by Xindage** [comment]
"It could be a case of beginner mistake" not really TBH, both DB, DB2, UDB uses a node builder compatible with chocolate doom, the only that made that happen could be choosing a different node builder in doom builder configuration or maybe setting the wrong node builder at slade as slade requires you to choose the node builder of your preference
