### ISSUE TITLE
E2M2: can't reach sector 305

### ISSUE THREAD

**Issue by watchmakerful** [freedoom/freedoom#140]
I can't find any ways to sector 305 (even with Doom Builder). But it's marked secret. WTF?
PS. Teleporters may NEVER be marked secret, remember!

**Comment by Proluiz** [comment]
this may solve it "for now", i marked the sector BEFORE of the teleport has a secret and the teleport sector is no more secret.

https://www.sendspace.com/file/a3xkc4

**Comment by watchmakerful** [comment]
>> i marked the sector BEFORE of the teleport has a secret and the teleport sector is no more secret.
This secret sector (304) has ZERO HEIGHT, no tags and no actions to "open" it. 
![55](https://cloud.githubusercontent.com/assets/10285128/5607686/7e0e9848-946d-11e4-8b60-9c5008346ac0.png)

**Comment by Proluiz** [comment]
what the f**k is the poblem of the map so i need more details? is that a true secret anyway or is a missing stuff of the game (like unfinished thing) it leads to where please detaail me.

**Comment by watchmakerful** [comment]
How to "open" this sector? I see no links to this sector, it even does not have a tag.

**Comment by Proluiz** [comment]
hmmm i noticed it now i remnber when i played this map i dont found that secret anywy where this teleport leads?

**Comment by watchmakerful** [comment]
You will never find it, it is always 0 height. Floor 224, ceiling 224, tag 0. How will you open it? :grin:

**Comment by Proluiz** [comment]
i see but TO WHERE this teleport leads (i mean where is the destination of it?)

**Comment by watchmakerful** [comment]
Nowhere, it must lead to a sector with tag 21, but there are NO sectore with this tag.

**Comment by Proluiz** [comment]
maybe this is a sort of unfinished bonus maybe removing it all solve the poblem so if you are ok. maybe today i'll ply the map and check if i can do a true secret for it or simple vanishes it.

**Comment by NickZ** [comment]
This got fixed by my submission #172, too. I added a door sector and marked the sector adjacent to the teleporter as secret. This can be closed.
