### ISSUE TITLE
Monster sprite frames that are not lit as they should be

### ISSUE THREAD

**Issue by fragglet** [freedoom/freedoom#141]
Opening this bug so that we have some discussion about this issue.

The POSSF\* sprites are shown when zombie troopers fire their guns, and these are supposed to be full-bright frames, but Doom's frame table doesn't have this frame set as full-bright. This looks bad with Freedoom's zombie sprites where there is an obvious flash from the gun included as part of the sprite. Here's a screenshot:

https://i.imgur.com/wz4xTeA.png

The Cyberdemon firing frames also suffer from the same problem:

https://i.imgur.com/70rRMxj.png

There's a fairly trivial fix for this: a simple dehacked patch can be used to tweak the frames so that they're shown at full brightness. I have such a patch here that I made: https://soulsphere.org/random/litefix.deh

I'd quite like to add this to Freedoom's DEHACKED lump but there's a problem: the patch changes the game behavior. While it isn't a change that will ever cause any desync, it might cause problems if there are TCs with complicated dehacked patches that assume that frame doesn't have full bright set. I don't know of any such TCs but it's theoretically possible.

For my part, I think we should just go ahead and add the patch; if we discover it causes any problems we can roll back the change at a later date. But I want to hear what other people have to say first.

**Comment by fragglet** [comment]
Also, when I pointed this patch out to Revenant100 in the context of the Doom 2 Minor Sprite Fixing Project, he mentioned a couple of other sprites that have incorrect full bright flags. I don't know yet if these affect Freedoom though:

http://www.doomworld.com/vb/post/1328520

**Comment by Blastfrog** [comment]
That it's theoretically possible to break some TC is enough reason to avoid adding this into the main Freedoom dehacked patch, even if no such TC exists yet or ever will. Text is as far as the dehacked patch should ever go.

**Comment by Voros2** [comment]
Big bump, but adding a DeHacked patch that modifies ingame behaviour is bound to cause desync in demos and potentially break other DeHacked mods. The patch should a standalone mod/WAD, giving the user freedom to do whatever they want with it.

**Comment by chungy** [comment]
This seems to be something you already did in 98f9aaee630762dc933325b3211a5cd8512b9f10 -- closing :)
