### ISSUE TITLE
Candles are drawn inside the floor

### ISSUE THREAD

**Issue by AXDOOMER** [freedoom/freedoom#142]
Unlike the original Doom, candles in FreeDoom are drawn inside the floor. This may be the result of auto aligning of sprites, which on some editors, put the sprites a few pixels inside the floor. In the original Doom, candles are drawn over the floor.

**Comment by jewellds** [comment]
I've had a go at fixing the offsets with pull request #144. It's still slightly below the floor line, because if you place it too high it looks like it's floating, but now it's centred and a bit higher than it was.
