### ISSUE TITLE
MAP29: player can be trapped in secret with chaingunners

### ISSUE THREAD

**Issue by Alexander230** [freedoom/freedoom#1423]
If player presses door open switch before the doors close, there is no way to open them back. It can be fixed easily if you make the switch pressable multiple times.

**Comment by mc776** [comment]
I just gave this a try in chocolate-doom and:

- (probably skill issue) I can't reach that switch before the doors close without cheating.
- using the switch does nothing while the doors are open.
- the switch does appear to be repeatable.

What version of Freedoom and what source port are you using?

**Comment by mc776** [comment]
Opening up the map in SLADE and I see that switch is in fact marked SR... I think this has already been fixed in https://github.com/freedoom/freedoom/commit/0b1456fcac7b7545d2bc6c6250a26cfa5e23ed21

**Comment by Alexander230** [comment]
I played the released version (0.13.0) in GZDoom and encountered it accidentally. The doors didn't close immediately, so I killed chaingunners first, pressed the switch, then the doors closed, and I was trapped. Yes, looks like it's already fixed in dev version :-)
