### ISSUE TITLE
Sprites of hanging corpses are not centered correctly

### ISSUE THREAD

**Issue by AXDOOMER** [freedoom/freedoom#143]
Sprites of hanging corpses are not centered correctly. This causes the sprites to appear to be moving around on the ceiling when the player circle-strafes around them. 

![hang](https://cloud.githubusercontent.com/assets/6194072/6364736/ef16f7dc-bc78-11e4-82d8-71cf8f4f525d.png)

**Comment by Proluiz** [comment]
same of #135 .
