### ISSUE TITLE
CONS1_x flats suck.

### ISSUE THREAD

**Issue by Blastfrog** [freedoom/freedoom#146]
Please, please replace them already. My most recent iteration should be perfectly suitable: http://i.imgur.com/EP7v6U9.png

The metal background is taken straight from a Freedoom wall patch. The screen is taken from Freedoom's original console flat. The border with the red dots is a heavily modified version of the console flat from TSAT, Project Dark Fox has given permission for it to be used in Freedoom, feel free to contact him for confirmation on that. The yellow buttons and keypad next to the screen are my own work.

I did deliberately follow the layout of id's original, but for good reason; flat alignment. One of Freedoom's stated goals is compatibility with PWADs, and maps could very well use the computer flat with the expectation that certain features are where id left them (maybe there's a small sector that uses just the keypad, etc).

**Comment by chungy** [comment]
fixed in 8dbebbd
