### ISSUE TITLE
DSPUNCH may be copyrighted material

### ISSUE THREAD

**Issue by leilei-** [freedoom/freedoom#151]
Last night I tried Freedoom for the first time in years, and then I punched a barrel and heard something very offensive.

This sound that has been claimed to have been self-recorded with no copyright issues derive from SoundIdeas materials.   While I don't have the set onhand to specify disc and track, I can identify the sound used in other, older copyrighted productions. Like for example you can hear the sound in Batman: Arkham Asylum, most notably in encounters with titans, such as demonstrated in this video:
https://www.youtube.com/watch?v=1qrh3xrBR2U#t=98

If you listen closely you can even hear the sample that was used for Doom's own DSPUNCH, which also derived from SoundIdeas.

I don't know if Per is around to identify the particular SoundIdeas disc/track involved.  He owns Series 6000 IIRC and I believe this sound (or mixture of two sounds) came from that set.

**Comment by AXDOOMER** [comment]
I heard the sound at 1:42, 1:48 and at 1:57.

**Comment by fragglet** [comment]
It's difficult to judge because the punch sound is very much just a typical-sounding "punch" sound. It's not surprising that games and sound libraries would use similar sounds.

For reference the current dspunch was added four years ago in 7507864c7d5d10c and Sodaholic gave some pretty strong assurances that these were entirely original.

**Comment by jewellds** [comment]
Okay, I've given this a bit of an investigation. It was hard to hear because of interference from other sounds in the game footage, so I looked for another source for the Arkham Asylum punch sounds and found this video:
https://www.youtube.com/watch?v=gGMQtuEHXvM

I believe the punch we're hearing is the second punch, slowed down.

http://orig03.deviantart.net/a127/f/2015/116/f/7/dspunch_vs_arkham_by_jewellds-d8r6jzz.ogg
The first sound is Freedoom's dspunch, the second is recorded from the gameplay footage, and the third is from the sound effects video, slowed down. They don't sound like a match to me.

**Comment by leilei-** [comment]
Batman's punch != Titan's punch.  It's very true Batman's punch sounds lower and different, i'm referring to when the titan (big guys) fail their arms hitting someone.  The familiar punch sample will show up, pitch indifferent, and mixed in with some meat sound effect to give it more muscular weight..

As for his assurance on being original, I have doubts since the Evil Unleashed hijacking incident. I wouldn't trust his word, personally.

**Comment by AXDOOMER** [comment]
@leilei- Can you save the video from Youtube to a .mp3 file then extract the sound with Audacity? It will be easier for everyone to compare the exact sound you are talking about.

**Comment by leilei-** [comment]
http://www.sound-effects-library.com/player.asp?id=HITHUMANSME02_47.2&desc=It%27s+A+Hit%3A+Thudding+Body+Or+Face+Punch+With+Slap+%A9+Sound+Ideas

Damning enough?  Its low quality though, because it's a preview for a marketplace where this sound can be purchased (at high quality) for £1.44.

**Comment by jewellds** [comment]
Ohh.... yeah that's pretty damning evidence.

The waveforms are a pretty close match. DSPUNCH at the top, Sound Ideas at the bottom.
http://img06.deviantart.net/7b60/i/2015/116/5/c/dspunch_vs_soundideas_waveforms_by_jewellds-d8r6vv6.png

**Comment by AXDOOMER** [comment]
^ From the waveforms, it looks like two different sounds.

**Comment by leilei-** [comment]
Because the sample from the site is a low-quality preview as a 22khz MP3, and the DSPUNCH sound is the same but with some compression applied from a high quality source.  The lengths and fades are identical.

**Comment by AXDOOMER** [comment]
![dspunch_vs_soundideas_waveforms_by_jewellds-d8r6vv6](https://cloud.githubusercontent.com/assets/6194072/7339945/7bd801d4-ec4e-11e4-998c-86284973e8e3.png)
Can MP3 compression change the waveform so much? Maybe he made some change to make the waveform unrecognizable.

**Comment by AXDOOMER** [comment]
I've uploaded both of them, they plan one after the other.
http://www.mediafire.com/listen/x9fp3qg1x7xhyhu/2punch.ogg

**Comment by leilei-** [comment]
Your ogg file seems to have introduced more artifacts to the sound I linked.

**Comment by AXDOOMER** [comment]
My  320Kbps Ogg didn't introduce more artifacts. Both sounds are different. Audio compression doesn't change the waveforms that much. 
![screenshot-7](https://cloud.githubusercontent.com/assets/6194072/7340057/83f3dfba-ec52-11e4-8cd8-2dffe062e415.png)

Low quality 64Kbps Ogg:
![screenshot-7](https://cloud.githubusercontent.com/assets/6194072/7340131/33272568-ec54-11e4-9dc5-c74682a409c9.png)

Low quality 64Kbps Mp3:
![screenshot-7](https://cloud.githubusercontent.com/assets/6194072/7340156/ee9ecbe8-ec54-11e4-8bb9-d8fcbc59fa5f.png)

**Comment by leilei-** [comment]
I've done a lowpass 500hz cutoff comparison and noticed there's even two peaks that line up at the same spot (check the "HMM").  I also inverted DSSOUND.beforehand (since inversion was apparently done)

![lowpass](http://leileilol.mancubus.net/crap/dspunch.png)

**Comment by AXDOOMER** [comment]
Even if Sodaholic inverted the sound, he had to do more than that to make the waveform different. I've sent him an email to ask how he does "punch sounds", saying that I'd like to make my own.
BTW, what font are you using in that picture? I like it.

**Comment by fragglet** [comment]
Rather than spend all this time speculating and trying to analyze sound waveforms, can we please just ask Sodaholic to give his side of the story? Thanks.

**Comment by AXDOOMER** [comment]
^ That's why I've sent him an email (and I've also PM him).

**Comment by fragglet** [comment]
Great, thanks. I'm just concerned that throwing around accusations like this isn't necessarily conducive to a healthy project. I'd like to hear Sodaholic's side of this before any more accusations or amateur detective work is thrown around, please. Thanks.

**Comment by AXDOOMER** [comment]
Sodaholic Says: 
Hey there.

It's been a few years so I can't remember the exact physical materials or audio filters that I used, but I basically recorded whacking various loose but solid things over a wooden beam and heavily edited and mixed the results.

One of the materials I do remember using were the closest thing to reed I could find in the area, some wheat straw. Reason for using this is that I heard that whacked reeds were used traditionally for punching sounds, kinda like coconut shells bumbling around to simulate the sound of a horse running.

There's lots of creative things that people in foley studios have come up with, I suggest researching what's been done in the past if you want some cool ideas for how to get a certain type of sound.

Hope this helps,
-Sodaholic

**Comment by fragglet** [comment]
I for one am satisfied with his explanation and I don't find any of the amateur detective work that's been posted on this bug to prove any kind of foul play.

It looks like they're different sounds, albeit ones that sound similar - possibly because they were recorded using the same kind of techniques as the original (the "whacked reeds" described).

Note that waveform pictures like the ones that have been posted do not really prove anything unless they are *exactly* the same. The waveform is ultimately just a graphical representation of the sound, so if they look "similar" it just means that they sound similar, which we already know - it shouldn't be surprising that two similar-sounding punch sounds have similar-looking waveforms.

**Comment by leilei-** [comment]
Why don't you verify the sound with Per or someone else who owns some SoundIdeas sets then? I'm still not buying his excuses.

Waveform comparison wasn't my idea (and not a smart one when you're comparing with an intentionally crippled web sample), I tried to make the best of that with a lowpass filter.

What about hearing the Doom DSPUNCH in the Freedoom DSPUNCH? That seems mixed in at the beginning.

**Comment by fragglet** [comment]
> I'm still not buying his explanation. It just shows he's adamant about being deceptive with his contaminations and is a potential hazard to any Free Software media project. 

Put bluntly, it's pretty rude for you to be storming in here and making accusations of deceptiveness against other contributors to the project, especially someone like Sodaholic who has a history of positive contributions to Freedoom. If you're going to do something like that, I fully expect to see some conclusive, irrefutable evidence to back up your claims. All you have provided is, "these sound effects sound kinda similar". That's not good enough, for the reasons I've explained.

I don't know what your personal background and beef is with Sodaholic and I don't particularly care. Contributors to Freedoom deserve to be treated with respect, not subjected to witch-hunts and baseless accusations. If you have a point to make, I suggest you do it civilly.

**Comment by fragglet** [comment]
Closing bug, as until evidence is provided to the contrary, I think we're done here.

**Comment by sneakernets** [comment]
Sorry to bring this back up, but I think leilei is in the right on this one - even if the post was abrasive. Taking samples through a Fourier transform right now.
