### ISSUE TITLE
A problem with making speedruns in PrBoom+ (Freedoom 0.9)

### ISSUE THREAD

**Issue by Dimon12321** [freedoom/freedoom#153]
There is a problem which is impossible to predict. Sometimes, when you reach a place where you must turn the switch to go further, but it doesn't work (breaks down) and your speedrun stayes unfinished. As I found out, this problem is old for this project. Here is the proof:

This is a movie .lmp file of my speedrun. When I reached the room on E1M2 (Phase 1), which requires the red keycard, the switch didn't work (but if you start the game again without recording .lmp - everything works just fine). Why it broke? .lmp file can be downloaded here: https://yadi.sk/d/HHDrPMAUgyfMb

Unfortunately, I can't dump the video because Fraps records 4 frame per second and video dumping feature doesn't work in PrBoom. To playback the demo, download PrBoom+ 2.5.1.3, put Doom.wad, freedoom1.wad and d23.lmp at the folder with PrBoom+, create a shortcut for prboom-plus or glboom-plus and add the following at the Target line: "-iwad freedoom1.wad -playdemo d23" and then start the shortcut.

Also, I have a video of Freedoom 0.8 Beta 1 where the stairs, which block the switch, didn't go down after I killed all monster in the area. I'm sure this is also connected with this problem.
https://www.youtube.com/watch?v=_y3KVxZmPIM

Do you know the cause of these anomalies? Is PrBoom+ a bad choice for speedrunning Freedoom? Can you fix that problem? Thank you and good luck in development!
P.S: sorry for my English. Also, I expect you have a good attitude to speedrunning.

**Comment by chungy** [comment]
You're trying to play Freedoom with vanilla compatibility enabled (you must have set -complevel 3):
`G_DoPlayDemo: playing demo with Ultimate Doom/Doom95 compatibility`

This won't work. Phase 1 and 2 are designed for Boom compatibility; you have told PrBoom to disable features that aren't available in vanilla Doom. Everything is working as intended, but your expectations are a bit off. The minimum -complevel supported for Freedoom Phase 1+2 is 9 (Boom v2.02).

**Comment by Dimon12321** [comment]
Thank you, chungy! The problem is solved and I'm closing the issue.
