### ISSUE TITLE
FreeDM DEMO1 desyncs

### ISSUE THREAD

**Issue by fragglet** [freedoom/freedoom#154]
82c9091dab26d0e76823f84e57e4bba84adaab47 broke sync for this demo. We need to record a new demo to replace it.

**Comment by Proluiz** [comment]
Also DEMO4 is desync too.

**Comment by NickZ** [comment]
We recorded some new demos, they'll be in for 0.10

**Comment by NickZ** [comment]
Replaced all desyncing demos with new ones, all the demos are working now.
