### ISSUE TITLE
Update SMITA0 sprite to use Sergeant_Mark_IV's version

### ISSUE THREAD

**Issue by samboy** [freedoom/freedoom#155]
Sergeant_Mark_IV (yes, the very same Sergeant_Mark_IV who made brutal Doom) has made a really nice update to to SMITA0 (tree with foliage) sprite:

http://www.doomworld.com/vb/freedoom/72566-my-smita0-sprite/

I have converted this sprite and it looks really nice in-game.

Freedoom should replace Kurt's SMITA0 with this updated sprite.

**Comment by chungy** [comment]
Closed as of c891b1e88a7ed73a1bbe16aa69dab077075aa4ee
