### ISSUE TITLE
Replace or edit music in MAP01, MAP16, MAP27

### ISSUE THREAD

**Issue by samboy** [freedoom/freedoom#156]
Having recently played a 32-map random map megawad, I noticed that I found the music unpleasant to listen to in four of the maps:

* MAP08 (d_ddtblu) The flute-like sounds are distracting (Picklehammer has made some really great music, such as the MAP30 theme)
* MAP13 (d_doom2) The high-pitched sustain guitar sounds are distracting (Jute has made some really good music, such as the MAP28 and MAP09 themes)
* MAP21 (d_count2) This theme plays the same chord over and over again for too long, which quickly gets annoying (Jute, again, has contributed good music)
* MAP27 (d_romer2) This theme plays some annoying high-pitched notes for a couple of bars. While not as annoying as other music here, it's still unpleasant for me to listen to (Yes, again, Jute did contribute a lot of music, and most of it is quite good)

In these four cases, I think Freedoom is better off just using the music from another Freedoom level; I replaced the MAP13 theme with the MAP09 theme which works a lot better.

Somewhat related discussion: http://www.doomworld.com/vb/post/1370527

**Comment by samboy** [comment]
As a point of comparison: The original DOOM2 uses 18 different themes for the 32 maps. Freedoom currently uses 31; we can reduce that number to 27 and still have 150% of the music the original had.

**Comment by fragglet** [comment]
Sounds good to me. If we have bad tracks we should just remove them.

**Comment by samboy** [comment]
As an aside, the smallest difference between levels in ID's Doom2 using the same music is six (for example MAP11 and MAP17 use the same these, as does MAP08 and MAP14)

**Comment by samboy** [comment]
Here are the changes I made (source on left copied to destination on right)

* MAP03 (d_countd) -> MAP13 (d_doom2)
* MAP09 (d_in_cit) -> MAP21 (d_count2)
* MAP17 (d_stlks3) -> MAP27 (d_romer2)
* MAP28 (d_tense) -> MAP08 (d_ddtblu)

As a note, MAP07 and MAP29 currently use the same theme (picklehammer/d_shawn.mus). Also: The MAP08 theme has a distinct style which may be needed for a particular type of "Gothic" map. 

The advantage of using copied music lumps is that this allows Fragglet's wadptr tool to more effectively compress them. 

My "Freedoom with random maps" fork is about to be uploaded here:

http://samiam.org/obhack/ObHack-FreeDoom-0.7.3.zip

GPG sig (signed with the MaraDNS GPG key):

http://samiam.org/obhack/ObHack-FreeDoom-0.7.3.zip.asc

**Comment by chungy** [comment]
> As a point of comparison: The original DOOM2 uses 18 different themes for the 32 maps. Freedoom currently uses 31; we can reduce that number to 27 and still have 150% of the music the original had.

I don't think the comparison is too useful in honesty. The game probably would work much better if every level had unique music (though there's no hard goal for that). Some duplication is okay, especially when we lack enough good music for that (and consider that Freedoom between its three games has 100 levels!), but keep in mind that Doom 2's duplication was inspired more by keeping the file size of the IWAD down; fewer installation floppies, and doom2.wad taking up less precious bytes on hard disks in an age that 100MB disks were common. Freedoom isn't going to be approaching file sizes to cause real concerns in the 21st century :)

I've just gotten a new music submission from Mogul, I think I'll replace one of these tracks, and look into how the other replacements work out :D

**Comment by chungy** [comment]
Ok. In, 4d61471 I've replaced MAP08/C2M7 with the new submission.

**Comment by samboy** [comment]
A few thoughts:

* I believe the reason Bobby Prince did not make more soundtracks is that he just didn't have the inspiration and/or wasn't paid enough to make more soundtracks. I can not find any interviews or discussions from the DOOM(2) development team about the reuse of soundtracks, but there is a note from Prince that “Many times in those wee hours, I would come to a point where I couldn't make positive progress toward completing a song or a sound effect” [1]
* Music sound tracks are each about 10 to 20 kilobytes in size in the .WAD files (easily verified by looking at the MIDIs/MUS files in SLADE). Going from 18 to 32 soundtracks would have, at most, added about 300k to the uncompressed DOOM2 IWAD. 
* Using .zip compression, the version of my FreeDoom IWAD with the duplicated soundtracks is actually a little bigger (6,543,218 bytes with duplicated soundtracks, 6,537,926 without).  The 32kb window that 1990s zip “DEFLATE” compression uses isn't large enough to figure out that “oh, this is a duplicate of a MIDI I have already seen, so here’s a pointer to the older MIDI” [2]
* If the goal of the FreeDoom project is to not have duplicated soundtracks, we should replace the MAP29 soundtrack, which is a duplicate of the MAP07 soundtrack, with something else.
* For us to have every single soundtrack be unique (e.g. The Deathmatch phase2 soundtracks are not the same as the non-Deathmatch soundtracks), we need 99 different soundtracks. Thankfully, the FreeDoom project currently has 114 different soundtracks (not 115, because picklehammer/introa.mid is the same file as picklehammer/intro.mid) , as well as the "dummy.mus" file.
* There has been a discussion about whether we should have c4m1, c4m2, c4m3, etc. themes [3], since the original Ultimate Doom .exe just used themes for other maps. Even though not all source ports support it, it would be feasible to do this, since we have enough unique music files to pull it off. 

Since the FreeDoom maintainers seem to prefer each level to have its own theme, I am closing this ticket. Duplicating the better themes works for me, but may not work for everyone.

[1] http://www.doomworld.com/classicdoom/info/music.php

[2] See https://en.wikipedia.org/wiki/DEFLATE#Bit_reduction for an overview; observe that the huffman tree can only reach back 32 kilobytes

[3] See http://www.doomworld.com/vb/post/1370814 about whether c4 should have its own themes.

**Comment by chungy** [comment]
Mind you that I'm just one person saying that unique music for all levels "would be nice" -- it's not a present goal. If all else were in place, Freedoom can release a version 1.0 without minding about tracks being used in multiple levels, at least with a variety like the present. Also, it's not possible in conventional engines to have separate sound tracks for single player versus multiplayer. But perhaps you were meaning FreeDM instead of Phase 2?

My count of 100 levels went by 36 in Phase 1, 32 in Phase 2, and 32 in FreeDM. You do bring up a point about Phase 1 Chapter 4 I hadn't considered, which would put the maximum number of unique tracks we could attain at 91. Still quite a lot :)

I'll reopen this issue, though MAP08 had its music replaced, the other maps are still problematic for the time being.

**Comment by fragglet** [comment]
All interesting discussion, but I think we should avoid any primary goal of "non duplicated soundtracks". I'd personally rather have 20 really good songs repetitively throughout the project than 100 mediocre ones.

**Comment by samboy** [comment]
For the record, the soundtracks I did not like in phase 2 were made by contributers whose music I, by and large, enjoy listening to when playing FreeDoom. Jute's music, which has the most misses for me, tends to have a nice jazzy progressive hard rock vibe to it I usually like, but sometimes he went overboard with the high-pitch sustained guitars which can be distractingly annoying.

As an aside, while MAP12's soundtrack is acceptable, if short, I did not find it particularly inspiring, so I've replaced it in my personal FreeDoom fork to use scragadelic/reflection_scrag.mid (DM10 music in FreeDoom).  This theme has a distinct 1980s vibe to it, but I think it is more interesting than the rather short generic sounding MAP12 theme from Jute.

**Comment by NickZ** [comment]
MAP01 is a D_RUNNIN clone.

Map16 is a very obvious clone, too.

**Comment by NickZ** [comment]
chungy has removed all the sound-a-likes and replaced them (2b32274), so this can be closed now.

**Comment by samboy** [comment]
Someone else opened up a discussion on Doomworld with similar concerns: https://www.doomworld.com/vb/freedoom/84593-music-should-be-curated/
