### ISSUE TITLE
Respect XDG

### ISSUE THREAD

**Issue by GreenLunar** [freedoom/freedoom#159]
Store configuration settings under `~/.config/prboom/` instead of `~/.prboom/`

You may also be providing an easier way to use user-defined `.wad` files by locating it under `~/.local/share/prboom/` in addition to using `prboom -iwad /path/to/file`.

**Comment by chungy** [comment]
This isn't an issue that directly affects Freedoom, please bring it up with PrBoom instead. :-)

**Comment by GreenLunar** [comment]
Where is the place to report issues related to PrBoom?

On the title screen of PrBoom I see:

Freedom
http://freedoom.github.io/
Version: v0.8
2014/01/01

and upon quitting, stdout shows (the following is Free Doom in red and blue):

```
################################################################################
################################################################################
################################################################################
################################################################################
################################################################################
################################################################################
###########################       ##############################################
###################       ###########        ###################################
  #########  ###  ################# ##########   ##   ########################  
###  ##################################################   ##   #################
###########################       ##############################   ##   ########
###################       ###########   ##   #############################   ###
###########  #################################   ##   ##########################
###  ##################################################   ##   #################
################################################################   ##   ########
#####################################       ##############################   ###
  ####    ####    ################# ######### ######## #######################  
################################################################################
                           http://freedoom.github.io/                           
```

**Comment by chungy** [comment]
Freedoom is the game data, PrBoom is the engine you happen to be playing with at the moment.

For the upstream project the proper place would probably be the bug tracker on SourceForge: http://sourceforge.net/p/prboom/bugs/?source=navbar

This project, unfortunately, is extremely inactive and effectively dead (though you can still try reporting it); the present development is done in PrBoom-Plus, and the feedback for it is only available via the following forum thread: http://www.doomworld.com/vb/source-ports/31039-prboom-plus-ver-2-5-1-3/

**Comment by GreenLunar** [comment]
Thank you.
