### ISSUE TITLE
Please revert SKY4 texture to use SKY4 patch

### ISSUE THREAD

**Issue by Blastfrog** [freedoom/freedoom#166]
Most PWADs for E4 assume the bright orange sky, using the starry night sky by default conflicts with that.

**Comment by fragglet** [comment]
Is it a big deal? PWADs assume "a sky" of some kind (which it is), and Freedoom's aesthetics are never going to perfectly match Doom's anyway. But they will match the intended aesthetics of our E4. How many PWADs replace E4 anyway?

**Comment by chungy** [comment]
I've stated a few times on IRC that I don't believe any PWAD is negatively impacted by the sky not being orange, especially in any significant capacity. I feel that this request is simply "Make Freedoom more like Doom"

**Comment by Blastfrog** [comment]
I already made decent looking version of SKY4 (not committed yet), and I feel that the night sky simply doesn't look that good. Double Impact looks fine with the orange sky.

"Freedoom's aesthetics are never going to perfectly match Doom's anyway"
There's a difference between not being a carbon copy and being completely different.

"I feel that this request is simply "Make Freedoom more like Doom""
Sure, but the color a specific sky being the same isn't going to infringe on anything. I don't advocate for cloning Doom, but we should follow it as a general guideline.

**Comment by fragglet** [comment]
I think sky textures are somewhat unique - unlike other textures where having something completely different can potentially cause significant disruption to the intended look of the level, the sky is just a backdrop that you see when you look out of the window. One answer might be to just imagine that you're playing your favorite E4 replacement PWAD at night time instead of during the day :)

**Comment by Blastfrog** [comment]
Here's an idea, what about an orange starry sky?

**Comment by chungy** [comment]
> I don't advocate for cloning Doom, but we should follow it as a general guideline.

Freedoom has a goal to be compatible with PWADs, but not a goal to look like Doom. That only makes it feel like a cheap knockoff (which it already does to a point, and it's one of the most difficult things to change).

If a non-orange sky has no harm to the visual presentation of PWADs, then I think there shouldn't be an effort to replace it with an orange sky for the sole sake of being like Doom. I don't think the sky we have looks bad as it is.

**Comment by chungy** [comment]
Given that your idea is not going over well with myself nor fraggle, I will close this issues thread. If you'd like to continue a discussion, and get a wider consensus on it, feel free to open a Doomworld thread about it and reference this issue report.
