### ISSUE TITLE
Replace music too close to originals

### ISSUE THREAD

**Issue by jewellds** [freedoom/freedoom#168]
https://github.com/freedoom/freedoom/blob/master/musics/csabo/d_stalks.mus

This track, which we are using for MAP02, is a very obvious cover of D_STALKS, which is used for MAP02 in Doom 2.

For comparison, here are the two tracks, played on MS Wavetable.
I've used Youtube uploads because our D_STALKS is a mus file, which doesn't play in most browsers.

https://www.youtube.com/watch?v=E6FjPxxmSbE
https://www.youtube.com/watch?v=N_GH9YiiBWw

The similarity has always bugged me and I've been meaning to mention it for a while, but with the [recent addition of the new Mogul tracks to the repository](https://github.com/freedoom/freedoom/commit/e3e9731082a77d906e743ca99c19083944166691), we have a good opportunity to replace it.

**Comment by fragglet** [comment]
+1 to eliminating resources that sound like originals - not just MAP02 but others too.

**Comment by jewellds** [comment]
The MAP01 and MAP04 tracks are similar to their Doom 2 counterparts,  but I didn't mention those because they are distinct enough that they couldn't be mistaken for one another. I personally always considered those tracks an acceptable homage rather than an outright ripoff.

Map02 is very a bad case where they sound nearly identical to one another.

**Comment by jmickle66666666** [comment]
If it helps, you can use any of my midis in freedoom:
https://www.doomworld.com/vb/wads-mods/72311-midi-jmickle66666666s-midi-year-one/
https://www.doomworld.com/vb/wads-mods/75017-jmickle66666666s-midi-pack-two-the-second-one/

**Comment by Blastfrog** [comment]
Should probably get rid of all of the obvious clones, such as the ones based on Ultimate Evil, At Doom's Gate, Deep into the Code, etc.

**Comment by jewellds** [comment]
Admittedly I have a soft spot for some of the sound-a-likes, but given that there seems to be a consensus to take them out, and with the recent commit replacing MAP02 and MAP04, I'm going to go back on my last comment and agree that we should go the whole hog. Does anyone know of any good quality tracks that are currently unused?

**Comment by NickZ** [comment]
MAP02 has been replaced, chungy is working on squashing the rest of the sound-alikes

**Comment by NickZ** [comment]
MAP16 should be added to this list.

**Comment by NickZ** [comment]
Merging with #156
