### ISSUE TITLE
DBRAIN1 texture needs a replacement

### ISSUE THREAD

**Issue by Blastfrog** [freedoom/freedoom#169]
It's crazy. It's not the same size as the other DBRAINx textures, and is made of a ton of redundant patches. It's also not compatible with PWADs that only replace patches.

What reason is there to set it up this bizarrely?

**Comment by Voros2** [comment]
Thanks to (https://github.com/freedoom/freedoom/commit/87f848d7fa76d00f5851b33331866b5719825077), I assume this can be closed?

**Comment by NickZ** [comment]
Fixed in #435 and #406.
