### ISSUE TITLE
Link to the latest build doesn't work

### ISSUE THREAD

**Issue by AXDOOMER** [freedoom/freedoom#170]
On this page: https://freedoom.github.io/download.html
The link to the lastest build doesn't work. 
http://freedoom.soulsphere.org/
My browser can't connect. Last week it didn't work too. It gives a connection timeout.

**Comment by fragglet** [comment]
See https://www.doomworld.com/vb/freedoom/80924-http-freedoom-soulsphere-org-down/

**Comment by AXDOOMER** [comment]
Sorry, I didn't see that.
