### ISSUE TITLE
MAP06 Detail

### ISSUE THREAD

**Issue by Catoptromancy** [freedoom/freedoom#20]
This map looks very bland. Could use reasonable modern style detailing. Some minor gameplay changes would not hurt either.

**Comment by NickZ** [comment]
Any update, Doommarine23?

**Comment by NickZ** [comment]
Map06 was replaced with Jimmy's Jenesis MAP03, so this issue is moot.

**Comment by Doommarine23** [comment]
Been too busy, glad to see it was resolved either way.
