### ISSUE TITLE
Get rid of symbolic links

### ISSUE THREAD

**Issue by fragglet** [freedoom/freedoom#202]
Freedoom has a slightly weird setup where we store resources (graphics, sounds, etc.) in subdirectories by the creator of the resource, and then symbolically link them into the parent directory for deutex to read.

This made some kind of sense years ago when there was no version control and I was trying to divide up the repository in a way that I thought made sense. But I don't think it's a good idea any more. It causes several problems:

* Symbolic links don't exist on Windows, so it is difficult to submit changes to Freedoom. Example is #195 where @Blastfrog encountered problems because of this.

* The repository is harder to browse in GitHub because you can't just find a resource and click it - you just get a "symbolic link" display telling you that your resource is in another directory.

* Resources often have more than one creator. This causes problems because if someone edits a resource originally made by someone else, it's no longer clear where that resource belongs. For example I took the "policy" that it should resources go in the directory of their original creator, but I've also seen resources moved between directories when making a change. Lack of consistency means that the directories become meaningless or even misleading.

* Subdirectories duplicate the functionality of a version control repository. You can already see who made a resource by checking the revision history of a file in Git, and it's likely to be more detailed and accurate than the subdirectory name.

* Dividing up by directory can imply some kind of ownership or territory, which is counter to the nature of the project.

I propose that we get rid of the subdirectories and move them into the parent directories as a more flat list of files. There are a few exceptions where this won't work; for example, lumps/genmidi, lumps/dmxgus, graphics/text are examples of functional subdirectories where we build things; they are not simply there to show authorship. In these cases we can still get rid of symlinks by changing their Makefiles to copy generated files into the parent directories.

**Comment by fragglet** [comment]
By the way, if we do this, I'd recommend splitting it into multiple commits by author directory. That way if you want to see the old subdirectory information, you can look at the revision history to see "this file used to be in the fraggle subdirectory", etc.

**Comment by Blastfrog** [comment]
I'm fully in favor of this. I was intending to suggest this myself at some point.

**Comment by chungy** [comment]
All sounds good, should be fairly simple to implement as well without breaking the build system. Feel free to do so :P

**Comment by rjy** [comment]
See also

https://www.doomworld.com/vb/freedoom/42768-handling-maps-in-svn/

Following that thread I wanted to do symlink removal and had started writing a script to automatically generate a slew of commits. One thing I discovered was an infelicity in rename detection. If you delete a symlink and move a file into its place in the same commit, Git will see it as a filetype change, and e.g. git log --follow will not work. Symlink deletion and file rename need to occur in separate commits.

**Comment by chungy** [comment]
I just pushed 113 commits for the initial stage of symlink removal. before RjY's comments about --follow, although it seems alright anyway.

The non-trivial things are still left to be dealt with, but at least it's a start :p

**Comment by rjy** [comment]
Mike Swanson wrote:
>I just pushed 113 commits for the initial stage of symlink removal. before RjY's comments about --follow, although it seems alright anyway.

Fair enough - no doubt Git has improved in the interim.

**Comment by chungy** [comment]
> Fair enough - no doubt Git has improved in the interim.

Probably so, and this is only a UI issue anyway. --follow makes the UI part look in the repository for simultaneous deletion and creation operations that happen to have (mostly) the same file contents. :)

**Comment by fragglet** [comment]
Oh, I was planning to use CREDITS to craft those commits as being from the individual authors. I guess this is fine though.

**Comment by fragglet** [comment]
Remaining author-name directories:

lumps/cph/misc-lumps - recommend renaming to lumps/palette or something similar (palette is a slightly inaccurate name as the scripts generate colormaps too).

graphics/captainw - suggest moving to graphics/titlepic

patches/agm_logo - is it worth having a separate top-level directory, eg. art/ where we put artwork that is used as a template for other graphics?

**Comment by Blastfrog** [comment]
I support having a source art directory.

**Comment by chungy** [comment]
> patches/agm_logo - is it worth having a separate top-level directory, eg. art/ where we put artwork that is used as a template for other graphics?

Yes, definitely. The move was a quick hack to solve the immediate first step, don't take it as a final judgment.

**Comment by fragglet** [comment]
Pushed a couple of commits that eliminated some more symlinks.

**Comment by NickZ** [comment]
Awesome. Having no symlinks is really going to be help with people developing on Windows.

**Comment by fragglet** [comment]
Bunch more progress. Only a few symlinks left now.

**Comment by NickZ** [comment]
After all of fraggle and chungy's work, with commit c14d7a1, there are no symlinks left in the repository, and there are no build errors resulting from their removal. Great job guys!

**Comment by fragglet** [comment]
Thanks!
