### ISSUE TITLE
0.10 C3M7 crashes boom

### ISSUE THREAD

**Issue by Danfun64** [freedoom/freedoom#203]
Freedoom is meant to be compatible with boom 2.02. Yet when I get access C3M7, I get the error "R_TextureNumForName: BRICK7 not found". (Video Verification: http://www.mediafire.com/watch/o4oob512o12qdaw/dosbox_000.avi)

I have no idea how this bug got missed for the release of 0.10, but I think it's worth a release of a 0.10.1 with this bug fixed. After all, for the few who use boom 2.02, having a level crash on a "stable" release is disheartening.

**Comment by chungy** [comment]
Thanks for the report. I'll get a 0.10.1 pushed out in about a week's time, giving a little room for any other potential issues first. :-)

**Comment by chungy** [comment]
Let's keep this open until the 0.10 point release :)

**Comment by rjy** [comment]
I'm surprised this can happen -- aren't the texture lists for phase 1 and 2 the same?

**Comment by fragglet** [comment]
Looks like it was a level problem rather than a texture problem.

It would be good idea to set up some kind of automated tests to detect common problems like this one and others.

**Comment by Danfun64** [comment]
...so I take it that the freedoom-0.10.y branch is where the next point release is coming from? If so, is it worth merging the other changes (like map05 fixes and removal of synlinks)?

**Comment by chungy** [comment]
The 0.10 point release(s) should fix things that were overlooked and a release critical bug, such as the one reported here. We do have to save the bigger changes for the next major version :)
