### ISSUE TITLE
Convert all music into MIDI format

### ISSUE THREAD

**Issue by fragglet** [freedoom/freedoom#206]
All source ports support MIDI files in lumps, and it was even supported in Vanilla Doom. Most of our music is already in MIDI format but there are a few lumps that are in Doom's native MUS format. I think we should just convert everything over to MIDI. Unlike MUS it's a standard format; using MIDI makes it easier to use standard music tools for contributors to edit stuff. It also makes it easier for people to reuse Freedoom's content as they can just pick the files out of the directory instead of having to go through a convoluted conversion process.

**Comment by fragglet** [comment]
One exception seems to be Doom 95, but that port has [so many problems](http://doomwiki.org/wiki/Doom95#Bugs), it doesn't seem worth making everything MUS format just to support it.

I don't know of any other source ports which don't support MIDI.

**Comment by jmickle66666666** [comment]
Since vanilla doom can use midis, there is no argument for using MUS. Doom 95 technically isn't vanilla compatible if it can't use MIDI files, and the same goes for other source ports too.

**Comment by chungy** [comment]
Doom95 shouldn't be a real concern.

**Comment by fragglet** [comment]
Yeah, that's one of the many annoying restrictions of deutex.
