### ISSUE TITLE
Freedoom phase 2 (0.10) map 06 bug with Odamex 0.7 ?

### ISSUE THREAD

**Issue by sviscapi** [freedoom/freedoom#213]
Hi,

I have just discovered a bug in Freedoom phase 2 (0.10) map 06 when playing with Odamex 0.7 (ARM port on the Open Pandora gaming console): 

* Release thread:

https://pyra-handheld.com/boards/threads/beta-odamex-0-7.76607/

* Package on our repository: 

http://repo.openpandora.org/?page=detail&app=odamex-magicsam

Just after entering the "blue key" room on the left of the starting point, there's another room with a secret switch in it (some kind of a blinking light). After pressing the action button against that blinking light, there was a weird sound and the display got all messed up...

For your convenience, I'm attaching a saved game just before triggering said switch, so you can try to reproduce that issue on your side.

[odasv3.zip](https://github.com/freedoom/freedoom/files/72675/odasv3.zip)

Is it a Freedoom bug or an Odamex bug ?

Cheers, Samuel (a.k.a "Magic Sam" on the Open Pandora boards)

**Comment by NickZ** [comment]
That's a bug in Odamex. The linedef for that secret door is a Boom generalized floor, and Odamex must have trouble implementing it.

We're planning to move to vanilla compatibility for future releases of Freedoom, so this should get resolved in the future. In the meantime, I recommend trying a different port.

**Comment by fragglet** [comment]
Closing as this is an Odamex bug; might be a good idea to report it to the Odamex devs.
