### ISSUE TITLE
Phase 2 MAP11: one secret sector is unreachable

### ISSUE THREAD

**Issue by watchmakerful** [freedoom/freedoom#220]
Sector 470 is too narrow to be entered and is tagged 9 (secret), therefore one cannot obtain 100% secrets on this map.
![168](https://cloud.githubusercontent.com/assets/10285128/12079604/fa28d22e-b247-11e5-8a3a-e9846374e173.png)

**Comment by andwj** [comment]
Looks like that sector was not meant to have a secret type.

I have began work to vanilla-fy this map, will fix this too.
