### ISSUE TITLE
Tall lamp misplacement?

### ISSUE THREAD

**Issue by CWolfRU** [freedoom/freedoom#221]
From Doomworld:

"The new tall techno lamp:
sprites/tlmpa0.gif 
sprites/tlmpb0.gif 
sprites/tlmpc0.gif 
sprites/tlmpd0.gif 
that was added on 1st January, appears misplaced. It does not stay at it's place, but moves, when the player moves. Please fix that.
Greetings
funduke"

**Comment by NickZ** [comment]
Could you submit the size corrected lamps that raymoo made with this issue
fixed? You need to modify buildcfg.txt with the correct offsets.

**Comment by CWolfRU** [comment]
Sure.

**Comment by andwj** [comment]
The "fixed" offsets are not correct -- the X offset has been set to the full width of the sprite (23 units), where it should be half the width (11 or 12).
