### ISSUE TITLE
HOM effects in freedoom phase 1 first demo, development version.

### ISSUE THREAD

**Issue by FredBezies** [freedoom/freedoom#231]
There is some HOM effects in demo1 in freedoom phase 1, development version. You can see them in prboom-plus when player is in the corridor and opened windows.

**Comment by chungy** [comment]
Just an artifact of a Boom map with a vanilla demo. It's not a real bug in either Freedoom nor PrBoom-Plus, and should be resolved whenever the map becomes vanillafied
