### ISSUE TITLE
Demo 2 in freedoom phase 1, development version, is not playing correctly.

### ISSUE THREAD

**Issue by FredBezies** [freedoom/freedoom#232]
Looks like there is a bug in this demo. It stops about 10 to 20 seconds after it starts. Wrong map used ?

Player is killed really shortly. How many time do you have to wait to load third demo ? Seeing this in prboom-plus.

**Comment by chungy** [comment]
Are you using the Freedoom 0.10.1 release? It should work fine...

**Comment by FredBezies** [comment]
I'm using git version as I'm keeping them up to date on archlinux user repository.

**Comment by chungy** [comment]
That's interesting, the map hasn't been touched, it should still sync. Perhaps it's a problem in your copy of prboom-plus?

**Comment by FredBezies** [comment]
Well, I'm using prboom-plus 2.5.1.4 which was released a few days ago.

http://prboom-plus.sourceforge.net/history.html

"2.5.1.4  @ 2016-Jan-10"

Bug in prboom-plus 2.5.1.4 ?!

**Comment by chungy** [comment]
Certainly interesting. I'm not seeing a desync with that engine myself :/

**Comment by Voros2** [comment]
No its true.
What's interesting is that in 0.10/0.10.1, the player doesn't die in demo2 of Phase 1 or demo4 of Phase 2, very quickly. But the autobuilds have this problem. That's why I sent in https://github.com/freedoom/freedoom/pull/277 to fix this.
