### ISSUE TITLE
FreeDM map10: Exit switch not aligned correctly 

### ISSUE THREAD

**Issue by AXDOOMER** [freedoom/freedoom#238]
![doom00](https://cloud.githubusercontent.com/assets/6194072/12869806/e30de6b8-ccf7-11e5-87c4-882dc554e5d7.png)

**Comment by AXDOOMER** [comment]
On map 21, this may be the same bug. Caused by a changed texture?
![map21](https://cloud.githubusercontent.com/assets/6194072/13908810/47a82b0a-eee1-11e5-8e04-3c35d01daa17.png)

**Comment by AXDOOMER** [comment]
> On map 21

The saw floats, it should be fixed too...

**Comment by Proluiz** [comment]
This was fixed on https://github.com/freedoom/freedoom/pull/621 dm21.wad
Can be closed.
