### ISSUE TITLE
Sprite not properly aligned on its axis

### ISSUE THREAD

**Issue by AXDOOMER** [freedoom/freedoom#239]
I don't know which sprite this is, but here's a screenshot. 
![doom04](https://cloud.githubusercontent.com/assets/6194072/12869871/9c1c8d48-ccf9-11e5-91f4-bc601e0fb1d4.png)
When you turn around it, it moves, so this means the sprite is not centered on its X axis.

**Comment by andwj** [comment]
The sprite is CEYE (frames A,B,C)

I will fix it shortly.
