### ISSUE TITLE
Weapon firing frames that are not lit correctly

### ISSUE THREAD

**Issue by AXDOOMER** [freedoom/freedoom#240]
Somehow, the light reaches the back of the pistol. This violates the laws of physics.
![doom00](https://cloud.githubusercontent.com/assets/6194072/12869882/05528de4-ccfa-11e5-8900-91034757f9d7.png)
The SSG is not lit at all.
![doom01](https://cloud.githubusercontent.com/assets/6194072/12869883/055a16f4-ccfa-11e5-8fb7-477d1ba1d727.png)
These two are fully lit:
![doom02](https://cloud.githubusercontent.com/assets/6194072/12869885/0592ce04-ccfa-11e5-9c59-ec11ec3acc16.png)
![doom03](https://cloud.githubusercontent.com/assets/6194072/12869884/0569e14c-ccfa-11e5-9e3c-7921bdc7e73b.png)

**Comment by Xindage** [comment]
actual state of this issue, pistol:
![image](https://github.com/freedoom/freedoom/assets/6380147/e406ff95-56a2-4c9e-ab0e-52294f9b6e24)
Shotgun:
![image](https://github.com/freedoom/freedoom/assets/6380147/1d27a53b-de70-4687-acb3-cd1c0808941f)
![image](https://github.com/freedoom/freedoom/assets/6380147/71d0b68e-2c9d-4a1a-a742-1f304e6ee0e3)
chaingun:
![image](https://github.com/freedoom/freedoom/assets/6380147/c2d74d62-07e3-4bad-b630-c5a79c98696d)
![image](https://github.com/freedoom/freedoom/assets/6380147/66b1edb5-b15a-416c-87b1-42dfd38c2552)
Rocket:
![image](https://github.com/freedoom/freedoom/assets/6380147/bb7d8cd1-614b-4f19-9952-26d47eec6800)
![image](https://github.com/freedoom/freedoom/assets/6380147/490c6bd4-420c-4e17-8799-7f76b0f0337d)
Plasma:
![image](https://github.com/freedoom/freedoom/assets/6380147/3cf7fb7b-9323-48a0-8fc9-ea8ca2ae0552)
BFG:
![image](https://github.com/freedoom/freedoom/assets/6380147/8235b0f8-ac5d-4bd4-9f0b-675b22e57445)

**Comment by Xindage** [comment]
someone still think that we still need to update something about this? bfg and plasma dont follow the rules as well, but i dont know if worth the effort...

**Comment by mc776** [comment]
i've tried these before and with the all-or-nothing i personally think it looks worse done "right" - where it's even noticeable (which it really isn't in vanilla above 160 or so).

making the whole sprite bright is at least consistent with the monsters and multiplayer.

**Comment by MerrittK** [comment]
Should we close this? A bunch of recent PR requests have been covering the flash frames.

**Comment by mc776** [comment]
At this point it's actually kinda consistent:

- everything else has a partially illuminating flash.
- the polaric energy weapons that launch an enormous glowing ball of hot plasma are fully lit up.

It's something to keep in mind if anyone wants to do a new BFG or de-idify the PEW, but it doesn't look buggy or inconsistent anymore... if anyone with the power to do so disagrees they're free to re-open and comment.
