### ISSUE TITLE
VISPLANE OVERFLOW in 1st level

### ISSUE THREAD

**Issue by CraftedPixel** [freedoom/freedoom#241]
Well it is sort of impossible to look outside without a visplane overflow error.
Can someone help :D

**Comment by fragglet** [comment]
Which level do you mean? C1M1 or MAP01?

**Comment by chungy** [comment]
and which version?

Freedoom is not yet vanilla-compatible, neither in the latest release nor the development tree. If you're looking for help in converting levels, you might try Doomworld's WADs and Editing forum.

**Comment by CraftedPixel** [comment]
I just learned how to make maps, but could not even get doors to work :D
I am talking about the episode 1 level 1 when looking outside will confuse the engine and crash
The editor I am using detected many errors in the level
Also trying to figure out how to open up a wad file to get all the sprites for editing
P.S.
And how to get doors working
