### ISSUE TITLE
A particular sector in Phase 1, E1M1 in the toxin pit isn't a damaging floor.

### ISSUE THREAD

**Issue by TrustyGun** [freedoom/freedoom#245]
This one, exactly. This is the first waterfall, but it is the same for the other waterfall. You can walk on top of it after the toxin pit rises.
![screenshot_doom_20160221_072758](https://cloud.githubusercontent.com/assets/7079721/13202551/ccb128b4-d86c-11e5-9611-c7505d0bed88.png)

**Comment by CraftedPixel** [comment]
hmm someone must have forgot lol
