### ISSUE TITLE
Remove Boom colormaps from IWAD

### ISSUE THREAD

**Issue by Blastfrog** [freedoom/freedoom#246]
Since we're targeting vanilla now, there's no reason to hold onto these Boom colormaps any longer. The maps that use them should be edited not to.

**Comment by fragglet** [comment]
Have all maps been converted to Vanilla? If not then the colormaps should stay until they have been.

**Comment by chungy** [comment]
They haven't and the project hasn't yet made the full vanilla switch.

**Comment by Blastfrog** [comment]
We can still keep the Boom format maps for the time being without colored lighting, somebody can just edit it out. I don't see why it's necessary to wait until they've all been converted to vanilla.

**Comment by fragglet** [comment]
I'd ask the flip question: why's it so urgent to remove all colormaps as soon as possible?

It seems like the most reasonable course of action is to just leave this bug open until all the levels have been converted; then it's a trivial change to just remove the colormaps.

**Comment by Blastfrog** [comment]
Why now and not later? I was thinking it'd be nice to just to clean the IWAD up a bit, but yeah, it would be easier to wait.

**Comment by Proluiz** [comment]
e2m4 (i think) uses colormaps, also i dont know why get back to vannila settings lots of maps is going to get edited by getting into vannila mostly is the FD2 by the visplanes ouverflow

**Comment by Voros2** [comment]
Now that all the maps are limit removing/vanilla, I think its time to remove Boom colormaps now.

**Comment by chungy** [comment]
Resolved as of a0e65f7fedbe7f7f4467c362059c2c57d7f69e10
