### ISSUE TITLE
Can someone get my Super Shotgun sound into freedoom?

### ISSUE THREAD

**Issue by ghost** [freedoom/freedoom#250]
I don't know how to convert this sound file to doom format and get it into freedoom.
Here is my sound file I recorded MYSELF. It is under CC - 0 1.0
http://creativecommons.org/publicdomain/zero/1.0/
so you can convert it to the license that freedoom uses.
http://www.mediafire.com/download/p18u6gp79418187/SuperShotgunLoadCC0.wav
Glad to contribiute to freedoom!

**Comment by chungy** [comment]
Not a problem. Could you provide your name and email for the submission?

**Comment by CraftedPixel** [comment]
Is there a PM or something? I don't want to say it here lol

**Comment by chungy** [comment]
Can send it to me at mikeonthecomputer@gmail.com

**Comment by CraftedPixel** [comment]
Did you get the message?

**Comment by chungy** [comment]
I did.

The sound seems a little bit too echo-y for direct submission, but I'm sure it can be cleaned up and made beefier :)

**Comment by CraftedPixel** [comment]
Yeah I just got a candy dispenser. Found the best sound. Slowed it down. then put some echo to the sound

**Comment by CraftedPixel** [comment]
You can close the thread once you got the the sound in the game

**Comment by VGAce** [comment]
the super shotgun sound that is currently in freedoom is fine dont change it!

**Comment by CraftedPixel** [comment]
Yeah I can't change it, but I am requesting it to be changed. And there has not been many new things to freedoom.

**Comment by 3rdwiki** [comment]
What is the current shotgun sound in freedoom ? I'd like to compare.

chungy's sound was pretty good, to me.

**Comment by CraftedPixel** [comment]
Hey Chungy how did you convert the wav into doom format?

**Comment by Voros2** [comment]
Sorry for bumping, but what exactly is your sound? I mean which sound does it replace? dssgcock?
And you don't have to convert it. Deutex can read WAV files and convert them during the building process.

**Comment by CraftedPixel** [comment]
If you looked at the title of the issue, you will find that the sound is that of a super shotgun.
Use audacity to separate the opening and closing of the super shotgun into two files.
I don't remember what sound it does replace, but you can go into the weapon sounds and hear the one that sounds like a super shotgun. At least that's what I did.

**Comment by AXDOOMER** [comment]
The current SSG sound is fine, why change it?

**Comment by 3rdwiki** [comment]
> The current SSG sound is fine, why change it?

As before, I would sincerely ask that someone gives links to both sounds so that **we** can decide.

**Comment by AXDOOMER** [comment]
It's the reloading sound. It must be split in two. The SSG has a shooting sound and two sounds for the reloading (when the shells are put inside and a second when he closes the gun). It may even be three reloading sounds. There may be another one for when the gun is opened. 

Your sound has too much echo and looks less professional that the current sound. I don't want to be abrupt, but that's how it is.

**Comment by Voros2** [comment]
Too much echo. Do some fixes, then maybe it'll be good, cause IDK.

**Comment by Xindage** [comment]
closed by being old issue, 2016.
