### ISSUE TITLE
FreeDM map27: Shells float in the air when the floor changes height

### ISSUE THREAD

**Issue by AXDOOMER** [freedoom/freedoom#251]
Only tried with Chocolate-Doom. I know this is an engine bug, so I believe it won't happen in other ports, but it should be fixed. 
![map27](https://cloud.githubusercontent.com/assets/6194072/13908819/88684f26-eee1-11e5-96b1-95ab2f18aff0.png)

**Comment by Proluiz** [comment]
nice find heh

**Comment by Proluiz** [comment]
This was fixed on https://github.com/freedoom/freedoom/pull/621
