### ISSUE TITLE
freedoom1.wad is not identified as a doom.wad drop-in replacement

### ISSUE THREAD

**Issue by fabiangreffrath** [freedoom/freedoom#253]
Let's not forget about this: Current stable releases of Chocolate Doom fail to identify freedoom1.wad as a full, i.e. retail, variant of DOOM.WAD and consider it a shareware release instead. This is because apparently the `spida1d1` lump is either missing in freedoom1.wad or Choco is unable to locate it for other reasons.

More background here: https://github.com/chocolate-doom/chocolate-doom/pull/702

**Comment by Voros2** [comment]
Is this still an issue? It looks like the problem was fixed.

**Comment by Xindage** [comment]
i'll test it someday when i get on windows

**Comment by Catoptromancy** [comment]
Freedoom1 and 2 are missing spida1d1. Apparently Chocolate has gone around this by just figuring out other ways to recognize freedoom. 

I still think it should be there. Can just duplicate SPIDA1 into SPIDA1D1.

**Comment by mc776** [comment]
If this has been resolved on Chocolate's end I don't see why this needs any more attention, unless vanilla does the same thing.

Adding *both* SPIDA1 and SPIDA1D1 is asking for disaster.

**Comment by Catoptromancy** [comment]
Oh yes, I must have looked at editor wrong. It looks like neither doom.wad or doom2.wad has spida1, yet freedoom does. Maybe a mislabel of resource that game somehow still works with?

**Comment by mc776** [comment]
SPIDA1 is parsed as the "A" frame of the actor viewed from the front.

SPIDA1D1 is parsed as
1. the "A" frame of the actor viewed from the front; *and*
2. the "D" frame of the actor viewed from the front, *mirrored horizontally*.

If you have both, at best only the one that's loaded later would be used (so SPIDA1D1 would overwrite both SPIDA1 and SPIDD1, not sure what would happen if SPIDA1D1 were loaded between those two). (the "disaster" I imagine would be if different sourceports treated multiple appearances of the "same" sprite differently, or some GZDoom mod needed to count the number of times a sprite was replaced by other mods, e.g., to determine whether to fix something that other mods tend to fix as well.)

Pretty much no other monster flips its front frame like this (not sure about the pain elemental) - just about nothing is so symmetrical for the animation to work, and it really throws people off who are trying to edit the sprite. And on modern machines no one really cares about saving the space from just that one frame for the additional confusion and limitation to be worth it.

And so, being sensible and reasonable, the artist who did the Freedoom megatechnospider sprite used a simple SPIDA1 - and I don't think we should switch to SPIDA1D1 just to accommodate one special use case that is no longer even in effect.

**Comment by Catoptromancy** [comment]
Doom2 1.9, and dsda-doom:
https://cdn.discordapp.com/attachments/356557933145882624/874076881312436344/doom01.png

**Comment by chungy** [comment]
Use Ultimate Doom to see the fourth episode.

This issue has been long resolved.
