### ISSUE TITLE
freedoom2

### ISSUE THREAD

**Issue by Buddies234** [freedoom/freedoom#254]
On map02 it won't open the door with the blue key on red key

**Comment by CraftedPixel** [comment]
That is how doom works...

**Comment by kyromaster** [comment]
I also experienced this. What do you mean with "how doom works"?
I'm not sure whether this is a bug or there's another way to complete the level.
I'm using latest zdoom.

**Comment by fragglet** [comment]
The bug description is unclear. Maybe one of you can clarify what exactly the bug is here?

**Comment by kyromaster** [comment]
In the level you can get both the red and the blue key. There's a red door in the north side of the map which doesn't open even though I've the key. Perhaps this is the "bug" that the door isn't openable. From what I see it's "almost" fact that with the yellow key you can complete the map.
I remember that I've played that level some time ago and had the same "problem".
I thought a little bit about "That is how doom works"...I'm not english native but were're talking about computer games here ;)

**Comment by CraftedPixel** [comment]
What I mean is that a red door cannot be opened with a blue key.

**Comment by alexey-lysiuk** [comment]
Works for me using the latest rheit/zdoom@7bdb98c with default compatibility settings.
Probably @Buddies234 meant that blue and/or red key doors cannot be opened using _corresponding_ keys. This is true because those doors must be opened by triggering two switches in the room near the starting point.

**Comment by kyromaster** [comment]
That's right of course!
Interesting level design ;)
