### ISSUE TITLE
Trigger not working properly on C2M9

### ISSUE THREAD

**Issue by fabiangreffrath** [freedoom/freedoom#256]
Hi guys,

this has been reported by eingousef on the Debian BTS [1]:

In freedoom phase 1, on map C2M9, there's a switch which is supposed
to sink into the ground when clicked, and to open some walls behind
which orb monsters and deaflares are hiding. But in 10.1 when you
click on it it just sinks into the ground, whithout opening the
hideouts.

The mapmaker knows this, so if you send him this bug report it should
ring a bell to him. He says that C2M9 has been modified by someone
else and that the modifications broke some triggers. Apparently
clicking the switch makes it sink into the ground, and the hideout
opening is triggered by the fact of clicking "action" while crossing
the line in front of the switch, so both events happen at the same
time. After the map modifications the line and the switch model are
mismatched, breaking that behavior. But if you go back at the place
where the switch was, and walk forward while clicking "action", it
triggers the hideout opening. So the game is stiff playable, you just
need to know the solution, but it's hard to discover, especially with
prboom-plus, where the right mouse button used for the "action"
command is also mapped on the "forward" command and there's no simple
way to change that.

Note that a similar bug happens at the beginning of the map, in the
tiny 100 armor room. Opening the door is also supposed to teleport you
in the minigun room, in 0.10.1 this doesn't happen and you can fight
the pain lord from the outside.

Adding a screenshot of a blocking situation that is not supposed to
happen in the game :

![1465587121](https://cloud.githubusercontent.com/assets/6449237/16059013/6c49de5c-3281-11e6-9e11-79074f8a173b.png)

(the button has sunk into the ground and the hideouts are still
closed).

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=827117

**Comment by Proluiz** [comment]
already on it
give me a week and i'll fix done

**Comment by Voros2** [comment]
Oh, so i wasnt hallucinating. Did you fix it yet proluiz?

**Comment by Proluiz** [comment]
sorry i had fixed indeed but i was having poblem to commit.

**Comment by Voros2** [comment]
Oh. Well can you commit it now?

**Comment by Proluiz** [comment]
If i can fix my git extensions i'll try send another pull request, or i'll have to post the file here or in forum i'm having issues there...

**Comment by Proluiz** [comment]
double post i cant yet find a way so i'll post there, if you can voros try do the request, https://www.sendspace.com/file/zx23yr

**Comment by Voros2** [comment]
I'll see what I can do :)

BTW, have you tried updating your fork?
