### ISSUE TITLE
DOOM 2 master levels launcher

### ISSUE THREAD

**Issue by CraftedPixel** [freedoom/freedoom#258]
Is it possible to have a launcher for the doom 2 master levels instead of having to _chocolate-doom -file '~/Desktop/games/doomwads/masterlevels/ATTACK.WAD'_ for every wad.

**Comment by fragglet** [comment]
Master Levels for Doom 2 have nothing to do with Freedoom - did you mean to file a Chocolate Doom bug?

**Comment by CraftedPixel** [comment]
Well ^%&* This is the wrong place.
But you did create chocolate-doom didn't you?

**Comment by CraftedPixel** [comment]
I am putting this on chocolate-doom
