### ISSUE TITLE
Freedom 0.9: Phase 1 Episode 1 Map 2

### ISSUE THREAD

**Issue by richardskumat** [freedoom/freedoom#259]
Where are you supposed to end this map(Nuclear Plant)?

I've wiped out the whole level, got the blue and red cards and there's no way out.

There seems to be a small room locked behind a red card door near the starting place where the switch on the wall doesn't seem to do anything.

Playing this on Debian 8 i686.

See https://s31.postimg.org/4b73mawqz/Screenshot_100716_16_21_31.png

**Comment by richardskumat** [comment]
Skipped the map with:

```
cheat idclev13
```

**Comment by Voros2** [comment]
Please download version 0.10.1

**Comment by richardskumat** [comment]
Yes, that's what I've ended up doing. Closing this now.
