### ISSUE TITLE
C1M1Crash at Chocolate Doom

### ISSUE THREAD

**Issue by killruana** [freedoom/freedoom#261]
After the first door, when I go to the right of the room, chocolate-doom crash with this error: 
"R_DrawPlanes: visplane overflow (142)"

Freedoom v0.10.1

**Comment by fragglet** [comment]
Thanks for your report. Freedoom doesn't work with Chocolate Doom since its levels are not vanilla-compatible. See https://www.chocolate-doom.org/wiki/index.php/Freedoom for more information. There's a project underway to convert Freedoom to be vanilla-compatible but it is still in development.

**Comment by killruana** [comment]
Ok.
Thank you for your response.
