### ISSUE TITLE
Lift that is supposed to lead to yellow key on C3M7, phase 1 ins't working

### ISSUE THREAD

**Issue by senpay** [freedoom/freedoom#280]
I currently faced an issue with lift that should lead to room with yellow key not working properly - it just changes floor level for a couple of second.

Please see a screenshot for a place I am talking about
![1](https://cloud.githubusercontent.com/assets/12186301/17974267/1519f248-6aee-11e6-80fb-8e4d08b629fd.png)
![2](https://cloud.githubusercontent.com/assets/12186301/17974266/151569d0-6aee-11e6-96ad-9b835ce37189.png)

I am using Freedoom  0.10.1, with Odamex engine.

**Comment by Voros2** [comment]
What's your compatibility level?

I have to replay that level again, and see on which compatibility level causes this (I just blaze through the levels, so I don't remember much :P)

**Comment by Voros2** [comment]
Alright, I checked it out on PrBoom+ and GZDoom. Works fine.

**Comment by senpay** [comment]
Hello,

Thanks for help! I'm using Odamex v0.7.0 and it seems not to have compatibility level settings, I think it is supposed to be as close as "Vanilla Doom" as possible.
Maybe this is what causing an issue..

**Comment by Voros2** [comment]
Probably. You should report this at Odamex's website, see what they have to say.
In the mean time use another source port.

**Comment by senpay** [comment]
Ok, thank you, will try to follow this thing with Odamex

**Comment by chungy** [comment]
This seems to have been fixed since reported. thanks
