### ISSUE TITLE
Fix the sprite with the flying candles

### ISSUE THREAD

**Issue by AXDOOMER** [freedoom/freedoom#293]
POL3A0 and POL3B0
![doom84](https://cloud.githubusercontent.com/assets/6194072/18457545/c15c063a-7927-11e6-91d2-a08bf28baabf.png)

This sprite has candles that are above others, so much that even if it is looked upon from above, the candles on the sides still seem to be higher than the two others at the center.

![anigif](https://cloud.githubusercontent.com/assets/6194072/18457977/311becd0-792b-11e6-89e1-adbc53882315.gif)

**Comment by AXDOOMER** [comment]
Made a fix:
![anigif](https://cloud.githubusercontent.com/assets/6194072/18460364/d7bae9ca-793e-11e6-8fa3-120c80098581.gif)

PNG + GIF files: http://www.mediafire.com/download/wwo8t9dzy7oyjcd/POL3A0_POL3B0.zip
![pol3a0](https://cloud.githubusercontent.com/assets/6194072/18460373/e95501b6-793e-11e6-972f-79b044ce8ea3.png)
![pol3b0](https://cloud.githubusercontent.com/assets/6194072/18460374/e95751d2-793e-11e6-9b7e-edf028a97bfe.png)

**Comment by Voros2** [comment]
Submit it!

**Comment by AXDOOMER** [comment]
I made a pull request, it should be good.
