### ISSUE TITLE
Remove F: lines from CREDITS

### ISSUE THREAD

**Issue by fragglet** [freedoom/freedoom#299]
This line is supposed to be the "Freedoom name" - the name previously used for subdirectories that stored contributions by contributor. Now we've abolished these, the F: fields are redundant. We should just get rid of them, but make sure that everyone has an S: line (screen name) or N: (real name).

We should also properly document the format of the CREDITS file.

**Comment by Voros2** [comment]
I'll do it. But first, what kind of format?

**Comment by Voros2** [comment]
Should I also include FreeDM's information?

**Comment by fragglet** [comment]
Needs to be the same as it currently is, but every line starting with F: should be removed. But we should make sure every contributor has either S: or N: or both.

**Comment by Voros2** [comment]
Just that? No "level by X", "music by X" etc? 

Alright.
