### ISSUE TITLE
DPHOOF and DPMETAL aren't included in the phase 1 iwad

### ISSUE THREAD

**Issue by uhbooh** [freedoom/freedoom#300]
These two sounds are mistakenly considered doom 2 only in the buildcfg file.

**Comment by Voros2** [comment]
Just to be clear, HOOF is for the Cyberdemon/Assault Tripod right? I can hear it in Phase 1.

**Comment by uhbooh** [comment]
You're hearing DShoof/metal, i was referring to the pc speaker sounds DPhoof/metal.
