### ISSUE TITLE
Upload build artifacts from Travis

### ISSUE THREAD

**Issue by fragglet** [freedoom/freedoom#301]
We now have travis-ci builds enabled for pushes and pull requests to Freedoom. We should make use of the ability to upload build artifacts and make the WADs from each build available for download: https://docs.travis-ci.com/user/uploading-artifacts/

**Comment by NickZ** [comment]
unfortunately, travis has been broken by the latest updates. Apparently, you can use docker to get packages that aren't in the repositories into the build environment, but I have no idea how to do this.
