### ISSUE TITLE
Stuck in MAP05

### ISSUE THREAD

**Issue by sviscapi** [freedoom/freedoom#304]
Hi,

I managed to get stuck in some narrow passage in MAP05. I'm attaching a saved game for your convenience:

[map05.zip](https://github.com/freedoom/freedoom/files/491791/map05.zip)

Walk to the end of that passage, and you should get stuck too. I had to use "idclip" to unstuck that poor Freedoom guy :)

Environment: Odamex 0.7.0 (SVN revision 5471) Open Pandora port (GNU/Linux ARM).

http://repo.openpandora.org/?page=detail&app=odamex-magicsam

Freedoom Phase 2 (snapshot):

http://freedoom.soulsphere.org/downloads/freedoom-0.10-228-g3adc2c9.zip
Commit: 8c65478379b04bef1552e80ef25df1914f972e45

Cheers, Magic Sam from the Open Pandora Community

**Comment by Voros2** [comment]
A screenshot is useful than a saved game. A demo is more useful.

**Comment by sviscapi** [comment]
@Voros2 : here you go

[map05_screenshots.tar.gz](https://github.com/freedoom/freedoom/files/501495/map05_screenshots.tar.gz)

**Comment by sviscapi** [comment]
@Voros2 : and here is a vanilla demo (latest phase 2 snapshot, ie commit 1379e8cff6ba62ae89ae7d8e3d36cda2bbb8f023)

[map05_demo.tar.gz](https://github.com/freedoom/freedoom/files/503521/map05_demo.tar.gz)

**Comment by Voros2** [comment]
Ok, I see the problem. It can be fixed by either making that area inaccessible (using an impassible linedef) or making it larger so that the player doesn't get stuck in it.

In case people don't know, it's in the part where the minigun is. Well, on the right side of this area.
