### ISSUE TITLE
Is e1m7 completable ?

### ISSUE THREAD

**Issue by sviscapi** [freedoom/freedoom#311]
Hi,

I'm stuck in Phase 1 e1m7 (commit 1379e8cff6ba62ae89ae7d8e3d36cda2bbb8f023) with Odamex 0.7 SVN 5471 (Open Pandora port (GNU/Linux ARM)). I think there is a door under "water" which just doesn't want to open.

Here is a saved game:

[e1m7.tar.gz](https://github.com/freedoom/freedoom/files/504923/e1m7.tar.gz)

Please let me know whether this a Freedoom or an Odamex bug.

Cheers, Magic Sam from the Open Pandora Community

**Comment by Voros2** [comment]
What's wrong with screenshots?

**Comment by sviscapi** [comment]
@Voros2 : here is the screenshot

![odamex_solo_20161002_170450](https://cloud.githubusercontent.com/assets/5636076/19021473/9ed65534-88c2-11e6-9ada-b8115b8d2971.png)

**Comment by Voros2** [comment]
[mp17.zip](https://github.com/freedoom/freedoom/files/505060/mp17.zip)
Tbh, this is my first try. But as you can see, you can finish it.

**Comment by sviscapi** [comment]
@Voros2 : since the map can be completed, I close this ticket.

**Comment by Proluiz** [comment]
this door actualy is just a generic starting door, much wad use it in middle of map to simulate other entrances to the map, but its to simulate a abandoned stating area or something like it, bit hard to me explain too...
