### ISSUE TITLE
Is MAP08 completable ?

### ISSUE THREAD

**Issue by sviscapi** [freedoom/freedoom#312]
Hi,

Same setup as in issue #311. This time I'm stuck in Phase 2 MAP08: the exit door remains blocked by steel bars, even after collecting all the keys and switching all the switches (AFAIK).

I'm attaching a screenshot and a saved game: 

[map08.tar.gz](https://github.com/freedoom/freedoom/files/504928/map08.tar.gz)

As always, please let me know whether this is a Freedoom or an Odamex bug.

Cheers, Magic Sam from the Open Pandora community

**Comment by Voros2** [comment]
Map08 is completable. 

Most likely its a problem related to Odamex.

And what's wrong with attaching screenshots as normal picture files? I want to see the problem in my browser.

**Comment by sviscapi** [comment]
@Voros2 : here is the screenshot

![odamex_solo_20161001_111508](https://cloud.githubusercontent.com/assets/5636076/19021454/e46ee9f4-88c1-11e6-9f3e-c8a4a3407a1b.png)

**Comment by Voros2** [comment]
Yeah, you forgot to flick one more switch.

**Comment by Voros2** [comment]
[mp08.zip](https://github.com/freedoom/freedoom/files/505057/mp08.zip)
Here's a demo. Recorded in prboom+

**Comment by sviscapi** [comment]
@Voros2 : since this map can be completed, I'm closing this ticket.

**Comment by Proluiz** [comment]
this map can be completed in any port aside from vannila (intant crash due line ouverlaps) and odamex (due incomplete special lines "boom" support)
