### ISSUE TITLE
WALL78_1 is a modified Doom 2 texture

### ISSUE THREAD

**Issue by fragglet** [freedoom/freedoom#321]
2d1c7857f3a0158a5a430ad24d2b74b266ebcda4 changed WALL78_1 but @Talon1024 has pointed out that this is a modified Doom 2 texture. 

![redwall](https://cloud.githubusercontent.com/assets/6550500/19503964/20a27f6a-9585-11e6-9316-66f373936e1f.png)![aa8mm1a](https://cloud.githubusercontent.com/assets/6550500/19503983/2f6a430c-9585-11e6-89ac-eacd59b7ad61.png)![wall78_1](https://cloud.githubusercontent.com/assets/6550500/19504135/fae0b4a8-9585-11e6-9fe7-6d190e5802af.gif)

We should revert this change and also audit other recent changes to ensure nothing else has slipped through the net.

**Comment by chungy** [comment]
I've force-pushed a commit that removes the offending file. Leaving the issue open for further auditing.

**Comment by Proluiz** [comment]
that redwall made by me is only a tiled version of the freedoom red flat nothing more than it... but i think its a better placeholder for the actual red wall

**Comment by AXDOOMER** [comment]
I added randomization to your texture so it doesn't look like tiles. 

![fae0b4a8-9585-11e6-9fe7-6d190e5802af](https://cloud.githubusercontent.com/assets/6194072/19570064/4d630460-96c6-11e6-99e2-465c473bc473.gif)

**Comment by Proluiz** [comment]
tileable textures are texture capable of be used in wall wider and higher than 128x128 whitout looking odd, i dont tested this textures but i mean "tileable" something of still look good in high walls.

**Comment by Voros2** [comment]
What's wrong with the current wall78_1?

**Comment by Talon1024** [comment]
It's very ugly. In addition, it doesn't work well with flat5_3.

**Comment by Talon1024** [comment]
I've been working on new replacements for both WALL78_1 and FLAT5_3.
![wall78_1](https://cloud.githubusercontent.com/assets/6550500/20024320/43f1c4aa-a2bc-11e6-9983-c918a7726458.png)
![flat5_3](https://cloud.githubusercontent.com/assets/6550500/20024321/456b8456-a2bc-11e6-8348-7f599aada962.png)

**Comment by Voros2** [comment]
Those textures are licensed under GPL.

**Comment by Talon1024** [comment]
I guess that means I can't use them. Oh, well. How about these:
![flat5_3](https://cloud.githubusercontent.com/assets/6550500/20120998/3df5eb52-a5dd-11e6-9478-e7f439753f83.png)
![wall78_1](https://cloud.githubusercontent.com/assets/6550500/20120999/3df61a8c-a5dd-11e6-8ffc-4b080107e86f.png)
These are based on textures from [this pack](http://opengameart.org/content/seamless-terrain-and-concrete-textures), which is licensed under CC0/Public Domain.

**Comment by Voros2** [comment]
Looks good. Why not submit them?

**Comment by fragglet** [comment]
Resolved in 9d74c8402851b8532fdcc7a43ac4e9a38010164c.
