### ISSUE TITLE
MAP20 HoM

### ISSUE THREAD

**Issue by Lyberta** [freedoom/freedoom#322]
After you defeat cyberdemon and go through the red door to the lift, the ceiling has Hall of Mirrors effect.

**Comment by Voros2** [comment]
Screenshot? I don't understand exactly WHERE you're talking about.

**Comment by FaTony** [comment]
It's the lift which has a very sophisticated platform which looks like a bunch of tiny metal diagonal beams. There is only 1 lift like that in the entire game.

**Comment by Voros2** [comment]
Gonna have to look at it with freelook. What port do you use for playing Doom?
C4M8 also a ceiling HOM, in OpenGL mode though.

**Comment by FaTony** [comment]
I've used PrBoom+ in OpenGL mode.

**Comment by Voros2** [comment]
I heard in the past that PrBoom+'s OpenGL code is not so good. Of course i could be wrong.

**Comment by Voros2** [comment]
I took a look and i didn't find any HOMs.
Maybe you should give a screenshot to see how it looks from your side

**Comment by chungy** [comment]
This map's been updated a couple times and I believe the issue has been resolved. Reopen if otherwise.

**Comment by Voros2** [comment]
TBQH, I never found the HOM myself.
