### ISSUE TITLE
C1M9 Few Zombies are just Blind and deaf.

### ISSUE THREAD

**Issue by Proluiz** [freedoom/freedoom#331]
Possible a rejects lmp issue, few zombies on the 2nd sector after the begin dont react in middle of the "war" while i'm killing the other shotunners around them they just stand there and only react when i get really to close of them.

Note: Normal deaf monsters still react if you shot from behind them. (aiming or not to them)

**Comment by Voros2** [comment]
Is this confirmed? I haven't found any problem like this on C1M9.

**Comment by Proluiz** [comment]
i'll try run another test soon this night so.

**Comment by Proluiz** [comment]
from where i've noticed this glitch it's not happening anymore, seens like it was fixed.
