### ISSUE TITLE
freedoom1: Blue passthrough texture on C1M2

### ISSUE THREAD

**Issue by AXDOOMER** [freedoom/freedoom#333]
There is a huge blue texture in the way on C1M2. You can still walk through. It looks weird and may be due to a recent texture change. It's on the east side of the map and there are two of them. 

BTW, I have played C1M2, C1M2, C1M3, C2M1 and C2M2. These levels are great!

Sorry I couldn't resize the screenshot. 
![screenshot_1105191642](https://cloud.githubusercontent.com/assets/6194072/20034280/0eaa957a-a3b0-11e6-8df9-bb9fd3880505.png)

**Comment by chungy** [comment]
3da56a1ab65785f9a63895a961fe684dfd6d13e0 changed this to be an opaque wall. Not an error, but it looks like it.

As an aside, you may really want to update your ZDoom. 2.8.1 is the latest, released this year :p

**Comment by AXDOOMER** [comment]
> you may really want to update your ZDoom

This is Tiny Core and the latest ZDoom is not available. GCC is broken and won't build anything. Also, I'd have to port it, because not every program is capable to run on this distro. I'm considering to port Chocolate-Doom, but I'd have to remove networking and sound support. Still, GCC is broken, so I can't do anything much. I was just on this distro for fun and I'm not doing anything serious with it.
