### ISSUE TITLE
Are the sprites and sound assets free to use commercially in other projects?

### ISSUE THREAD

**Issue by darie2808** [freedoom/freedoom#335]
Hi everyone,

I am working on a VR shooter game and was wondering if it is OK to use your assets commercially ? 

I read your licence but I am still not sure.

Thank you in advance,
Darie

**Comment by AXDOOMER** [comment]
> Due to the extremely minimal restrictions of BSD-style licenses, software released under such licenses can be freely modified and used in proprietary (i.e., commercial) software for which the source code is kept secret.

Source: http://www.linfo.org/bsdlicense.html

Google is your friend.

**Comment by fragglet** [comment]
Hi! Freedoom is licensed under the BSD license. You can use Freedoom's assets but you must credit the project and include a copy of the license.

**Comment by AXDOOMER** [comment]
> You can use Freedoom's assets but you must credit the project 

Where does it state that in the in the license?

**Comment by fragglet** [comment]
It's implied by the first clause:

    * Redistributions of source code must retain the above copyright 
      notice, this list of conditions and the following disclaimer.
