### ISSUE TITLE
Am I allowed to use some of the Freedoom music in my game?

### ISSUE THREAD

**Issue by ScooT99** [freedoom/freedoom#339]

**Comment by chungy** [comment]
Yes, see the COPYING file. You'll basically just have to include the contents of that file to maintain credit back to the Freedoom project.

**Comment by ScooT99** [comment]
What do you mean? Do I have to include the file itself?

**Comment by chungy** [comment]
Either the file or a larger file containing the credits and copyright of all your resources.
