### ISSUE TITLE
Death inside the door while it is open may cause HOM

### ISSUE THREAD

**Issue by stas730** [freedoom/freedoom#346]
Bug: Death inside the door while it is open may cause HOM
I saw this bug in one demo. I'm used "TNTHOM" cheat code because I'm using PrBoom-Plus and saw HOM. It was worked when I tried it.

**Comment by Voros2** [comment]
I can't explain it in technical details, but it's unavoidable. The demos get replaced anyway with new versions and if a player dies underneath a door, bad luck.

**Comment by AXDOOMER** [comment]
Every Doom engine does this. You'd need an engine where you can set the HOM color to black.

**Comment by fragglet** [comment]
Thanks for the report, but this isn't a Freedoom bug.
