### ISSUE TITLE
Status bar number have a huge shadow behind them

### ISSUE THREAD

**Issue by AXDOOMER** [freedoom/freedoom#356]
![doom85](https://cloud.githubusercontent.com/assets/6194072/22095342/01131b14-dde2-11e6-8a6c-b4afc3f491a4.png)

It's easier to notice behind the yellow numbers over "arms". The number 2 is fine, but other numbers have a square shadow that covers all the background of the number.

The huge shadow is not there when the number are not lighted up (gray instead of yellow). In this case, the shadows are correct. Start a new game and compare the shadow after you enter IDKFA to see the difference. 

It's harder to see on the right,, because the status bar on the background is already very dark.

**Comment by chungy** [comment]
I'm not sure what the problem is. I'm suspecting an engine bug. Shows up in Chocolate/Crispy, but not PrBoom :/

Using Doom itself, shows some weird artifacts too, but it's better hidden. Maybe we should just changes the background to blend better with the shadows.
