### ISSUE TITLE
How to see secrets at night.

### ISSUE THREAD

**Issue by NeverMine17** [freedoom/freedoom#359]
So when I was playing doom, I find that with a flash of a bullet you can see secret doors. Try to do that in front of the secret door and in places where there is bad lighting.

**Comment by Voros2** [comment]
Sounds more like a Doom mapping tip than a Freedoom bug.

**Comment by NeverMine17** [comment]
I thought that you might fix it

**Comment by Voros2** [comment]
Fix what? You have to be more clear than that.

**Comment by NeverMine17** [comment]
Maps

**Comment by Voros2** [comment]
I'm sorry, what maps? All 67 maps? What secret door? Which map?

Secrets are secrets. So if players find them, they find them. That's the point.

**Comment by teamgenten** [comment]
Muzzle flash is a feature, not a bug. XD
