### ISSUE TITLE
Plutonia's A-BROWN4 is misaligned.

### ISSUE THREAD

**Issue by jewellds** [freedoom/freedoom#367]
The Plutonia texture A-BROWN4 uses a frame from the boss cube as a decorative skull. However, because our BOSFA0 is larger than Doom's, it appears off-centred.

The obvious solution would be to change the coordinates for BOSFA0, but I don't know if this would cause compatibility problems so I opened this issue.

Left - Freedoom's version showing the misaligned skull. Right - Plutonia's for comparison.
![brown1freedoom](https://cloud.githubusercontent.com/assets/6622575/22858811/2194a542-f0c0-11e6-96d4-2cdc19c89c2c.PNG) ![brown4plutonia](https://cloud.githubusercontent.com/assets/6622575/22858812/21a87162-f0c0-11e6-8740-86cc41ebdc9d.PNG)

**Comment by chungy** [comment]
This was probably introduced when the cube sprite was changed, we can fix it by offset.
