### ISSUE TITLE
Remove newline escape sequences from C6TEXT

### ISSUE THREAD

**Issue by Voros2** [freedoom/freedoom#373]
There are two newline escape sequences at the end of C6TEXT, so it continues displaying text, such a part of the obituary message for the stealth technospider. I incorporated the fix in the C6TEXT fix pull request, but it seems it wasn't added.

Since the new v0.11 has this bug, maybe a small v0.11.1 would be worthwhile?

**Comment by chungy** [comment]
Thanks, this is fixed. Indeed, if/when we do a 0.11.1, this would be one of the fixes.
