### ISSUE TITLE
C3M1 uses old MIDI track

### ISSUE THREAD

**Issue by Voros2** [freedoom/freedoom#375]
The old C3M1 track is used for map22 as d_map22.mus. How it replaced Blueworrior's C3M1 is unknown to me, but please replace it with this: http://www.geocities.ws/c/a/catodemos/freedoom/blueworrior/D_E3M1.mid

**Comment by Voros2** [comment]
This should be present for a v0.11.1 bugfix release.

**Comment by chungy** [comment]
This is the same track? It's also the same one that you had submitted in August, in 3c4fba1cb85dd72de4f85e2eb4690099fca63b1b

I'm quite confused on what your intent is...

**Comment by Voros2** [comment]
Looks like I confused the filenames that time and uploaded the wrong track. Why I didn't notice back then, not sure. Well, c3m1 should've been replaced with the new track given above. My bad.

**Comment by chungy** [comment]
It's still the same track though, so that link is basically useless.

**Comment by Voros2** [comment]
That explains a lot. Now that I think about it, I had never heard the old C3M1 track. Its a long story not worth mentioning. Closing this.
