### ISSUE TITLE
Various problems with current release.

### ISSUE THREAD

**Issue by James-T-Oudvoure** [freedoom/freedoom#386]
In the most recent version (V0.11.1), all endtexts have been replaced with the doom endtexts, all monster obituaries have been replaced with doom obituaries, all level names (whether on the automap or console) have the last letter chopped off, all item pickup texts have the last punctuation mark chopped off, and the names at the end of the monster role call have the last letter chopped off.

These problems occur with both Freedoom: Phase 1 and Phase 2.

There's probably more problems than these, but they're the most obvious ones that I could see.

**Comment by fragglet** [comment]
What source port are you using?

**Comment by Voros2** [comment]
Works for me in Chocolate Doom and PrBoom-Plus. You're not using some obscure source port that doesn't handle DeHacked properly, are you?
Similarly, I had a small issue with PrBoom-Plus where C6TEXT was replaced with Doom's C6TEXT. It was probably a random bug caused in very exact conditions.

Anyways, it seems more like the port your running on has some issues with processing DeHacked if you ask me.

**Comment by James-T-Oudvoure** [comment]
No, I'm just using GZDoom.

**Comment by James-T-Oudvoure** [comment]
Well, I tried playing the maps on Zandronum (of all possible engines), and it works there.

Since the last time I played GZDoom was before I last updated, I think it just might be a bug or something. I'll try updating again and see what happens.

**Comment by James-T-Oudvoure** [comment]
Well, it works in the most recent GZDoom dev build, false alarm I guess.
