### ISSUE TITLE
[Suggestion] Prevent doubling of Freedoom logo

### ISSUE THREAD

**Issue by JNechaevsky** [freedoom/freedoom#388]
I would like to explain my aesthetic suggestion of how to prevent doubling of Freedoom logo.
![Doubling](http://i.imgur.com/CiCXZrB.png)

First of all, I recommending to make M_DOOM offsets logically centered, like on this mockup:

![](http://i.imgur.com/WtbR35u.png)
(these offsets for M_DOOM: 13 / -16)

Next, Freedoom logo on TITLEPIC must have similar coordinates, this will prevent doubling.
If everything will be done right, result will be like this:
![](http://jnechaevsky.users.sourceforge.net/files/animated.gif)

In case of necessity, demo wad may be downloaded here: 
http://jnechaevsky.users.sourceforge.net/files/centered.wad

**Comment by Voros2** [comment]
Ahh yes, I wanted to implement that, but kept forgetting too. There are two ways to do this:
1- Changing the offsets of M_DOOM in the WAD, via buildcfg.txt
2- Changing the XY coordinates of the M_DOOM for the TITLEPIC, via Makefile 

Personally, I would like to edit the Makefile rather than buildcfg.txt, but my knowledge on Python is too low. Plus, I wouldn't be able to test it because of my hardware limitations. 

I'm sure chungy/fraggle will look into this soon.

**Comment by jmtd** [comment]
This is the relevant line to change in create_caption (which is a shell script)
https://github.com/freedoom/freedoom/blob/master/graphics/titlepic/create_caption#L35

**Comment by Voros2** [comment]
Interesting, but I don't understand how the image location can be at -6,2 and with a size of 0,0.

**Comment by jmtd** [comment]
That's arguments to imagemagick's "convert" tool. The `-draw` stuff is documented here http://www.imagemagick.org/script/command-line-options.php#draw

you can ignore 0,0 for w,h which just means "image's original w,h"

yes -6,2 is weird. I think this must be related to the other options passed to `convert`, such as `-gravity north` which I guess sets the drawing location to be centered at the top, so -6,2 pulls the logo 6 pixels to the left and 2 pixels down.

Here's the docs for -gravity http://www.imagemagick.org/script/command-line-options.php#gravity
Clearer (IMHO) would be either using `-gravity undefined` and an exact pixel offset for the logo, or re-ordering the arguments to `convert` so the logo is first, before any `-gravity` is supplied.
