### ISSUE TITLE
SLAD2 to SALD11 animation broken

### ISSUE THREAD

**Issue by AXDOOMER** [freedoom/freedoom#389]
The animation of these textures seem broken. I was trying to fix an issue that I have making my map. I use this texture with the saw and it's not animated in Freedoom unlike TNT. 

This is the texture:
![doom85](https://cloud.githubusercontent.com/assets/6194072/23284112/c42d1470-f9f7-11e6-8c86-de6c78454361.png)

I am using Chocolate-Doom. I have been trying to get the texture to be animated by launching the Freedoom with `-gameversion final`, that doesn't work. 

I have tried `-iwad tnt.wad -file map08/test08.wad -warp 8` and it does animate. 
When I do `-iwad tnt.wad -file map08/test08.wad -warp 8 -merge freedm.wad`, it doesn't. 

I have explained the issue here on Doomworld: https://www.doomworld.com/vb/post/1720682

I have done a quick test map (warp to MAP08)
http://s000.tinyupload.com/index.php?file_id=01038098839934731924

**Comment by NickZ** [comment]
@Talon1024 Can you take a look at this?

**Comment by Talon1024** [comment]
This issue has to do with the way animations work in the Doom engine. Each animation has a pre-defined starting texture and ending texture. Any texture in between those start/end textures is treated as a frame of the animation.

In the days before [ANIMATED](https://zdoom.org/wiki/ANIMATED) and [ANIMDEFS](https://zdoom.org/wiki/ANIMDEFS), hijacking pre-existing hardcoded animations was the only way to create new ones.

Both the TNT: Evilution and Plutonia IWADS hijack a few animations to replace them with other animations. For example, Plutonia hijacks the DBRAIN animation for its MC animation, and the FIREBLU animation for its AROCK animation.

By that, I mean the Plutonia IWAD puts the MC animation frames (MC2-MC19) in between DBRAIN1 and DBRAIN4, and replaces the DBRAIN1 and DBRAIN4 textures with the first and last frames of the MC animation respectively.

Similarly, TNT: Evilution hijacks the SLADRIP1-3 animation for it SLADx animation.

This issue may be solved by doing one of these things:
- Using an ANIMATED or ANIMDEFS lump to add the TNT and Plutonia animations, although this would only work in ports like Boom or ZDoom, and would not work with PWADs meant to be used with the TNT or Plutonia IWADS.
- Building separate PWADs with the "hijacked" TNT and Plutonia texture definitions, although this would be a bit cumbersome.
- Building separate IWADs that include the TNT and Plutonia texture definitions, although this is a very bloated solution.

**Comment by NickZ** [comment]
Ah hah, I was under the impression that it was only some of the animated textures from Final Doom that had this problem, as opposed to all of them. 

>Use an ANIMATED or ANIMDEFS lump to add the TNT and Plutonia animations, although this would only work in ports like Boom or ZDoom, and would not work with PWADs meant to be used with the TNT or Plutonia IWADS, unless said PWAD includes its own texture definitions based on the TNT/Plutonia texture definitions.

To be clear, you mean that this wouldn't work with PWADs that don't include the texture definitions full-stop, or it wouldn't work in Vanilla? If it's the former, it sounds like this wouldn't fix anything, since the PWAD has to include texture definitions regardless. If that's the case, we should close this as wontfix, since we probably won't create seperate PWADs or IWADs for Final Doom.

**Comment by Talon1024** [comment]
The ANIMDEFS/ANIMATED approach wouldn't work with PWADs that don't include the TNT texture definitions. And it definitely won't work in vanilla.

**Comment by NickZ** [comment]
Ok. @AXDOOMER: the best advice I can give you is to add the texture definitions to your PWAD to fix the animation, as we can't do it in Freedoom2 without breaking compatibility with other stuff. I'm closing this as wontfix.

**Comment by Talon1024** [comment]
Now that I think about it, the ANIMDEFS/ANIMATED approach will work in some cases, but not in vanilla.

For example, if a wall uses a SLADx, MCx, AROCKx, etc. texture, the ANIMDEFS/ANIMATED approach can work, but not if that wall uses SLADRIP1, DBRAIN1, or FIREBLU1.

Also, some Freedoom levels use static frames of these animations creatively. For example, Xindage's most recent [C2M1 beta](https://www.doomworld.com/forum/topic/93603-phase-1-ch-2-dev-thread-bonus-map11/?do=findComment&comment=1767410) uses MC7 for hedges in the outdoor area.
