### ISSUE TITLE
C3 secret exit

### ISSUE THREAD

**Issue by JimFlasch** [freedoom/freedoom#401]
Which level in FreeDoom Phase 1 C3 is supposed to have the secret exit to C3M9? In Doom 1 E3, the secret exit is in level E3M6, but C3M6 has just one exit, to E3M7. (I figure the secret exits in Phase 1 should be in the same levels as in Doom 1.)

**Comment by chungy** [comment]
There's supposed to be one in C3M6, but there isn't.

**Comment by JimFlasch** [comment]
Presumably one will be added by next release (and maybe C3M5 too - there's still a placeholder there)?
