### ISSUE TITLE
misaligned button texture in MAP12

### ISSUE THREAD

**Issue by jonathan-gramain** [freedoom/freedoom#405]
Hi,
One of the wall button textures in MAP12 (railroads) is misaligned everywhere it appears in version 0.11 (I think 0.10 was ok).
Thanks otherwise for this awesome level!

![button_texture_misaligned_1](https://cloud.githubusercontent.com/assets/3418241/23447785/1c6ea690-fe02-11e6-83c7-0707f8834114.png)
![button_texture_misaligned_2](https://cloud.githubusercontent.com/assets/3418241/23447786/1c70ec66-fe02-11e6-94bd-da04a50ca94a.png)

**Comment by Voros2** [comment]
It's the only Zok (Zok is the level author) map that suffers from this. Map15 also has misaligned switches.

**Comment by Catoptromancy** [comment]
Those maps are being converted to vanilla, will eventually take care of this.

**Comment by mc776** [comment]
Both of these have been addressed (see my reply to #800) and I think this issue can be closed.
