### ISSUE TITLE
phase2 map12 low performance

### ISSUE THREAD

**Issue by CyberKiller40** [freedoom/freedoom#408]
I am using:
- freedoom 0.11.1
- zandronum 2.1.2 64bit
- brutal doom v20
- opensuse 42.1, intel gpu mesa drivers

In phase 2 in map12 (railroads) after about 3/4 map progress, I had large open spaces opened and in effect performance dropped to a crawl (<5 fps) after another door opened. The zandronum process used a whole cpu core.

I'm putting this issue here because this doesn't happen with any other maps so most probably this is the fault of this specific map. It seems only few doors autoclose on this map, most stay open permanently after opening them.

**Comment by AXDOOMER** [comment]
Are you using software rendering or OpenGL?

**Comment by CyberKiller40** [comment]
Sorry I forgot to say, I use the opengl renderer, trilinear texture filter and radial fog mode (default fog was giving serious artifacts)

**Comment by CyberKiller40** [comment]
I tried the software renderer and though the savegame I made earlier didn't want to load. I skipped to map12 and managed to finish it without much problems. The performance was lower than usual, at the point when the large open spaces were there, but still playable.

I tried that again with opengl, but without brutal doom and it was ok also.

So perhaps this is not so much a Freedoom problem after all. Maybe it's something related to brutal doom, maybe all the bullet shells that are left on the ground. I guess this issue can be closed.

**Comment by Voros2** [comment]
Brutal Doom is infamously well known for many things. The performance issue was so big that the author even made the next version be more hardware-friendly (if you get what I mean). A benchmark video was even uploaded to YouTube by the author to show off the next iteration of Brutal Doom and its performance fixes: https://m.youtube.com/watch?v=Kqf9qKw6pQc

And GZDoom/Zandronum/ZDoom/etc tend to use a lot of power for some reason. This is not a hunch, but a fact. 

The Freedoom project does not involve any programming, only data. If you run into performance problems, it's the port you're running on that's causing the problem, not Freedoom itself.

**Comment by Catoptromancy** [comment]
This map needs converted to vanilla. Will likely solve many performance issues at the same time, after conversion.

Unrelated/semi-related, maybe use a different driver combo. Will help on many other larger maps.

**Comment by Xindage** [comment]
it's supposed to be fixed by 0ea4a09825236a2428b19cf442c8722e73879ef0
