### ISSUE TITLE
Texture changes that break a map's theme (example: FreeDM map04 in this case)

### ISSUE THREAD

**Issue by AXDOOMER** [freedoom/freedoom#409]
Some textures have been replaced with new ones in Freedoom. This sometimes break how a level is supposed to look like. 

#### In the future, I suggest we should be cautious.

This is map04 for example: 
![Uploading Screenshot_Doom_20170306_191715.png…](https://s23.postimg.org/wiarayr9n/Screenshot_Doom_20170306_191715.png)

I can't remember what was the previous texture, but now it looks wrong. 

We should set a list of criteria that we would move toward when replacing textures, so that we avoid breaking the theme of people's map. (unless we put the burden on the map authors)

An example of criteria could be that the texture should look as close as possible to the original.

**Comment by Catoptromancy** [comment]
The original/previous textures were actually the bad ones. Maps affected by these changes should be updated.

**Comment by Proluiz** [comment]
dm04 in rework project already not use this texture anymore

**Comment by fragglet** [comment]
> An example of criteria could be that the texture should look as close as possible to the original.

I'm unsure here if "original" in this context means "the previous version of the texture" or "the version in Doom".

* If the former, I appreciate that it's frustrating when texture changes disrupt levels which depend upon them, but imposing a restrictive rule like this would potentially slow down the project significantly. I'd rather we "move fast and break things" and then fix them up later, than tell people they can't make any significant changes textures for fear of breaking things.

* If the latter, we specifically want the opposite this. Freedoom's material needs to be original and different, not copies of `doom.wad`.

So I don't think any change in policy is needed. But if texture changes do mess up levels we should certainly file them as bugs. In extreme cases we should maybe consider rolling them back, especially in the case of an upcoming release.
