### ISSUE TITLE
Set up deterministic builds

### ISSUE THREAD

**Issue by fragglet** [freedoom/freedoom#41]
Freedoom's build system is not deterministic. The generated IWADs can be subtly different depending on factors like the building system and the current date.

This is important because some ports like ZDaemon use checksums of the WAD files to ensure all players are playing the same game. Debian builds its own Freedoom WADs. Even though the levels are the same (and thus won't desync) it won't be possible for players using the Debian WADs to play against people using the "official" WADs we release on the website.

Factors to address:
- Freedoom's title screen includes the build date. This immediately kills deterministic builds. We should just get rid of this I think.
- The text rendering by ImageMagick seems to differ on different systems. When I built on Debian and Ubuntu I found that subtle differences in text rendering meant that the graphics that used it didn't match (ie. title screens).

**Comment by NickZ** [comment]
Any movement on this issue?

**Comment by chungy** [comment]
Not yet, sadly. I want to focus on getting a 0.10 release as soon as possible, and I will be evaluating issues like this as release-critical for 1.0 (don't take this as a statement of 1.0 following directly after 0.10; but I want to be thinking about that goal more seriously now).

**Comment by NickZ** [comment]
Resolved as of #467
