### ISSUE TITLE
Difficulty suggestion

### ISSUE THREAD

**Issue by ROCKNROLLKID** [freedoom/freedoom#433]
Hello.

As someone who has played Doom since DOS times, one thing that I always hated was that ultra-violence would be too easy and nightmare would be too hard. I thought of a way to maybe solve this. What about making the current nightmare difficulty as a ultra-nightmare and then making a new nightmare difficulty that's as hard as ultra-nightmare, but without respawning monsters.

Either that or it would be nice to maybe do some buffs for ultra-violence so that one is a little harder.

Also, I didn't want to make another ticket to ask this, but is there any ETA when Freedoom campaign (phase 1 and 2, don't really care about FreeDM) would actually be completed?

**Comment by chungy** [comment]
We're not in control of the engine, and specifically targeting vanilla for compatibility. If we targeted an engine like GZDoom, this would be possible, but we don't and it's not. Sorry.

> Also, I didn't want to make another ticket to ask this, but is there any ETA when Freedoom campaign (phase 1 and 2, don't really care about FreeDM) would actually be completed?

No ETAs. :)
