### ISSUE TITLE
Please remove the new annoying death sounds

### ISSUE THREAD

**Issue by AXDOOMER** [freedoom/freedoom#436]
It's really annoying in deathmatch where it's played repetitively. I fail to understand how they are an improvement on the previous death sounds. 

commit: https://github.com/freedoom/freedoom/commit/2246f2d5526702d9cd79d1b6e1c56df0712973c3

**Comment by rjy** [comment]
>I fail to understand how they are an improvement on the previous death sounds

I think there was plenty wrong with the previous death sounds. One was a repeat of one of the zombie deaths, an obvious mistake. The other was the Wilhelm scream, a tired cliché.

**Comment by AXDOOMER** [comment]
Yeah, but now it's even worse. It discourages me from deathmatching in FreeDM.

**Comment by rjy** [comment]
Alexandre-Xavier Labonté-Lamoureux wrote:
>Yeah, but now it's even worse. It discourages me from deathmatching in FreeDM. 

I wouldn't know. If only Odamex were active when I am awake...

It's a pity Freedoom can't use D_EPain (from DoomEd), it's hilarious.
https://github.com/fragglet/DoomEd/blob/master/D_EPain.snd

**Comment by AXDOOMER** [comment]
The previous sound sounded more like somebody who was dying. Who screams at the top of his lungs when he dies? 

https://www.youtube.com/watch?v=nAdniWncWu4

**Comment by NickZ** [comment]
Fixed in #437
