### ISSUE TITLE
Documentation on sprite names?

### ISSUE THREAD

**Issue by VinnyVicious** [freedoom/freedoom#438]
I'm trying to understand why the pistol sprite files are named `pisga0` and `pisgb0`. Is there a documentation somewhere? I'm also curious about the enemies.

**Comment by Voros2** [comment]
Google is your friend.

In all seriousness, pisg is an acronym for "pistol gun" most likely. What your looking for is probably documented extensively on DoomWiki.

**Comment by VinnyVicious** [comment]
https://www.google.com/search?q=freedoom+sprite+names
https://www.google.com/search?q=freedoom+sprite+naming
https://www.google.com/search?q=freedoom+sprite+documentation

Before posting this issue, i've tried. All sprites in the game have some sort of naming standard. I just want to know how to follow that standard in order to create additional content.

**Comment by Voros2** [comment]
Freedoom is essentially Doom with a heavy cosmetic change. Nothing technical is involved. Look up Doom editing and ask questions over at Doomworld/ZDoom/Zandronum/etc Forums. The answers your looking aren't really related to Freedoom itself. And DoomWiki is your friend for Doom related info.

To create additional content, its usually preferred by people to use DECORATE or/and Dehacked. Learn either one of these and you can make extra content easily.

**Comment by teamgenten** [comment]
https://zdoom.org/wiki/sprite

**Comment by Voros2** [comment]
This also isn't related to Freedoom.
