### ISSUE TITLE
Adding more frames to a weapon animation?

### ISSUE THREAD

**Issue by VinnyVicious** [freedoom/freedoom#440]
I'm trying to revamp the pistol, but in order to do that i need more animation frames. How can i do that? Is there a special file name?

**Comment by Calinou** [comment]
I don't think this is possible - Freedoom tries to keep compatibility with conservative source ports such as Crispy Doom or PrBoom+, which usually do not provide a lot of room for graphical improvements.

However, you could probably make a PWAD that adds more frames to the weapon animation, but it won't work in all source ports. It also wouldn't be the default shipped with Freedoom.

**Comment by Voros2** [comment]
You might want to have a look at learning ZDoom's DECORATE language, which can easily make new frames for weapons.
But you can also use Dehacked/Bex, using the extra sprites present in Boom ports. The BlacksOps mod is a smooth Doom weapons mod for Boom-based ports. This should give you a good idea on how to get more frames for your pistol without sacrificing essential frames for a non-ZDoom based port.
