### ISSUE TITLE
MAP05 Blue Passcard issue

### ISSUE THREAD

**Issue by JohnnyTheWolf** [freedoom/freedoom#442]
In Phase II's MAP05, it is possible to grab the Blue Passcard through the bar without lowering it firsthand. It is not that big of a deal, since the switch to do so is in the very next room, but I do not think this is intended.

**Comment by Voros2** [comment]
I can't replicate the bug you've reported. How exactly do I do it? Or was this caused by accidental gliding?

**Comment by JohnnyTheWolf** [comment]
I was able to replicate it myself easily by running into the bar and hugging it.

**Comment by Voros2** [comment]
Can you do it again, and record it as a demo? If you can replicate it again, then it can be considered as a bug rather than a freak accident.

**Comment by JohnnyTheWolf** [comment]
Huh. Weird. I cannot seem able to reproduce the bug a third time.

**Comment by Voros2** [comment]
Fortunately RjY managed to replicate it: https://www.dropbox.com/s/iz1xtqo4hsau438/map03map05-bumps.zip?dl=0

It would be best to not report any map issues atm, as there's a new management going on with maps. Blastfrog is in charge of map01-map11, and updates on progress very scarce. But it has been confirmed that map05 will become map21 (you can find this hellified map05 over at the Freedoom forums, specifically the development thread for map21-map30).

**Comment by Proluiz** [comment]
"Basically, the key is placed close enough for ZDoom or PrBoom+ (non-vanilla compat settings) to pick it up"

Fix: [map05_fix.zip](https://github.com/freedoom/freedoom/files/3577112/map05_fix.zip)
