### ISSUE TITLE
MAP06 100% items

### ISSUE THREAD

**Issue by JohnnyTheWolf** [freedoom/freedoom#444]
Not sure if it is a bug, but I cannot seem to get 100% items on MAP06.

**Comment by Voros2** [comment]
Map06 has been successfully finished 100% on skill 2 and 4. I should do skill 3 but, it should be safe to assume that you can get 100% items overall.

**Comment by JohnnyTheWolf** [comment]
I tried the map twice on skill 4, yet I kept ending up one item short.

I seem not to be alone either: https://www.youtube.com/watch?v=a3cj4KsWgqU

**Comment by JohnnyTheWolf** [comment]
Ah, I think I see the problem: there is a Blue Overdrive sphere above the exit room. However, I have no idea how to get to it without cheating.

**Comment by Voros2** [comment]
I just did 2 100% runs on skill 3 and 4. 

I think the map your talking about is the old map06 (now map18).

**Comment by JohnnyTheWolf** [comment]
The map I am talking about is Gamma Labs, as shown in pagb666's video.

If that is the one, then how did you get the Overdrive sphere without cheating?

**Comment by Voros2** [comment]
Where in the world do you see an overdrive sphere? The old map06 had an inacessible overdrive sphere.

Not to mention that over at Doomworld, a user by the name of Litrivin did a 100%run on map06 on skill 4 with no issues. Litrivin is very thorough with his reportings. And I did a 100% run on skill 3 too.

**Comment by Voros2** [comment]
I just watched the video. This is the old map06, the one with the inaccessible overdrive sphere.

**Comment by JohnnyTheWolf** [comment]
So how can I play the new MAP06? I use build 0.11.2 and the old map06 is the one that gets loaded after MAP05.

**Comment by Voros2** [comment]
Get the git build: http://soulsphere.org/freedoom
