### ISSUE TITLE
E3M4 100%

### ISSUE THREAD

**Issue by ReakutheCrate** [freedoom/freedoom#448]
The trap that lets all the Imps teleport in after picking up the soulsphere is flawed.
The trigger "38 -W1 floor lower to lowest floor" on lines 1432 - 1435, making sector 204 lower to the same height as sector 188, instead of sector 205, this same problem is happening with sector 396.

A height lip may be required for this to work more correctly, or perhaps lowering the sectors with the Imps on them to the same height as sector 188, avoiding this whole problem entirely.

**Comment by sgtcrispy** [comment]
The trap does work as intended. I've retested it on Chocolate, Retro and again on ZDoom and it seems to be working fine. I see no real point in changing the shared sector. /shrug

**Comment by sgtcrispy** [comment]
After a bit more testing I have found that a least one imp doe get stuck in the holding sector. Must be a random occurrence, I never ran into that before. However, I'll get a fix whipped up.

**Comment by NickZ** [comment]
@sgtcrispy any progress on this?

**Comment by Voros2** [comment]
There's no point in editing any of the maps. AD_79 is in control of E3, so it's his decision on what should happen to E3.

**Comment by Voros2** [comment]
(https://www.doomworld.com/forum/topic/95097-freedoom-phase-1-e3m4-refresh/)

**Comment by Proluiz** [comment]
e3m4 is free of this error, but i've noticed a small issue in easy and normal skill with monsters stucks on each other and i fixed it.
[e3m4.zip](https://github.com/freedoom/freedoom/files/3577087/e3m4.zip)
