### ISSUE TITLE
Freedoom phase 1 unbalanced difficulty curve

### ISSUE THREAD

**Issue by ReakutheCrate** [freedoom/freedoom#450]
While playing through phase 1, I came across a bit of a realization as to the difficulty of the maps as I was playing them.
The entirety of episode 1 felt like it was episode 2.
Episode 2 started out feeling like episode 3, while the end felt like episode 1.
Then episode 3 came around, it felt like it kept bouncing back and forth between 2 and 3, along side not being finished, episode 3 was also a vast disappointment map wise.
Episode 4 then was largely uncalled for with what it pulled most of the time, the first map was amazing, then the rest of the episode turned into giant corridore maps.

What I'm getting at, there is a vast disconnect as to the map progression and difficulty curve being presented that's rather offputting, I like Freedoom, however, this disbalance doesn't help my enjoyment of it. Some maps need to be moved around, others redone, and or had some things changed about them, and I'm going to go so far to say that episode 4 direly needs to be rebalanced entirely.

**Comment by Voros2** [comment]
The maps are being redone.

**Comment by ReakutheCrate** [comment]
One thing I neglected to write, there are two maps that feel perfect in their construction, that's both E2M5, and E4M1. Those two maps are the most enjoyable ones, but also the ones with the most open feel.

**Comment by Xindage** [comment]
Closed as stale
