### ISSUE TITLE
E4M2 damaging floor sectors

### ISSUE THREAD

**Issue by JamesS6192** [freedoom/freedoom#451]
Hello! I created an account just to report some issues I located in Freedom v0.11.2 just to support you guys. <3

The issue is simple to fix, but still an issue. I'm unsure if the issue has been reported already (doesn't appear to be judging from the search) but just in case it hasn't:

Sectors 195 and 182 both have sector effect #5 which is the damaging floor effect. They are each adjacent to a slime pit which also possesses the same sector effect. It's not supposed to have this effect.

**Comment by NickZ** [comment]
Thanks James! We'll look into it.

**Comment by NickZ** [comment]
Fixed 'em. Thanks James!
