### ISSUE TITLE
Possible skies

### ISSUE THREAD

**Issue by Voros2** [freedoom/freedoom#460]
(https://www.dropbox.com/s/bqiog8k3oivpigz/RSKY1.WAD?dl=1)
If you think it's cool, I'll provide the creator's username and email (he only shared that much of info with me) here.

**Comment by NickZ** [comment]
ooh yeah, that looks good. Make sure to get his written permission that it can be committed to freedoom under the license and all that.

**Comment by Voros2** [comment]
Oh, I did that long ago :P everything's legit and the author is willing to contribute.
S: Eradrop
E: samurai00020@walla.com

**Comment by NickZ** [comment]
Sounds good, make the PR!

**Comment by Voros2** [comment]
Mind doing it for me? My hands are tied behind my back atm if you get what I mean.

Also: https://www.dropbox.com/s/yfh6ycoszn6stb9/SKY3.WAD?dl=1 (same guy)

**Comment by NickZ** [comment]
I'll do rsky1, but I think the current rsky3 looks better.

**Comment by Voros2** [comment]
That's actually SKY3 of Doom1.

**Comment by NickZ** [comment]
ahhhh, ok. I dunno, after testing, the brown mountains kind of clash with the mostly red theme of episode 3.

**Comment by Voros2** [comment]
Right. I initially thought this too, but that red sky is just too good. Feel free to do whatever you want.

**Comment by Voros2** [comment]
And another https://www.dropbox.com/s/g0qtivv8vaolrka/RSKY3.WAD?dl=1 but I'm not entirely happy with it.

**Comment by Voros2** [comment]
Reopened for that one last sky recommendation (which actually doesn't look that bad as I remember it).

**Comment by NickZ** [comment]
Yeah, after testing, I think I like it better than the pink mountains. I'll add this.

**Comment by NickZ** [comment]
Fixed in d3ecfd865577bdf834ee3464632d06b04bde7bda
