### ISSUE TITLE
E2M4 - stuck

### ISSUE THREAD

**Issue by Zuccace** [freedoom/freedoom#476]
Soo... I managed to jump (actually just run, so no actual jumping) [over the rightmost pole](http://i.imgur.com/dRCWVjx.png) to get the powerup. I ran from the plat where the crosshair points.

This was played on odamex 0.7.0 and freedoom git.
v0.11.3
git commit d3038fad309789c3add9a6ec01367794f87bef10

**Comment by rjy** [comment]
Ilja Sara wrote:
>Soo... I managed to jump (actually just run, so no actual jumping)
>[over the rightmost pole](http://i.imgur.com/dRCWVjx.png) to get the
>powerup. I ran from the plat where the crosshair points.

I've done this too, .lmp.gz attached (unless github strips it)

-- 
https://rjy.org.uk/

**Comment by rjy** [comment]
>unless github strips it
not surprising really

http://s000.tinyupload.com/?file_id=02618522952955440092

-- 
https://rjy.org.uk/
