### ISSUE TITLE
Use separate TEXTURE lumps instead

### ISSUE THREAD

**Issue by Voros2** [freedoom/freedoom#477]
As of https://github.com/Doom-Utils/deutex/commit/dffa953964e848519afc527b10b8b057f8a357d5 TEXTURE lumps can have different names other than TEXUREx. How about halting the usage of build-textures and stick with three separate TEXTURE lumps?

**Comment by chungy** [comment]
I don't think it's a great idea. We gain quite a lot from not having a bunch of work duplicated in multiple files.

**Comment by fragglet** [comment]
Please note that the build-textures script also serves an additional purpose: it generates TEXTUREx and PNAMES lumps in a way that is compatible with the original IWADs (see #1 and 82d90f8e8a6bcee9c88cc). Otherwise certain PWADs won't play correctly with Freedoom.
