### ISSUE TITLE
Some sprites have speckles when playing with D2TWID

### ISSUE THREAD

**Issue by fragglet** [freedoom/freedoom#48]
Screenshot: http://i.imgur.com/9U7X25O.png

I get this when playing with D2TWID, but only with Chocolate Doom. When using PrBoom+ they don't appear. Only appears on some sprite frames; it's particularly noticeable on the Baron / Spider sprites. 

D2TWID has replacement PLAYPAL / COLORMAP lumps so that may be to blame.

**Comment by NickZ** [comment]
closed with #214

**Comment by chungy** [comment]
Still an issue, actually.

**Comment by mc776** [comment]
Are there any sprites left that still do this?

**Comment by mc776** [comment]
Link for convenience https://www.doomworld.com/idgames/levels/doom2/megawads/d2twid

**Comment by mc776** [comment]
I'm also getting this with PrBoom+.

Is this only one colour in the palette or are there more?

**Comment by mc776** [comment]
Why I think the only affected thing is colour 255:

PrBoom+
![456](https://user-images.githubusercontent.com/24984517/236759318-3c743405-0df0-4c85-a90f-47add412a347.png)

Chocolate (btw how do you get DeuTex -as to use a specific IWAD? The easiest way to check these is with a dead octaminator but I'm stuck with release)
![123](https://user-images.githubusercontent.com/24984517/236759321-e441e5c6-99be-498f-80b2-86220f491676.png)

By the way I did actually test #967 and as far as I am at all able to tell there are no cyan speckles anywhere.

**Comment by mc776** [comment]
I think I linked this issue without understanding what linking does. Reopening until we have an agreement on a proposed permanent workaround.

**Comment by mc776** [comment]
It doesn't seem like any sprites have this problem anymore, not even any of the recent stuff (checked fist, backpack and bronzes as the highest-risk items).

I think we can close this for now and re-open it or post a new issue (or even just a PR since we all know what to look for now) if it ever comes back up again.
