### ISSUE TITLE
Add vanilla map15?

### ISSUE THREAD

**Issue by Voros2** [freedoom/freedoom#483]
Catoptromancy edited map15 to conform to vanilla limitations. Afterwards, Graf Zahl edited it to make the progression more fluid and less cryptic. 

Map can be found here: http://www.geocities.ws/voros/stuff/map15_gz2.wad

I'm aware of the czars, but consider adding it the repo?

Note: the nodes may need to be rebuilt

**Comment by NickZ** [comment]
Fixed in https://github.com/Talon1024/freedoom/commit/42c5a9952d2a398fa81ada603f53dfd01038ce4a

**Comment by NickZ** [comment]
@Talon1024 Can you please PR that level?

**Comment by Talon1024** [comment]
I thought I added this level a long time ago, in #495.

**Comment by NickZ** [comment]
So you did, my mistake.
