### ISSUE TITLE
wadinfo-builder.py can probably be removed

### ISSUE THREAD

**Issue by fragglet** [freedoom/freedoom#485]
This script was put in place a long time ago when Freedoom was very incomplete and there were a lot of missing resources. Its main purpose is to point missing resources at "dummy" resource files (you'll notice that each directory contains a `dummy.png` or `dummy.wav`, `dummy.mid`, etc.). Nowadays we have a complete set of resources so I doubt it's necessary any longer. If it is still masking some missing resources it would be simpler to just manually edit `buildcfg.txt` to point to dummy until the resource is submitted.

Doing this should simplify the build quite a bit; the diagram in `BUILD-SYSTEM.adoc` should become one step shorter.

**Comment by fragglet** [comment]
A quick survey of the dummy references being produced by wadinfo-builder.py:

Missing levels:
```
wadinfo_phase1.txt:e3m5 = dummy
wadinfo_phase2.txt:map26 = dummy
```
Missing sound effects:
```
wadinfo_phase2.txt:dspedth = dummy
wadinfo_phase2.txt:dsbspwlk = dummy
wadinfo_phase2.txt:dsflame = dummy
wadinfo_phase2.txt:dsflamst = dummy
```
These ones are weird. It seems that some textures are embedding sprites as patches, and as a result they get included in the generates [patches] list.
```
wadinfo_phase2.txt:; bosfa0 - no dummy
wadinfo_phase2.txt:; tfogf0 - no dummy
wadinfo_phase2.txt:; tfogi0 - no dummy
```

**Comment by fragglet** [comment]
The rogue sprites-as-patches are actually from Final Doom textures:

* Plutonia's `A-BROWN4` texture embeds `BOSFA0` (fancy spawn cube on door front).
* TNT's `SLAD10` and `SLAD11` textures embed `TFOGF0` and `TFOGI0` (gives a "sparkle" effect on the UAC logo; I'm not sure what this even looks like in Freedoom).

**Comment by Voros2** [comment]
Since we're on the subject of removing a script, I have always wondered if the music-duplicates script is needed anymore. It certainly isn't used anymore and there're no more duplicate tracks other than a 1-3 being shared by FreeDM and Phase 2 (which can be replaced with the pending music submissions).
