### ISSUE TITLE
Box of Shotgun Shells sprite looks like a portion of fries from McDonalds

### ISSUE THREAD

**Issue by fragglet** [freedoom/freedoom#486]
Can we change this? Reminds me of a McDonalds takeaway every time I see it.

![Box of Shotgun Shells](https://i.imgur.com/qzZvW8v.png) ![McDonalds fries](https://i.imgur.com/ey4JAJk.png)

**Comment by chungy** [comment]
Great. Now I'm not going to unsee it.

**Comment by Voros2** [comment]
Thank you for engraving this similarity in my head. Now I can't see the same way ever again.

Why not just revert back to the old sprite?

**Comment by haleyjd** [comment]
I'm lovin' it ;)

**Comment by NickZ** [comment]
fixed in #538
