### ISSUE TITLE
wad2image scripts do not exist

### ISSUE THREAD

**Issue by Talon1024** [freedoom/freedoom#493]
Although the wad2image targets are in the makefile, the scripts do not exist.
`$make wad-image
make: command: Command not found
Generating images for WADs in "levels".
scripts/wad2image/bin/wad2image.py      --out-dir wad-images    --wad-spath wads,{top-dir}/wads,.,/usr/share/doom,/usr/local/doom  levels/c1m7.wad
/bin/sh: 1: scripts/wad2image/bin/wad2image.py: not found
Makefile:156: recipe for target 'wad-image' failed
make: *** [wad-image] Error 127`

**Comment by rjy** [comment]
Kevin Caccamo wrote:
>Although the wad2image targets are in the makefile, the scripts do not exist.

As I understand it (and please let me know if I have misunderstood),
wad2image is a separate application maintained independently by its
author. It is not part of the Freedoom distribution, and must be
self-installed. The build targets exist simply as a convenience for
users who have the program installed.

-- 
https://rjy.org.uk/

**Comment by Talon1024** [comment]
Thanks for clearing that up.
