### ISSUE TITLE
Suggestion for ending C4TEXT

### ISSUE THREAD

**Issue by JNechaevsky** [freedoom/freedoom#498]
The ending text `C4TEXT` contains three following lines:

> No one will know know who saved them.
> No one will know what happened here.
> No one will ever find you again.

Maybe it will be a good idea to add another one (4th) or replace last one with something like...

> _(And)_ No one will _(never)_ steal/take/encroach your freedom.

Like a playing of words freedoom+freedom. I'm not actually sure which word will fit perfect in terms of beauty, literary and ease of understanding.

**Comment by ElonSatoshi** [comment]
I don't like it. I can't see any way in which Freedoomguy's freedom is encroached by the monsters/aliens he has to mow down.

**Comment by JNechaevsky** [comment]
Nevermind. Done this in my translation project.
