### ISSUE TITLE
E1M8 only secret is useless...

### ISSUE THREAD

**Issue by FredBezies** [freedoom/freedoom#514]
I'm currently playing git from November 18th, 2017 and I noticed the only secret in E1M8 is kinda useless. It gave me energy cells, but in first episode there is no energy cells weapons...

What about an automap?

**Comment by Litrivin** [comment]
C1M6 does contain one secret polaric energy cannon.

**Comment by FredBezies** [comment]
Did not find it. Well, so my bug is invalid. Closing it.
