### ISSUE TITLE
Lots of missing files on compile

### ISSUE THREAD

**Issue by GarethH96** [freedoom/freedoom#516]
Getting a lot of errors about not being able to find files:
[logfile.txt](https://github.com/freedoom/freedoom/files/1497765/logfile.txt)

**Comment by chungy** [comment]
You need to upgrade to [DeuTex 5](https://github.com/Doom-Utils/deutex)

**Comment by GarethH96** [comment]
`$ deutex --version
DeuTex 5.0.0`

**Comment by chungy** [comment]
Are you missing PNG support? You might want to make sure you have libpng ≥ 1.6 installed and then recompile (also, 5.1 is the latest version).

**Comment by GarethH96** [comment]
Got it working now. I installed libpng-dev from the Ubuntu repo and then got the newest version of Deutex from here: https://github.com/Doom-Utils/deutex. Thanks.

**Comment by anorman728** [comment]
I'm having the same issue, with the latest DeuTex and libpng-dev 1.6.34-1ubuntu0.18.04.2.  Would you rather I create a new issue or continue this one?

**Comment by chungy** [comment]
You shouldn't need to install libpng-dev, just install the deutex package.

**Comment by anorman728** [comment]
My DeuTex version should be up-to-date--

> deutex --version
> DeuTex 5.2.1

**Comment by chungy** [comment]
Hrm, assuming you're doing a custom compile then, make sure the `./configure` output in the deutex source tree shows that it finds PNG.

Alternatively, Ubuntu's [own packages](https://packages.ubuntu.com/search?keywords=deutex) should support PNG just fine.

**Comment by anorman728** [comment]
It's looking like that might be the problem-- Part of the output of `./configure` is `checking for PNG... no`.  I'll do some research and come back with what I find.

**Comment by anorman728** [comment]
Scratch that-- On Ubuntu 16.04 it says no, but on 18.04 it says yes.

**Comment by anorman728** [comment]
It's very possible that this is a system setup issue.  Probably not worth looking into right now.  Sorry about that.
