### ISSUE TITLE
C4M8 isn’t 100% vanilla, there are visplane overflows

### ISSUE THREAD

**Issue by ghost** [freedoom/freedoom#521]
C4M8 isn’t 100% vanilla. After the player manages to unlock the final section once and for all, there is at least one location where visplane overflows do happen. I have attached (link 1) one demo recorded with Chocolate Doom. Obviously, the visplane overflows crash Chocolate Doom and abort the demo recording.

I strongly believe that Visplane Explorer cannot detect it (according to its developer, C4M8 was OK, link 2) because it cannot simulate the activation of every linedef. It can simulate the opening of every door and this isn’t exhaustive enough to predict certain visplane overflows.

Link 1: https://www.dropbox.com/s/xqvbhuue3r0mfcu/c4m8.zip?dl=1
Link 2: https://www.doomworld.com/vb/post/1535100

**Comment by NickZ** [comment]
Hmm, that's interesting. Would you be interested in trying to fix it?

**Comment by Litrivin** [comment]
I would do it, but I lack of a desktop computer at this moment.

**Comment by NickZ** [comment]
closed in #536
