### ISSUE TITLE
Map13 and later maps starting from Map17 has visplanes and HOM issues in vanilla Doom 2 engine.

### ISSUE THREAD

**Issue by MakotoIchinose** [freedoom/freedoom#524]
In vanilla Doom engine, Map13 triggers visplane overflow after few steps from the fence, and the same error, along with some HOM glitches happens to the majority of the last maps starting from Map17.
Also Map21 even can't be loaded due to a spawn thingy error: 
`P_SpawnMapThing: Unknown type 4001 at (-96,32)`

Perhaps I'm going crazy by playing and testing Freedoom that perhaps intended for source ports on a 20 years old unmodified vanilla engine, but for some reason I love to slap some PWAD on the vanilla engine.

**Comment by Calinou** [comment]
Note that Freedoom Phase 1 and 2 are not vanilla-compatible (they require a limit-removing source port such as [Crispy Doom](https://www.chocolate-doom.org/wiki/index.php/Crispy_Doom), which behaves closely to the vanilla executable by default), but FreeDM is.

**Comment by AXDOOMER** [comment]
> Note that Freedoom Phase 1 and 2 are not vanilla-compatible – they require a limit-removing source port such as Crispy Doom, which behaves closely to the vanilla executable by default. However, FreeDM is vanilla-compatible.

That's incorrect. Phase 1 and 2 are being remade to be vanilla-compatible.

**Comment by Calinou** [comment]
> That's incorrect. Phase 1 and 2 are being remade to be vanilla-compatible.

I edited it for posterity. :smiley:

**Comment by mc776** [comment]
2018... are any of these issues still outstanding?

**Comment by mc776** [comment]
It's been 5 years with a lot of compat work done on these later maps. I think it's best that we close this and if any specific compatibility issues come up they can be dealt with then.

**Comment by Xindage** [comment]
closed due stall, if it still happens there's a chance of someone bumping in this during the playtests.
