### ISSUE TITLE
Bluetooth mouselook on Android vesion

### ISSUE THREAD

**Issue by fickbowt** [freedoom/freedoom#525]
Are you the devs for all platforms? Because I'd love to see bluetooth mouselook for the android version of Freedoom (praise be to Freedoom and the devs whom work on it). I have a bluetooth keyboard which works fine on the android version - just want mouselook too! I would literally carry a mouse and keyboard everywhere then.

Any help?

-Fickbowt

**Comment by Ferk** [comment]
I think you are in the wrong github.
You are probably talking about this: https://github.com/mkrupczak3/GZDoom-Android

"Freedoom" is a project to create free graphics, sounds and map assets for use with any Doom-compatible engine. Any questions or issues related to a particular Doom engine are only related to that engine. I don't think the Freedoom project has actively endorsed any particular engine so far, for what I know.

**Comment by chungy** [comment]
Indeed. We understand the distinction between just the game data (Freedoom) and engine (Eg, GZdoom for Android) is confusing, but this bug report belongs in the latter category.
