### ISSUE TITLE
Error at load saved game

### ISSUE THREAD

**Issue by Volkec** [freedoom/freedoom#526]
Using prboom-2.5.0-win32.
FreeDoom 0.11.3 - freedoom1.wad.
The game die at loading saved game, if demo already start - with error:
"Signal handler: Exiting on signal 11".

If I load saved game before demo starts, then OK. But it is difficult, because, I have only few seconds for this.
If I first start new game - even if demo starts before, is OK. Then I can load saved game without error.

**Comment by Kizoky** [comment]
It might be a problem with prboom, and not freedoom.
I think the demo is out of sync and that is what causes problems

**Comment by Volkec** [comment]
How can I sync the problem..... I mean prboom?
By the way, with freedoom2.wad - the same version 0.11.3 works OK. Loading saved game.

**Comment by Litrivin** [comment]
And Chocolate Doom won’t let the user load a new game while DEMO1 is playing.
I strongly think internal multiplayer demos ought to be replaced with standard single-player ones.

By the way, DEMO3 of freedoom1.wad crashes PrBoom-**Plus** (PrBoom is **really** obsolete, you should migrate to PrBoom-Plus unless you happen to prefer PrBoom for some inusual reason), which reports something about an unexpected angle for the player sprite. However, that very same demo plays back just fine if I use doom.wad as IWAD, once extracted and loaded as a PWAD file the corresponding map (C4M3, it happens to use only standard textures of _Doom_).

**Comment by chungy** [comment]
First: This would be a prboom bug, not a Freedoom bug, and yes, PrBoom-Plus should be considered the current branch of the port.

Second: I didn't know vanilla/chocolate has that limitation of being unable to load a game while the demo loop has a multiplayer session played out. I still like having multiplayer demos, but maybe we can think about keeping demo1 as single-player only.

> By the way, DEMO3 of freedoom1.wad crashes PrBoom-Plus

I can't reproduce this. I even made all the videos on YouTube for the demo loops that are recorded with prboom-plus.

**Comment by Litrivin** [comment]
@chungy: False alarm, this is the actual reason: https://www.doomworld.com/vb/post/1852928

By the way, issues 508 and 509 have nothing to do with the IWAD itself, so they can be closed in order to declutter a little the issues section.
