### ISSUE TITLE
Is this game was written in Python?

### ISSUE THREAD

**Issue by Alihusejn** [freedoom/freedoom#527]

**Comment by Calinou** [comment]
Freedoom isn't written in any language. It only provides game content (levels, textures, sounds, …) which can be used in most Doom source ports; see the [Freedoom download page](https://freedoom.github.io/download.html) for a non-exhaustive list. (Most source ports are written in C or C++.)

**Comment by Alihusejn** [comment]
Can I do this with Python?

**Comment by chungy** [comment]
We have a bunch of scripts used for the build that are Python, but I wouldn't really say the game is written in Python, no.
