### ISSUE TITLE
What about adding this polished version of C3M6?

### ISSUE THREAD

**Issue by DoomeroHispalense** [freedoom/freedoom#531]
https://www.doomworld.com/forum/topic/74395-e3m6-updatetweaks/

Paging @Talon1024 ...

I have tested it and it seems 100% compatible with vanilla, except for some minor and easily fixable _tutti-frutti_ artifacts.

**Comment by Talon1024** [comment]
I just realized that this submission was from 3 years ago. It's amazing the MediaFire link still works. I agree that this map should be added. It's a definite improvement over the current C3M6.

**Comment by DoomeroHispalense** [comment]
The secret exit? Well, it’s somewhat lame. But I think the pros outweigh the cons.

By the way, could you check this post of mine? I still think that _Freedoom_ needs these little icons for the sake of completeness, but, alas, I am not an artist to create them...
https://www.doomworld.com/forum/post/1826361

**Comment by Talon1024** [comment]
![igneous](https://user-images.githubusercontent.com/6550500/39957336-6757a52e-55bf-11e8-9919-4ba12b145600.png)

**Comment by DoomeroHispalense** [comment]
The first issue should be easily fixable, the second one seems to be a feature instead of a bug. Anyway, it seems it lacks from proper multiplayer support.

And speaking about multiplayer support, current MAP25 features drawseg overflows in the multiplayer-only area.

**Comment by Xindage** [comment]
this map seems to be already in the master. not sure if both are identical.
