### ISSUE TITLE
Daily Builds page has only deathmatch version

### ISSUE THREAD

**Issue by funduke** [freedoom/freedoom#550]
At the "Daily Builds" page at http://freedoom.soulsphere.org/ there is currently only the deathmatch version for download avayable.

**Comment by fragglet** [comment]
I run it. Now fixed.

**Comment by funduke** [comment]
Thank you.

 

Greetings

Funduke

 

Gesendet: Freitag, 25. Januar 2019 um 15:55 Uhr
Von: "Simon Howard" <notifications@github.com>
An: freedoom/freedoom <freedoom@noreply.github.com>
Cc: funduke <frank.bergien@gmx.net>, Author <author@noreply.github.com>
Betreff: *** GMX Spamverdacht *** Re: [freedoom/freedoom] Daily Builds page has only deathmatch version (#550)


I run it. Now fixed.
