### ISSUE TITLE
Text is invisible

### ISSUE THREAD

**Issue by ghost** [freedoom/freedoom#553]
Video showing at https://youtu.be/Op0QvtwoxaA (video showing the text)

I'm sure this is something wrong i'm doing but i don't see anyone else with this problem

I'm compiling on windows using cygwin and i don't see any errors except for wad2image not being found

https://pastebin.com/raw/2uz2aLJj (console output)

**Comment by chungy** [comment]
Do you have pillow installed? I think it would exit with an error if not, but I'm not sure right now.

**Comment by igdegoo** [comment]
> 
> 
> Do you have pillow installed? I think it would exit with an error if not, but I'm not sure right now.

I do have pillow installed

**Comment by Ferk** [comment]
I didn't say anything because I thought it was some problem in my setup, since I didn't compile the wads in a while... but I also have the same issue.

**Comment by NickZ** [comment]
Very strange. I would recommend trying this out on the Ubuntu terminal that is available for Windows 10, you can get it here: https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6?activetab=pivot:overviewtab
