### ISSUE TITLE
Freedoom: Phase 2.wad issue

### ISSUE THREAD

**Issue by Dauggo** [freedoom/freedoom#559]
When i want to play a diffrent WAD i just put in a diffrent .wad file, but it is stuck on freedoom: Phase 2. And it always dosent let me play any level's because of "Level has no vertices" or something like that. Hope i can get some help.

**Comment by Ferk** [comment]
Sounds like an issue with your source port, not with Freedoom. What source port are you using?

**Comment by rautamiekka** [comment]
> GZDoom? I don't know what source port im using.

That's just **absolutely impossible** for 2 reasons:
1) the EXE is named `gzdoom.exe`
2) it says GZDoom the boot dialog title

**Comment by chungy** [comment]
No personal attacks, please.

If you're using Windows, you can probably drag-and-drop WADs on top of the executable and they should launch. If it has errors like "no vertices", the map is probably invalid somehow.

**Comment by rautamiekka** [comment]
> No personal attacks, please.

No such thing was used.

**Comment by chungy** [comment]
> No such thing was used.

From the earlier message: "That's just **absolutely impossible**"

Not everyone knows what a source port is. Now let's drop this :)

**Comment by Dauggo** [comment]
When i try to play a diffrent wad, like maybe DOOM 2 or maybe something else, the game just shows the Freedoom title screen and the text, when i try to do a new game, it just shows the console. in green text there is "Map has no vertices" or something like that

**Comment by Ferk** [comment]
When you load GZDoom it normally shows a dialog asking which IWAD to load your WAD with. In that dialog there's a checkbox saying "Do not ask again".

You probably loaded Freedoom1 and marked "Do not ask again", which probably made GZDoom use Freedoom1 as the IWAD for every future WAD you load. Check your GZDoom configuration settings or just completely remove the config file.

Note that this is a GZDoom issue if anything, not Freedoom's fault, it would have happened as well if you did the same with Doom1 and then tried to load Doom2.

**Comment by Dauggo** [comment]
But how do i change the IWAD?

**Comment by Dauggo** [comment]
I found out how to change it, but Doom2.wad is freedoom.wad? Wierd...

**Comment by Dauggo** [comment]
Fixed all of this stuff.
