### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'identify': 'identify'

### ISSUE THREAD

**Issue by vilhelmgray** [freedoom/freedoom#569]
Executing `make` in the Freedoom version 0.11.3 source root directory results in missing file error:
```
make -C graphics/text
make[1]: Entering directory '/tmp/freedoom-0.11.3/graphics/text'
./textgen textgen.mk > textgen.mk
Traceback (most recent call last):
  File "./textgen", line 181, in <module>
    font = Font('fontchars', kerning_table=FONT_KERNING_RULES)
  File "./textgen", line 37, in __init__
    self.get_font_widths()
  File "./textgen", line 54, in get_font_widths
    w, _ = get_image_dimensions(filename)
  File "/tmp/freedoom-0.11.3/graphics/text/common.py", line 20, in get_image_dimensions
    stdout=subprocess.PIPE)
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'identify': 'identify'
Makefile:75: textgen.mk: No such file or directory
make[1]: *** [Makefile:71: textgen.mk] Error 1
make[1]: Leaving directory '/tmp/freedoom-0.11.3/graphics/text'
make: *** [Makefile:19: subdirs] Error 2
```

I suspect I'm missing a dependency, but I don't know what package provides the `identify` file.

I am running **GNU Make 4.2.1**, **Python 3.6**, **Pillow 6.0.0**, and **DeuTex 5.2.0**.

If another dependency is required, then we can update the [COMPILING.adoc](https://github.com/freedoom/freedoom/blob/master/COMPILING.adoc) file to include it.

**Comment by vilhelmgray** [comment]
The [README file](https://github.com/freedoom/freedoom/blob/master/graphics/text/README) in the `graphics/text` directory states:

> The script generates the image by invoking ImageMagick to composite the
character graphics together. ImageMagick is therefore a dependency,
although the Python wrapper for ImageMagick is not used.

Is this the package that provides `identify`?

**Comment by Calinou** [comment]
`identify` is part of ImageMagick, like `convert` and `mogrify`.

**Comment by vilhelmgray** [comment]
After installing the latest version of ImageMagick (version 7.0.8-51), I was able to get past the missing `identify` issue. However a new error appears regarding `convert`:

```
make VERSION=v0.11.3 -C graphics/titlepic
make[1]: Entering directory '/tmp/freedoom-0.11.3/graphics/titlepic'
convert -transparent '#00ffff' ../m_doom.gif m_doom.gif
convert -transparent '#00ffff' ../t_phase1.gif t_phase1.gif
./create_caption titlepic.gif m_doom.gif t_phase1.gif fd1title.gif
convert: delegate library support not built-in '/usr/share/fonts/urw-fonts/n019004l.pfb' (Freetype) @ warning/annotate.c/RenderFreetype/1808.
convert: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
convert: non-conforming drawing primitive definition `text' @ error/draw.c/RenderMVGContent/4395.
convert: delegate library support not built-in '/usr/share/fonts/urw-fonts/n019004l.pfb' (Freetype) @ warning/annotate.c/RenderFreetype/1808.
convert: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
convert: non-conforming drawing primitive definition `text' @ error/draw.c/RenderMVGContent/4395.
make[1]: *** [Makefile:16: fd1title.gif] Error 1
make[1]: Leaving directory '/tmp/freedoom-0.11.3/graphics/titlepic'
make: *** [Makefile:20: subdirs] Error 2
```
It's possible my version of ImageMagick is missing a feature. Do you know which feature is required (I can probably recompile it from source with the required support)?

**Comment by vilhelmgray** [comment]
I'm sorry, I was wrong. It looks like my package system installed a security policy xml file that blocks the usage of the 'PS' coder by default: `/etc/ImageMagick-7/policy.xml`

**Comment by vilhelmgray** [comment]
Commenting out the following line as such in `/etc/ImageMagick-7/policy.xml` allows the Freedoom build to complete without error:
```
<!-- <policy domain="coder" rights="none" pattern="PS" /> -->
```

Thank you for the help, I believe this Github issue can be closed now. At some point, it will be good to add ImageMagick to the dependency list in [COMPILING.adoc](https://github.com/freedoom/freedoom/blob/master/COMPILING.adoc) so that it will be more obvious to casual users.

**Comment by chungy** [comment]
The master branch doesn't use ImageMagick anymore, instead uses Pillow. The [version you were trying to build](https://github.com/freedoom/freedoom/blob/v0.11.3/COMPILING.adoc) already tells you what you need :)

**Comment by vilhelmgray** [comment]
My apologies, you're right it doesn't require ImageMagick anymore -- I just cloned the master branch and compiled successfully without the ImageMagick tools. In the future, I'll make sure to check that the documentation I'm looking at matches the version I'm building.

I think it will be good to have Autotools support to provide the dependency checking for users via a canonical configure script. I'm considering writing a patch to add the support to Freedoom; would you be opposed if I made such a pull request in the future?
