### ISSUE TITLE
MAP02: Wrong end level switch graphic

### ISSUE THREAD

**Issue by mulenmar** [freedoom/freedoom#570]
MAP02's end switch uses a skull switch patch (SW2_7), which doesn't really fit the techbase theme of the level.

Would suggest SW1S0 instead.

**Comment by Proluiz** [comment]
Here's the fix for it, nothing was changed aside from the switch.
[map02_fix.zip](https://github.com/freedoom/freedoom/files/3576934/map02_fix.zip)
