### ISSUE TITLE
Sound Ideas Copyright Infringement

### ISSUE THREAD

**Issue by saniv** [freedoom/freedoom#576]
Due to your dismissive handling of copyright issues, I've added Freedoom to the evergrowing list of copyright unsafe open sources projects:
https://github.com/saniv/free-game-art/blob/master/foss-copyright-infringement-records.md

Have a nice day.

**Comment by chungy** [comment]
Thanks, but you provide no real evidence and the history of the project is quite contrary to your conclusion. We must dismiss you as nothing more than a troll :)
