### ISSUE TITLE
DEMO1 should not be a netgame

### ISSUE THREAD

**Issue by fragglet** [freedoom/freedoom#579]
I recently discovered that there's a vanilla bug where it's not possible to use "load game" from the main menu while a netgame demo is playing (since the menu thinks you're in a netgame). `freedoom1.wad`'s DEMO1 is a netgame demo so this means that if you don't immediately choose "Load Game" after the game starts, you're locked out from loading a game until the next demo plays. I'm not opposed to having some netgame demos in the rotation but maybe we could keep DEMO1 as a single player demo?

**Comment by chungy** [comment]
Good point, especially as the demo loop starts very soon after loading the game.
