### ISSUE TITLE
Textures: BIGBRIK1 and BIGBRIK3 differ from each other, unlike doom2.

### ISSUE THREAD

**Issue by Proluiz** [freedoom/freedoom#586]
Bigbrik1 needs to be repatched to match the current version of bigbrik3, it make so easy to noticed the diferences in some map mods.

In Doom2:
![BIGBRIK1](https://user-images.githubusercontent.com/6380147/63427878-915cff80-c3ec-11e9-951d-94a274921029.png)![BIGBRIK3](https://user-images.githubusercontent.com/6380147/63427885-9621b380-c3ec-11e9-8f10-bcd237a2b29f.png)![BIGBRIK1](https://user-images.githubusercontent.com/6380147/63427878-915cff80-c3ec-11e9-951d-94a274921029.png)

In Freedoom2:
![BIGBRIK1](https://user-images.githubusercontent.com/6380147/63428009-dbde7c00-c3ec-11e9-8b97-85941c7c93a3.png)![BIGBRIK3](https://user-images.githubusercontent.com/6380147/63428012-de40d600-c3ec-11e9-8e9c-fa8c3e207031.png)![BIGBRIK1](https://user-images.githubusercontent.com/6380147/63428009-dbde7c00-c3ec-11e9-8b97-85941c7c93a3.png)

**Comment by chungy** [comment]
Looks more like an intentional difference to account for the light source... I'm personally in favor of keeping it like this.

I could maybe see it making secrets easier to find, but are there examples where it makes maps too easy?

**Comment by AXDOOMER** [comment]
It doesn't make sense bright up the pixels on a texture with a light source considering that light should propagate to adjacent wall textures as well.

The only valid example is the following case, where the resulting light of a light source can be contained within the texture itself. (Doom 2 MAP27)
![Screenshot_2019-08-21_14-57-13](https://user-images.githubusercontent.com/6194072/63460253-2a5b3d00-c424-11e9-9fa2-9665937ede2e.png)

It's up to the author of the map to make design decisions about light and I don't think Freedoom should include design decisions that will break what a map was supposed to look like in the original Doom. If the author wants to show that a wall emits light (or bright up the pixels on a wall), he will add a sector with a different light value. 

Other designs decisions were made in the past, like changing the candle sprite for a little lamp, and I think this inevitably breaks how some maps were intended to look.

**Comment by NickZ** [comment]
Makes sense to me. Do you want to take a crack at fixing it?

**Comment by fragglet** [comment]
+1 to keeping the texture the way it is. It's not a design goal for the textures to look identical to Doom's - rather, we should be making a conscious effort to deliberately make them look different. I'd actually be in favour of replacing the current texture with something even more different to the Doom II one.

**Comment by Proluiz** [comment]
care to tell us any example, i can try something, and them we can get something new maybe

**Comment by MatthewTheGlutton** [comment]
I agree with fragglet but something should still be done about these particular textures given how there's this sharp visible line between the light one and the regular ones around it. Maybe add that lightening effect to the non-light ones too?

(And would there be any hope in maybe making this look a little *more* different from Doom? I know the brick lines need to line up as in the original given how many maps actually align them, but the bricks could be made 1/2 size with more lines or the lines themselves could be light or something)

**Comment by Proluiz** [comment]
here's 2 possible option to fix the issue:

Using the darker one:
![BIGBRIK1](https://user-images.githubusercontent.com/6380147/64302638-aa23f400-cf5a-11e9-9c36-9031b675c15c.png)![alt1](https://user-images.githubusercontent.com/6380147/64302645-ae501180-cf5a-11e9-8050-268313f67222.png)![BIGBRIK1](https://user-images.githubusercontent.com/6380147/64302647-b14b0200-cf5a-11e9-8f92-32a036a64c1b.png)

Using the bright one:
![alt2](https://user-images.githubusercontent.com/6380147/64302667-bc059700-cf5a-11e9-8ff2-caa015dd5368.png)![BIGBRIK3](https://user-images.githubusercontent.com/6380147/64302671-bf991e00-cf5a-11e9-8f3c-611785cab2ef.png)![alt2](https://user-images.githubusercontent.com/6380147/64302675-c1fb7800-cf5a-11e9-8907-c5fbd293569a.png)

**Comment by MatthewTheGlutton** [comment]
So I just tried rapidly switching between
https://user-images.githubusercontent.com/6380147/63427885-9621b380-c3ec-11e9-8f10-bcd237a2b29f.png D2
https://user-images.githubusercontent.com/6380147/64302645-ae501180-cf5a-11e9-8050-268313f67222.png Proposed fix 1
https://user-images.githubusercontent.com/6380147/63428012-de40d600-c3ec-11e9-8e9c-fa8c3e207031.png Freedoom current
in different tabs and I'm seeing similarities that are a lot closer (esp. the dark teal bits) than could be explained by needing something somewhat similar-looking.

It might be advisable to do a brand new version of these textures from scratch.

**Comment by MatthewTheGlutton** [comment]
Here's what I've got for RW23_3 right now. Anything that needs to be changed?
<a href="https://imgur.com/2waxYUu"><img src="https://i.imgur.com/2waxYUu.png" title="source: imgur.com" /></a>

**Comment by Proluiz** [comment]
indeed is diferent but, the lines are way light.

**Comment by MatthewTheGlutton** [comment]
My thought on that is that it *should* be different from the Doom version, but I'll make the mortar darker than the brick again if there's anything that's clearly broken by this.

**Comment by AXDOOMER** [comment]
@MatthewTheGlutton  This one looks good. Looks like chocolate walls.

**Comment by MatthewTheGlutton** [comment]
Oh hey I can upload with Ctrl+V here

Thoughts on which one of these to use? I did the first one on the left, after misremembering and thinking that the D2 version had only 1 light while Freedoom had 2, then did the one on the right when I looked again and realized D2 was the one that had 2 lights while Freedoom currently has 4.
![image](https://user-images.githubusercontent.com/24984517/64379488-ddf72c00-cfe3-11e9-80eb-9f2d34b362ab.png)

**Comment by Proluiz** [comment]
Both looks good, can you do the gray version too? Whiteout doing recolor too?

**Comment by MatthewTheGlutton** [comment]
Of course!
![image](https://user-images.githubusercontent.com/24984517/64386177-45fe4000-cfed-11e9-8625-df9614ca6d4b.png)

As for which light strip, I'm personally inclined to use the more Doom-like one simply because it looks better, but have there been any Freedoom maps that rely on this texture having four lights (e.g., a 16-pixel-wide square column with a light at the bottom)?

**Comment by AXDOOMER** [comment]
> Thoughts on which one of these to use?

I'd say the one with two lights looks best because it makes less repetition and the bricks are large too, so larger lights looks best. 

> but have there been any Freedoom maps that rely on this texture having four lights (e.g., a 16-pixel-wide square column with a light at the bottom)?

It doesn't matter if you make them smaller. If you would have made them bigger for example, they could get cut in half in some maps so it would break the texture alignment of some walls.

**Comment by MatthewTheGlutton** [comment]
Good point about there actually being an aesthetic principle in favour of the 2-light.

And it occurs to me that the brick design doesn't really lend itself to the 16-pillar thing anyway while the current Freedoom 4-light isn't even regular in a way that would allow for it:
![image](https://user-images.githubusercontent.com/24984517/64392633-80bea300-d002-11e9-9927-7a627150c148.png)

**Comment by MatthewTheGlutton** [comment]
I think this issue can be closed since the graphics originally in question have been replaced.
