### ISSUE TITLE
I noticed some issues

### ISSUE THREAD

**Issue by P41R47** [freedoom/freedoom#587]
Hi, Everybody! New to the git and really wanting to support Freedoom and help in it development.
Well i downloaded the last git build (0.11-348-g43ec8a91) and i found something that feels off.
The new teleport sounds like a monster telefrag, in other words, sounds a lot like when a monsters is gibbed. At first i think it was a new change to give Freedoom more personality, but next thing i found is me checking my soles and searching for the gibbed corpse around.

Another little thing i found is the numerical text in the intermission screen. I really like to play Hell2Pay with Freedom to simulate that it is THE total conversion Hell 2 Pay was meant to be. And after finishing a level, in Hell 2 Pay there are story text as CWILV with some hints for the next level and for the story to unfold. Well, with DOOM 2 as iwad, that story text can be read properly, but with Freedoom 2 as iwad, the level stats appeard to be a little more separated.
The graphic of the intermission are all custom from H2P, what doesn't change was the numbers of the stats. Here to show what im saying:
![ISSUE1](https://user-images.githubusercontent.com/54422591/63560115-2534e580-c52b-11e9-910d-28deb76e0fd2.png)
![ISSUE2](https://user-images.githubusercontent.com/54422591/63560122-2b2ac680-c52b-11e9-85eb-aa8625b331af.png)

Last thing i found is that Freedoom, greatly changes how mods with custom music sounds. I played H2P with Freedoom 2 in crispy, and then with Doom 2 also in crispy, and the music sound totally different. I'm playing in crispy/chocolate with OPL chip type 3.
I tried other mods with custom music and they also sounds pretty different than with Doom 2.
And to my total surprise Struggle: Antaresian Legacy cannot be played in crispy with Freedoom 2, while it is totally playable with Doom 2 iwad.

**Comment by chungy** [comment]
Thanks, it'd be appreciated if you make separate issues for everything you find.

That being said, I have to 100% agree on the teleporter sound having regressed in its purpose. I get confused often playing recent builds.

**Comment by P41R47** [comment]
Thanks for answering, Chungy. 
About the DMXGUS, i think thats what makes the music in freedoom sound different. But the difference is pretty big. It could break some PWAD compatibility... Well, not breake it, but surely make it completly different and throw some players away.
