### ISSUE TITLE
Textures: Implement FD2 stock textures into FD1

### ISSUE THREAD

**Issue by Proluiz** [freedoom/freedoom#588]
Why we havent have all textures from freedoom phase 2 inside fredoom phase 1?

For example we can see small chuncks of phase 2 texture data inside phase 1, like some metal textures, aquatex and plutonia bricks.

Based on what i said here: https://www.doomworld.com/forum/post/2020360
I really want to start using these textures to make episode 2 very unique, if you guys let me have these textures in freedoom phase 1 i'll be extreme pleased.

And yes i'm already aware that doom1 and doom2 dont share the same switchs sets and must be kept untouched to keep the compatibility with mods.

**Comment by fragglet** [comment]
Sounds reasonable to be honest.

**Comment by MatthewTheGlutton** [comment]
What about other assets like P2 monster sprites and sounds and SSG?

**Comment by Proluiz** [comment]
not necessary, doom mods that uses doom2 exclusive assests like monsters do it by itself, an example:

Complex doom and Knee deep in zdoom

**Comment by Ferk** [comment]
Honestly it would be quite convenient if there was a version of the wad that used some MAPINFO magic to add phase 2 as if it was an episode 5. Then everything would be contained in a single wad (would wads from both Doom1 and Doom2 work with it?).

I know this would not work in anything close to vanilla, or even prboom, though.

**Comment by chungy** [comment]
There could possibly be a (wadsmoosh)[https://bitbucket.org/JPLeBreton/wadsmoosh/] fork to combine all of FreeDM, Phase 1, and Phase 2.

Other than that, Phase 2-specific sprites like monsters and SSG should be excluded from Phase 1. The rest of the textures should be fine.
