### ISSUE TITLE
SKY4 break compatibility.

### ISSUE THREAD

**Issue by P41R47** [freedoom/freedoom#589]
I know this issue was talked before, but, i found that the pwad ''CRUSADES'' by Richard Wiles, uses the sky4 backdrop to generate shadowed things in the distance. Unfortunately, that details can't be appreciated with the starry sky of E4.
I played around with the resources, and i found that a SKY texture with more than one lump overrides whatever SKY texture that appeard in any pwad. Even if they are named RSKYx as in the texture patch. Only way that i found to change them (if the pwad doesn't have any TEXTUREx, PNAMES), is bia MAPINFO. And even in MAPINFO they need to be named RSKYx to be displayed properly. This ocurred to me in GZDOOM and in Crispy
I like the starry sky, and it truly goes with the aesthetic of double impact. I don't want it to be changed at all, but maybe we need to use an starry sky that doesn't use more than one texture lump for full compatibility.

**Comment by chungy** [comment]
There sadly seems to be multiple issues surrounding this, I'll post screenshots for reference, all using [crusades.wad](https://www.doomworld.com/idgames/levels/doom/a-c/crusades):

Crispy+Freedoom:
![crusades-crispy-freedoom](https://user-images.githubusercontent.com/1094821/63642773-6c30f100-c679-11e9-92e0-e1f482532219.png)
Crispy+Doom:
![crusades-crispy-doom](https://user-images.githubusercontent.com/1094821/63642772-6c30f100-c679-11e9-9290-cfe040368f96.png)

Vanilla+Freedoom:
![crusades-vanilla-freedoom](https://user-images.githubusercontent.com/1094821/63642774-6c30f100-c679-11e9-92a8-9a5eb2ef458b.png)

Doom's E4 sky does not contain any discernible light source, and it's possible to make maps that arbitrarily pick a direction.

The vanilla case (also occurs in prboom-plus) is more worrying and indeed seems to be a result of our SKY4 being composed of four textures. Console output in Chocolate Doom shows:
```
R_GenerateLookup: column without a patch (SKY4)
```

I'm not sure if this is solvable without compromising Double Impact's artistic quality a little bit by going back to a single texture only for SKY4. If we do that, I'd pick SKY4A (the stars with no light source).

**Comment by chungy** [comment]
I've done some experimenting, and I really don't think we can keep a special SKY4 made up of multiple patches while keeping vanilla mod compatibility. It's sad, but I'll favor said compatibility for a little change to Double Impact.

**Comment by P41R47** [comment]
Glad to spot it!
SKY4A seems the natural choice, but maybe something like this could work, too
![muestra](https://user-images.githubusercontent.com/54422591/63643320-656ba380-c6a4-11e9-8871-1cefd2d8de1b.png)
 Maybe its to simple, but looks like an arm of the milky way's spiral (or we could try to achive an affect similar to what i said 
![Screenshot_Doom_20190824_195017](https://user-images.githubusercontent.com/54422591/63643525-a665b700-c6a8-11e9-8419-9f6b421c1b59.png)
![Screenshot_Doom_20190824_195141](https://user-images.githubusercontent.com/54422591/63643526-a665b700-c6a8-11e9-8481-884a12a88962.png)

:P).
![Screenshot_Doom_20190824_193714](https://user-images.githubusercontent.com/54422591/63643465-1bd08800-c6a7-11e9-9c71-46ed3398d752.png)
![Screenshot_Doom_20190824_193743](https://user-images.githubusercontent.com/54422591/63643466-1c691e80-c6a7-11e9-93e4-3dd75d144d21.png)
![Screenshot_Doom_20190824_193749](https://user-images.githubusercontent.com/54422591/63643467-1c691e80-c6a7-11e9-8538-55d66fc45275.png)
![Screenshot_Doom_20190824_193914](https://user-images.githubusercontent.com/54422591/63643468-1c691e80-c6a7-11e9-86a9-3b214819b9ef.png)
![Screenshot_Doom_20190824_194025](https://user-images.githubusercontent.com/54422591/63643469-1d01b500-c6a7-11e9-8a22-0d1af1996fe4.png)
In the last 2 photos i tried to give the image a light blueish tint with slade.
