### ISSUE TITLE
Posibble new SKY4 replacement

### ISSUE THREAD

**Issue by P41R47** [freedoom/freedoom#590]
I found a a neat and free Sky to replace SKY4.
http://www.textures4photoshop.com/tex/clouds-and-sky/seamless-galaxy-with-stars-texture-for-photoshop.aspx

The only inconvenient is that, to make it loop, we have to spin it 90°. like this:
![seamless-galaxy-with-stars-texture-for-photoshop-thumb48](https://user-images.githubusercontent.com/54422591/63643692-d616be00-c6ac-11e9-829e-5fc8c7f7ddea.jpg)

Here some screenies with that nice space sky
![Screenshot_Doom_20190824_201321](https://user-images.githubusercontent.com/54422591/63643698-f777aa00-c6ac-11e9-9661-e026ed62b8f0.png)
![Screenshot_Doom_20190824_201344](https://user-images.githubusercontent.com/54422591/63643699-f777aa00-c6ac-11e9-8bdd-94185ac1631c.png)

Here is the image ready for include in Freedoom1 in PNG.
![Prueba SKY 4](https://user-images.githubusercontent.com/54422591/63643700-ffcfe500-c6ac-11e9-894f-55ecd1abe97f.png)

Chungy, i tried it with crusades.wad and it looks pretty good; look at it:
![Screenshot_Doom_20190824_202511](https://user-images.githubusercontent.com/54422591/63643726-85ec2b80-c6ad-11e9-9972-349669d108c0.png)
![Screenshot_Doom_20190824_202526](https://user-images.githubusercontent.com/54422591/63643727-85ec2b80-c6ad-11e9-969e-19469b02e9d5.png)
![Screenshot_Doom_20190824_202543](https://user-images.githubusercontent.com/54422591/63643745-ed09e000-c6ad-11e9-827a-c8a6bf485ad8.png)

For obvious reasons i cant tried it with Freedoom1, but aside from the monsters, the mood isn't breake it at all

**Comment by MatthewTheGlutton** [comment]
> I found

uh

**Comment by chungy** [comment]
You have a good idea, but we tend to be weary of such websites. The [about](http://www.textures4photoshop.com/tex/about.aspx) page kind of reads like it might be ok, but I have open questions as to the origin of the image.

We'd be better off trying to find images with a very clear license (or public domain). Most of what NASA publishes is public domain, and you might also find something on [Wikimedia Commons' astronomy category](https://commons.wikimedia.org/wiki/Category:Astronomy)

**Comment by P41R47** [comment]
How about this one, is from wikipedia:
https://it.wikipedia.org/wiki/File:Milkyway-summit-lake-wv1_-_West_Virginia_-_ForestWander.jpg

![800px-Milkyway-summit-lake-wv1_-_West_Virginia_-_ForestWander](https://user-images.githubusercontent.com/54422591/63644096-3ad71600-c6b7-11e9-87d7-0b6b0bb7deac.jpg)


... But also i edited it a little to make it more dooomey...
![Prueba SKY 4 2](https://user-images.githubusercontent.com/54422591/63644090-26931900-c6b7-11e9-80c7-927af34344e3.png)

Here some screenies:
![Screenshot_Doom_20190824_213511](https://user-images.githubusercontent.com/54422591/63644101-4cb8b900-c6b7-11e9-9e84-acf9ea2aaed4.png)
![Screenshot_Doom_20190824_213242](https://user-images.githubusercontent.com/54422591/63644102-4cb8b900-c6b7-11e9-9dd5-b60a4a56d424.png)
![Screenshot_Doom_20190824_213408](https://user-images.githubusercontent.com/54422591/63644103-4d514f80-c6b7-11e9-94d5-7c893d108a6a.png)

**Comment by Ferk** [comment]
Looks good but aren't the darker stripes giving away the tiling too much?
It's a pity because the first one you showed looped very well. Any chance to make the transition less obvious?

**Comment by Ferk** [comment]
> https://it.wikipedia.org/wiki/File:Milkyway-summit-lake-wv1_-_West_Virginia_-_ForestWander.jpg

The Wikipedia states the image is CC-BY-SA 3.0, I think that's not compatible with BSD.

There are many space images under public domain or CC-0. For example:
 https://commons.wikimedia.org/wiki/File:Milky_Way-Andromeda_Collision_close-up.jpg
There are even panoramic ones that should be easier to tile:
 https://commons.wikimedia.org/wiki/File:Deathvalleysky_nps_big.jpg
 https://commons.wikimedia.org/wiki/File:ESO_-_Milky_Way.jpg

**Comment by Ferk** [comment]
It shouldn't be very hard to shift around the image and mix a bit the colors around the junction.
I gave it a try:
![image](https://user-images.githubusercontent.com/193426/63884316-3e7bdd00-c9d6-11e9-9a2d-346f890729cd.png)

**Comment by Ferk** [comment]
This version is also kind of decent at tiling vertically too. I was thinking perhaps that would be a good thing for ports that use freelook in software mode and don't scale the sky.
![image](https://user-images.githubusercontent.com/193426/63885703-3bceb700-c9d9-11e9-93d1-ddd56c4990e5.png)
