### ISSUE TITLE
Maps with missing deathmatch starts

### ISSUE THREAD

**Issue by chungy** [freedoom/freedoom#598]
Freedoom should have every level stocked with four co-op starts, and at least 8-ish deathmatch starts per level. Vanilla Doom only recognizes the first 10 deathmatch starts in a map, but it is not an error for more to exist and it might make sense for some maps to have extras that may be used by advanced engines. There is a hard requirement of at least 4 deathmatch starts per level.

Some levels are lacking these requirements, Specifically:
* C2M6: 0 starts
* C2M7: 0 starts
* C3M2: 0 starts
* C3M3: 0 starts
* C3M4: 0 starts
* C3M6: 1 start

**Comment by MatthewTheGlutton** [comment]
I was wondering if they had been intentionally omitted from the singleplayer IWADs! Glad to know they aren't.

**Comment by chungy** [comment]
Even though single-player is the focus of Phase 1 and 2, we need to support all game modes.

**Comment by Proluiz** [comment]
Even if i'm on work of episode 2 I'm not going to fix it so soon since i'm still planning to do something else with these maps, but if REALLY necessary I can fix it.

**Comment by chungy** [comment]
If you're adding new versions of those maps, you don't need to fix the current ones.

**Comment by Proluiz** [comment]
That's a fix for the non existent DM Start locations, I dont have tested it so much, i just make sure that any player dont be alone on the area of the map that he spawn.
[DMStarts.zip](https://github.com/freedoom/freedoom/files/3576820/DMStarts.zip)

I also fixed a wrong texture mc18 used in e3m3 and replaced it by the BFALL1 (blood waterfall)
