### ISSUE TITLE
The list of issues seriously needs a review.

### ISSUE THREAD

**Issue by Xindage** [freedoom/freedoom#599]
Few isseus out here are really ancient and few of them can be closed since it was either fixed/changed/notfix/portissue.

so my suggestion is really look on these issues and find who are still true and who is already false.

Some examples to check:
Some sprites have speckles when playing with D2TWID https://github.com/freedoom/freedoom/issues/48 
:::::::::::::::::::::::::::::::::::::::::::::::::
Weapon sound length and volume https://github.com/freedoom/freedoom/issues/89
:::::::::::::::::::::::::::::::::::::::::::::::::
new textures for plutonia caused some bad texturing in certain maps (Freedm) https://github.com/freedoom/freedoom/issues/121
:::::::::::::::::::::::::::::::::::::::::::::::::
Monster sprite frames that are not lit as they should be https://github.com/freedoom/freedoom/issues/141
:::::::::::::::::::::::::::::::::::::::::::::::::
freedoom1.wad is not identified as a doom.wad drop-in replacement https://github.com/freedoom/freedoom/issues/253
:::::::::::::::::::::::::::::::::::::::::::::::::
Lift that is supposed to lead to yellow key on C3M7, phase 1 ins't working https://github.com/freedoom/freedoom/issues/280
:::::::::::::::::::::::::::::::::::::::::::::::::
C1M9 Few Zombies are just Blind and deaf. https://github.com/freedoom/freedoom/issues/331

**Comment by doomfighter33456** [comment]
and map12 has still misaligned switches
