### ISSUE TITLE
Easy to get stuck in E2M6 - C2M6 Trepidation Site

### ISSUE THREAD

**Issue by GamesOpenSource** [freedoom/freedoom#607]
It's easy to get stuck here, especially because it seems like it would be really easy to jump over the fence on the right (but there is an invisible wall):
![a](https://user-images.githubusercontent.com/54016023/64907045-07a00980-d6ee-11e9-8015-f356764f17ff.jpg)

You can probably rocketjump but in my experience you don't have the HP for that at that point.

**Comment by Calinou** [comment]
Note that you can't get there without jumping (which isn't a feature present in vanilla Doom). Still, it probably doesn't hurt to fix it :slightly_smiling_face:

**Comment by Proluiz** [comment]
i'll take care of it.

**Comment by Proluiz** [comment]
here's the fix, if you can reach there with jump I added a crate that help you jump off from there.
[e2m6.zip](https://github.com/freedoom/freedoom/files/3665841/e2m6.zip)
