### ISSUE TITLE
README.md is incredibly incredible

### ISSUE THREAD

**Issue by fabiangreffrath** [freedoom/freedoom#610]
Hi there,

README.md contains the same superlative twice in two adjacent sentences:

  You must be **incredibly** careful when basing on existing graphics or sounds.  Most _Doom_ projects are **incredibly** lax on reusing intellectual property [...]

This should probably be improved.

**Comment by MatthewTheGlutton** [comment]
Hot take: it's even better with that emphasis, twice.

Because it's true.

**Comment by AXDOOMER** [comment]
Looks more like a figure of speech than something that should be improved.

**Comment by selliott512** [comment]
Joining the two sentences "... or sounds because most ..." would make the reuse of "incredibly" seem intentional rather than a failure to come up with a synonymous word. It's pretty low on my list of concerns though.

**Comment by chungy** [comment]
It's probably improved if the word is removed in both instances.
