### ISSUE TITLE
Player/zombie shooting sprites

### ISSUE THREAD

**Issue by MatthewTheGlutton** [freedoom/freedoom#611]
Actually two issues:

1. I noticed while doing stuff for point 2 that the offsets for ****E2E8 and ****F2F8 are based on the center of *the image* rather than the center of where the actor's body appears to be. I assume this holds true for the other sprites as well where the weapon is extending outwards horizontally. This can be misleading in play when someone appears to be behind cover when they're not, or if someone naïvely assumes that a monster has radius 20 extending from the middle of its body:
![image](https://user-images.githubusercontent.com/24984517/65177000-b4d69280-da0a-11e9-9bf8-b6786d656b50.png)
(red: real hitbox center line; brown: perceived center line; pink: actual hitbox; blue: section of perceived hitbox extending outside of actual hitbox)

I'm posting this as an issue just in case there's some well known mod out there that relies on this behaviour. If not, I'll see if I can go through the buildcfg and post a PR.

2. I can post some modifications to the player shooting sprites so that the E frame has the gun pointed and both frames actually appear to be shooting at height 36, as shown in this rough mockup:
![image](https://user-images.githubusercontent.com/24984517/65176019-cae35380-da08-11e9-9923-67022647a4cf.png)

Are either of these things worth working on? If not I'd still like to PR one specific fix for the PLAYE2E8 sprite as shown on the far left of the above image, just so the gun isn't crooked.

**Comment by Ferk** [comment]
That's great! honestly, the player sprite did need some love. His arms from the side do look like a gorilla.

I do like the small incremental improvements. I did also some incremental tweaks to the front & back sprite in the past (#546) in retrospect I should have modified the rest as well accordingly (the huge boots are imho a bit too much and were messing up the walking animation).

**Comment by MatthewTheGlutton** [comment]
Thank you for the implied go-ahead re: boots. XD

**Comment by MatthewTheGlutton** [comment]
....this is a rather large project now that the boots are a thing.

I think I'll post a PR to center the shooting sprites first since I see that all other frames and rotations are fairly close to centre body mass.

**Comment by MatthewTheGlutton** [comment]
I'm still very slowly working on some player running sprites but I think everything mentioned in the OP has been addressed.
