### ISSUE TITLE
Texture: The texture AQPIPE04 wont tile correct.

### ISSUE THREAD

**Issue by Proluiz** [freedoom/freedoom#612]
While mapping i have noticed that one of the aquatex texture wont tile correct, making a wierd effect when used on long walls, here's a example in doom builder.
![image](https://user-images.githubusercontent.com/6380147/65290240-d9bf2880-db24-11e9-9037-1b0eeb87426d.png)

**Comment by MatthewTheGlutton** [comment]
Here's a first pass at it - still tiles kinda funny but no visible hard seam as far as I can tell.
![aqpipe04tileable](https://user-images.githubusercontent.com/24984517/65299721-87323c00-db25-11e9-931c-a601fb56975c.png)

**Comment by Proluiz** [comment]
The second one is way better

**Comment by MatthewTheGlutton** [comment]
One more go, absent any obvious issues I think I'll put up a PR for this
![aqpipe04tileable_shifted_smooth](https://user-images.githubusercontent.com/24984517/65336087-8d063c80-db7a-11e9-901f-6e35fc359db4.png)![aqpipe04tileable_shifted_smooth](https://user-images.githubusercontent.com/24984517/65336087-8d063c80-db7a-11e9-901f-6e35fc359db4.png)![aqpipe04tileable_shifted_smooth](https://user-images.githubusercontent.com/24984517/65336087-8d063c80-db7a-11e9-901f-6e35fc359db4.png)

**Comment by Proluiz** [comment]
good.
