### ISSUE TITLE
Doom-compatable maps?

### ISSUE THREAD

**Issue by Epictyphlosion** [freedoom/freedoom#620]
I've been wondering if it's possible to play the maps in Freedoom with a Doom or Doom II IWAD. I've seen some posts suggesting that , even if one did extract the maps from the Freedoom IWAD, it wouldn't work since the textures have different names in Freedoom. Do you guys have any plans to release the maps as PWADS?

**Comment by chungy** [comment]
The maps are only intended for Freedoom, not any other games. It would take significant editing work to turn them Doom-compatible and we won't have any official project to do so.

**Comment by Calinou** [comment]
For posterity, I asked the same question in #534 a while ago.
