### ISSUE TITLE
Proposed new shotgun sound

### ISSUE THREAD

**Issue by ObsidianPlague** [freedoom/freedoom#623]
http://www.geocities.ws/obsidianplague/etc/DSSHOTGN.wav

**Comment by MatthewTheGlutton** [comment]
So I finally managed to try this and the current DSSHOTGN at home in my regular setup.

This doesn't strike me as an improvement, even if it weren't far, far too quiet.

**Comment by Calinou** [comment]
> EDIT: I suspect that something in the sound engine is cutting out a lot of the higher-pitch loud parts leaving a muddy mess at the end. I've had this trouble in the past with stuff that would sound great until it actually got into the game - sometimes it would help to convert it to 11025.

Remember that GZDoom has options to change the resampling mode from (linar, nearest, …). Using a nearest resembler will result in a "crisper" sound, which may sound better depending on the sounds.
