### ISSUE TITLE
FreeDM: This iwad requires a new title screen

### ISSUE THREAD

**Issue by Xindage** [freedoom/freedoom#634]
The title screen of FreeDM is based on old map04 and it wont display the correct "version" of the map.
if someone comes with a original idea it'll be good too.

**Comment by Proluiz** [comment]
![image](https://user-images.githubusercontent.com/6380147/67350236-9b040000-f520-11e9-9f5e-c117ce0c5896.png)
now the same screenshot from almost the same location:
![image](https://user-images.githubusercontent.com/6380147/67350277-b7a03800-f520-11e9-9181-86e7ccff9ddd.png)

**Comment by fabiangreffrath** [comment]
Look a bit less spectacular now, unfortunately. BTW, you can bind a key in Crispy Doom yo take a "clean screenshot", i.e. without HU messages and weapon sprites.

**Comment by MatthewTheGlutton** [comment]
Looking less spectacular probably because the same decorative elements are isolated in a much bigger space + the primary colours on the stuff on the left side of the screen being replaced with browns and greys.

Back to the title screen, ideally there'd be some actual art for it...

**Comment by AXDOOMER** [comment]
The current title screen looks fine. I don't see why it should be changed just because the level represented in the screen looks different. 

> ideally there'd be some actual art for it...

Could be real cool.

**Comment by mc776** [comment]
Addressed by #1224.
