### ISSUE TITLE
C1M7 : "lost souls" and cell ammo are found.

### ISSUE THREAD

**Issue by FredBezies** [freedoom/freedoom#636]
Playing freedoom phase 1 based on last github version, I noticed some "lost souls" (can't remember their freedom name) and cell ammo in one secret.

I thought both were going to appear in episode 2 and onward ones?

**Comment by MatthewTheGlutton** [comment]
Is there any reason to keep C1 limited to Doom shareware stuff?

**Comment by FredBezies** [comment]
Well, it is just to follow the rules set by id here. By the way, providing cells without any weapon to use them, is it logical?

**Comment by MatthewTheGlutton** [comment]
Last I heard there weren't going to be more efforts to put out a "shareware version" of Freedoom so there's no longer any rationale for such a restriction except maybe the higher-stakes-second-episode storytelling formula.

I haven't played C1 in its entirety - is there a plasma rifle on an earlier level? If there is then the cells in M8 would make sense.

**Comment by FredBezies** [comment]
I understand more why we can find both cells and "lost souls".

And I did not find any plasma rifle in episode 1. I did not found all secrets too :D

**Comment by chungy** [comment]
> Is there any reason to keep C1 limited to Doom shareware stuff?

Indeed there is not. We can use anything in C1 :P

**Comment by guynamederick** [comment]
Personally, I'm fine with cell ammo in later levels, makes it feel better to carry onto your weapons in a continuous playthrough. The polaric energy cannon can stay in the chapter, it's a secret weapon so it won't break a regular run. Dead flares could probably be introduced and placed better, but they can stay in the chapter.

**Comment by FredBezies** [comment]
Well... In which level the polaric gun is hidden? Did not find it. So far, so good. Will play episode 2 tomorrow. I need to play some Doom to change my mind...

**Comment by Proluiz** [comment]
e1m6
polaric is located there

**Comment by Xindage** [comment]
This should be closed no?
