### ISSUE TITLE
C1M5: Too long and complex

### ISSUE THREAD

**Issue by guynamederick** [freedoom/freedoom#639]
Some players dislike C1M5 for being a long level and confusing with where to go, especially compared to what came before it. Being the 5th level most players will touch, the level might need to be simplified or revamped to fit between C1M4 and C1M6 better. Difficulty could also be reduced while at it.

**Comment by mc776** [comment]
Is this about the current E1M9 (the one that starts with the unmarked doors and the zombiemen that immediately appear without warning or teleport fog)?

**Comment by Calinou** [comment]
> Is this about the current E1M9 (the one that starts with the unmarked doors and the zombiemen that immediately appear without warning or teleport fog)?

No, it's referring to the current C1M5. I still find this level quite long and confusing if I haven't touched Freedoom in a while.

**Comment by mc776** [comment]
Just to be 100% clear, we're talking about this map, with the unfortunately obscure red key and backtracking to the red door near the entrance:
![e1m5](https://user-images.githubusercontent.com/24984517/219824656-33b51461-10c1-4b44-b22f-0a35ab80673f.jpg)

and not this much larger one, with the multiple unmarked key doors, disorienting monster-spawning tricks, deceptively impassible windows and unreadable snarl of linedefs in the automap?
![e1m9](https://user-images.githubusercontent.com/24984517/219824665-b96a3963-013f-4b03-9863-af6749f33cdd.jpg)

**Comment by Calinou** [comment]
> Just to be 100% clear, we're talking about this map, with the unfortunately obscure red key and backtracking to the red door near the entrance:

I'm not talking about that one.

> and not this much larger one, with the multiple unmarked key doors, disorienting monster-spawning tricks, deceptively impassible windows and unreadable snarl of linedefs in the automap?

I'm talking about this one.

**Comment by mc776** [comment]
Any comments on #869 ? I've made a few aesthetic changes and hopefully jump-proofed things.

**Comment by Xindage** [comment]
alright, thanks
