### ISSUE TITLE
Hit Indicator

### ISSUE THREAD

**Issue by ConsumingCritic** [freedoom/freedoom#644]
I wanted to say that I enjoy _Freedoom_ and appreciate the direction of the free game's development. and its endeavor for compatibility with the original _Doom_ engine. I have considered contributing to the project, so it should come as no surprise that I do have a suggestion to make.

I was wondering what you all make of hit indicators. It may be the wrong term to describe them, but hit indicators are graphical elements that many first-person shooters employ to indicate that the player-controlled character has received damage. Some of them like _Freedoom_ display a flashing red screen as the indicator, but some others also use an indicator that points where the player received damage. For example, an arrow that points up means that the player was attacked by some offender in front of them, and an arrow that points down-right means they were attacked from the right side of behind.

I think this would be a good idea because players know that they are hit but sometimes wonder where the damage came from. In the real world in my case, I would certainly know where it came from, but since this game flashes only red as the indicator, I may not know immediately. I do not know about the other players, but I find that it diminishes my experience. Perhaps having a directional indicator may diminish the experience of some other players (I do not know why it would).

Anyway, I have created a simple bottom graphic as the provisional directional hit indicator, both in its original SVG and PNG forms. The graphic was originally created using Inkscape, another free program used to draw vector graphics, and since GitHub would not allow SVG attachments, I have put it in ZIP (also attached at the bottom). My idea is that if implemented, whenever the player character receives damage, the center of the screen would display the graphic, which would rotate to point to the source of the damage. It would be shown briefly before fading away. If you think my proposal would benefit the game, please share your thoughts. My hope is that my ideas are good enough to contribute something worthwhile to this project.

As said before, here is the graphic in its vector and raster forms:

[hit_indicator.zip](https://github.com/freedoom/freedoom/files/3883015/hit_indicator.zip)
![hit_indicator](https://user-images.githubusercontent.com/58091701/69486551-8c0bb880-0e12-11ea-8774-08c80399161c.png)

**Comment by MatthewTheGlutton** [comment]
Freedoom does not have any additional gameplay elements that can't be used in vanilla Doom.

Besides, that's what the mugshot is for.

**Comment by ConsumingCritic** [comment]
Oh. I must have missed the part where the project does not discriminate against the original vanilla engine by boasting such elements. I did read that part, but I might have misinterpreted it.

Also, do you mean to tell me that the avatar at the bottom already does that (by turning his head to the direction of the damage)? How did I miss that?

**Comment by guynamederick** [comment]
I suppose but when getting hit by multiple enemies from several directions, the mugshot of the marine turning his head would swap left and right rapidly which can make the benefit somewhat lost, especially once the screen starts getting pretty bloody. If taking too much damage, then the "OUCH" will take presence until the player runs away or manages to kill every monster damaging them. Vanilla has a bug where the "OUCH" face does not show up when taking 20% damage at once, instead it appears when you get more than 20% health after taking a hit. But again, I suppose it's no harm to mention.

**Comment by ConsumingCritic** [comment]
We do not have to change it. I am just wondering whether that change would be the most appropriate. I do not want it to be verbose and unintuitively complicated to understand; at the same time, I do not want it to be so simplified that it neglects noteworthy details. Maybe the change is satisfactory, but I definitely prefer to use simple language such as "Also used to locate the direction of received damage."

Regardless, I agree that it would not make this game _Freedoom_ if we were to change it so much that it vaguely resembles the 1993 classic. That clearly does not fit within the spirit of this project. Fortunately, I do have another suggestion that is being saved for when it is done. It is not a new gameplay feature, but rather a MIDI tune that is is mid-tempo and fits within the rock genre. When I finish that, maybe I will share that with the hope that it fits this game's style.

**Comment by MatthewTheGlutton** [comment]
Suggestion: read more, play more, write less.

**Comment by ConsumingCritic** [comment]
I do not object to the above suggestion. As I have said, I hope to prepare my MIDI tune and submit it for review. I have closed this issue as an archived discussion for any future reference, and thanks for the civil feedback.
