### ISSUE TITLE
E1M7 has an section that inflicts damage despite looking safe

### ISSUE THREAD

**Issue by YeldhamDev** [freedoom/freedoom#649]
**Freedoom 1** v0.12.0
**GZDoom** v4.2.3

An section on the map **E1M7** has a section that, despite looking completely safe, damages you:
![Screenshot_20191126_155748](https://user-images.githubusercontent.com/30739239/69663939-3d168b00-107f-11ea-9a7a-4f8bbea65ef4.png)
![Screenshot_20191126_155809](https://user-images.githubusercontent.com/30739239/69663942-3e47b800-107f-11ea-8084-c539fe8eefc3.png)

**Comment by Xindage** [comment]
it was fixed in #702
