### ISSUE TITLE
C4M2: Thing 683 (Teleport Destination) is marked Multiplayer-Only

### ISSUE THREAD

**Issue by maxmanium** [freedoom/freedoom#652]
This teleporter that opens doesn't work as a result:

![DOOM0000](https://user-images.githubusercontent.com/58398531/69917899-bf60cf80-1430-11ea-971d-e12f03811b30.png)

**Comment by perryprog** [comment]
I just realized you opened an issue regarding this, I forgot to check.

This is fixed by #692.
