### ISSUE TITLE
Either the freedoom-x.x.x.tar.xz or freedoom-x.x.x.zip archives provided on the release page contains the freedoom source instead of the compiled iwads. And I can't remember which one.

### ISSUE THREAD

**Issue by ElonSatoshi** [freedoom/freedoom#666]
I'm downloading the .zip archive and hoping it's the tarball that has the source. But this is an issue since it's not clear which is which.

Please put "-src" in the filename of the one with the source, so that people downloading from the github releases page can tell the difference.

**Comment by chungy** [comment]
The compiled IWADs are always in the Zip files and linked from the website: https://freedoom.github.io/download.html

It is common practice in open source that tar files are source code, and it is not common practice to mark file names with "-src".
