### ISSUE TITLE
bootstrap/doom2.wad is a BLOB

### ISSUE THREAD

**Issue by fabiangreffrath** [freedoom/freedoom#67]
Hi there,

as it currently stands, bootstrap/doom2.wad is just a BLOB. I mean, there is a README file explaining how to reproduce it, but no actual rule to do so. I know that there is a circular dependency with the actual freedoom.wad, because of the missing PLAYPAL lump, but could we just please assume that deutex works and add such a rule?

Thanks!

Fabian

**Comment by NickZ** [comment]
rjy's pull request resolved this.
