### ISSUE TITLE
Player can straferun into unescapable area in C2M9

### ISSUE THREAD

**Issue by Calinou** [freedoom/freedoom#673]
**Freedoom version:** 0.12.1

On C2M9, the player can straferun into an unescapable area that doesn't deal damage. The player will be forced to load a previous save to continue. I suppose this can be fixed by making the red wall's linedef impassible.

Tested on GZDoom 4.4-pre, but it should be possible with Crispy Doom as well.

### Straferun from here, make sure not to touch the wall while airborne

![Screenshot_Doom_20200315_123430](https://user-images.githubusercontent.com/180032/76700666-132eb600-66ba-11ea-89a8-21ab23379cd8.png)

### After entering the unescapable area

![Screenshot_Doom_20200315_123444](https://user-images.githubusercontent.com/180032/76700669-188c0080-66ba-11ea-9ae7-7e8f52651268.png)

**Comment by Proluiz** [comment]
i've a better idea, i cant put it as impassible since it'll block the cacodemons too, so leave it as that for right now. 03/17 i'll come with a fix.

**Comment by BethOfDeath** [comment]
I feel like it was forgotten to close this issue after closing the pull request? Or is there still a problem?
