### ISSUE TITLE
Change the music track for MAP07

### ISSUE THREAD

**Issue by Mortrixs19** [freedoom/freedoom#675]
Since Map07 is now completely I think it's a proper moment to change the current track for a new track since the current one doesn't fit the level.

As the author I think that this removed music from Map26(0.11.3) Fits the map perfectly it's an original track composed for freedoom (Not by me) that was removed because it didn't fit in Map26.

[Midi-MAP07.zip](https://github.com/freedoom/freedoom/files/4389035/Midi-MAP07.zip)

**Comment by DPstudroid** [comment]
Well, as a musician, it'll be my pleasure to make a track for MAP07, the current one is monotone and sometimes even annoying, and sure 0.11.3 MAP26 could fit, but I'm sure I could come up whit something better,  still let me know what you think?

**Comment by mc776** [comment]
omg yes please, this is so, so, *so* much better than the current map07 music

Who did this?
