### ISSUE TITLE
Credit

### ISSUE THREAD

**Issue by Ajanddino** [freedoom/freedoom#676]
Hi I was looking at the credits and noticed I wasn't there. Awhile ago I wrote a original track for Freedoom (C2M8).  It would mean a lot to me if I could be added to the credits for my song.
Here is a link of when I posted the song
https://github.com/freedoom/freedoom/pull/549
-Anthony Pierce
ajanddino@gmail.com

**Comment by Xindage** [comment]
You're already there. https://github.com/freedoom/freedoom/blob/master/CREDITS#L825
