### ISSUE TITLE
Suggestion: fix super shotgun flash timing

### ISSUE THREAD

**Issue by maxmanium** [freedoom/freedoom#678]
Since there is already a DEHACKED patch in the wad, I think it'd be worthwhile to fix this bug, where the two flash frames last 5 and 4 frames, respectively, instead of 4 and 3.

**Comment by MatthewTheGlutton** [comment]
This is asking for trouble with compatibility with virtually anything else.

**Comment by maxmanium** [comment]
> This is asking for trouble with compatibility with virtually anything else.

Um... how?

**Comment by guynamederick** [comment]
> This is asking for trouble with compatibility with virtually anything else.

I have used the Minor Sprite Fixing project for Doom 1/2 and I haven't seem to run into compatibility issues related to the Super Shotgun frames. Then again, I run the mod before loading other addons, so if anyone could find cases where changing the Super Shotgun frames causes incompatibility with sprite mods, do make a post here.

**Comment by maxmanium** [comment]
> Then again, I run the mod before loading other addons

Exactly, if this were included in the IWAD DEHACKED lump it shouldn't cause any issues as it would just be overridden by any other modifications.

**Comment by MatthewTheGlutton** [comment]
Now that I think further about how DEHACKED patches are treated, I think I'll rescind this objection, though it does *feel* extraneous...

**Comment by fabiangreffrath** [comment]
I have already hard-coded this into Crispy Doom ages ago, and it was done alike in MBF, without any compatibility issues.

**Comment by Blastfrog** [comment]
Eh, it might not hurt, as it's cosmetic only and can be overriden by other dehacked files.

While nobody mentioned sounds in this thread, there was a brief discussion on the Discord about reassigning sounds and I think that's a step too far. Cosmetic only, sure, but cosmetic tweaks shouldn't be to change what content is even used, but rather to fix objective errors such as bright flags not being on or gun flash timing being out of sync with the underlying weapon animation.

**Comment by AXDOOMER** [comment]
> I think it'd be worthwhile to fix this bug, where the two flash frames last 5 and 4 frames, respectively, instead of 4 and 3.

If you want to fix this correctly, change the frame that lasts 5 tics to 4, but don't change 4 to 3. If you shorten both frames, then you make the fire animation too short.

**Comment by mc776** [comment]
[TIL GZDoom also fixes this internally.](https://github.com/ZDoom/gzdoom/blob/eb94f81a83294024bf87fba8d437042fc07eba7c/wadsrc/static/zscript/actors/doom/weaponssg.zs#L46)

**Comment by mc776** [comment]
So does anyone actually know of any mod that uses frames 47 and 48 (at all, let alone in a really timing-sensitive way), or is the objection purely theoretical?

**Comment by mc776** [comment]
The other possible way to fix this is to have the big flash be the first frame, and have the second frame be blank.* Do this with both shotgun and we end up with all bullet weapons having a single frame for their flashes, though the pistol would be significantly longer (5 SSG, 4 shotgun, 4 chaingun (but always shown 2 at a time), 7 pistol) and we lose the animation that enhances the visibility of the blast at the expense of verisimilitude (and, in my opinion, "punch").

Anyone else got any thoughts on this?


* having the second frame be the flash fading looks really, really shitty, just because (a) it's fullbright and (b) we really don't have enough frames to suggest both motion and rapid change in colour:
![DOOM00](https://user-images.githubusercontent.com/24984517/226207519-c9771e28-2e9c-405d-9e83-12f44b4f5a07.png)

**Comment by maxmanium** [comment]
@mc776 I believe this is the case for all weapons EXCEPT SSG, actually. The muzzle flash frames have a duration which is 1 tic longer than the frame it overlays. I’m not sure how it works but changing it to match does cause it to disappear verrryyyyy slightly before the next frame displays. Strobe light effect is probably because it is calling A_Light0 every 3 tics which it doesn’t get a chance to when it lasts 4 tics.

**Comment by mc776** [comment]
After all these years we've finally found the use case that creates a problem: #1151
