### ISSUE TITLE
Episode VS. Chapter

### ISSUE THREAD

**Issue by Blastfrog** [freedoom/freedoom#682]
I think there is no good reason to call episodes "chapters". id, nor Zenimax own the word, nor can they reasonably or legally claim to. Episode is a very common and well understood term in games, and calling them "chapters" for the sake of being different serves little other purpose, and only serves to add to needless confusion. Not to mention, we can't even change the actual lump names of Phase 1 maps, we call them "CxMx" but in reality they're "ExMx" and always will be.

Might as well revert to "episode" for many reasons, in my view.

**Comment by chungy** [comment]
This is probably a good idea.

**Comment by Blastfrog** [comment]
Also, an addendum:

An episode, like in TV, is usually a self-contained entry with a clear beginning, middle and end. A chapter, like in a book, is usually just a subdivision of one whole entry.

In games, these terms are traditionally used in much the same way. The Marathon games have a Doom 2 style level structure, and they call their equivalent to clusters "chapters." And then there are countless examples of episodic games, Half-Life 2 being a well-known example.

If we're going to be calling anything "chapters" in Freedoom, the term would be more aptly suited to Phase 2's level segments, rather than Phase 1's level segments.

**Comment by fragglet** [comment]
Fair enough, if you'd like to put in the work to do this then go right ahead.

**Comment by Ferk** [comment]
ZDoom ports also get confused with current naming, since they expect the "ExMx" and strip it, only to re-add it in a more controlled way.

So Freedoom map name in ZDoom looks like "E1M1: C1M1: Outer Prison" with a confusing double prefix.

**Comment by guynamederick** [comment]
With what Ferk has mentioned, I think this only gives more reasons to revert back to Episode if it means some ports having this map name issue. Considering the map lumps are still ExMy in the files as you pointed out, I agree with you that "chapter" only adds confusion.

**Comment by MatthewTheGlutton** [comment]
So what exactly needs to be changed? DEHACKED, BUILDCFG, anything else?
