### ISSUE TITLE
We must change Double Impact?

### ISSUE THREAD

**Issue by P41R47** [freedoom/freedoom#683]
Now that Double Impact is a canon add-on of the new Unity Classic Doom, is alright to have Double Impact to have it as an Episode for Freedoom: Phase 1?

**Comment by Blastfrog** [comment]
It was donated by the creators to the Freedoom project, so yes, we can have it. I have no idea what "Unity Classic Doom" even is, but I hope they have permission too, or if they got it from Freedoom, that they're following the license terms.

But yeah, the Freedoom project has nothing to be concerned about here.

**Comment by P41R47** [comment]
> It was donated by the creators to the Freedoom project, so yes, we can have it. I have no idea what "Unity Classic Doom" even is, but I hope they have permission too, or if they got it from Freedoom, that they're following the license terms.
> 
> But yeah, the Freedoom project has nothing to be concerned about here.

Sorry, i misspeled it, i mean this one:
https://doomwiki.org/wiki/Doom_Classic_Unity_port

I know that Rottking and Ralphis donate it, but the owners of the Doom IP released Double Impact as an official add-on for their new port.
I don't know what could come with that, or if this official add-on makes them the copyright holders of Double Impact as add-on.
I just brought something to the table that, i think, could have some repercussion in the future.
@fragglet surely know more if this could be a problem or not.

**Comment by Blastfrog** [comment]
Okay, but did _they_ get permission to use it, or did they just swipe it? They could swipe it, but only as long as they follow the Freedoom license terms. If they're not, they're actually stepping on _our_ toes and not the other way around.

**Comment by P41R47** [comment]
> Okay, but did _they_ get permission to use it, or did they just swipe it? They could swipe it, but only as long as they follow the Freedoom license terms. If they're not, they're actually stepping on _our_ toes and not the other way around.

They contacted Rottking and Ralphis, and the authors give them their approval. They made it the proper way. Even credit them as the creators of the mapset.
I know what our licence terms explicity tells. But the mapset was released as a Freedoom episode and as a legal and official DLC, in both cases approved by the authors themselves.
I'm not talking who is the fault here, i'm just talking if this could bring some complications, because we are offering for free something that one must pay to been able to play.
The original wad is not the same thing, as to play it, one need a legal copy of Doom, or a copy of Freedoom. But Freedoom already have that same mapset for free...

**Comment by Blastfrog** [comment]
In that case, no party involved has anything to be concerned about.

**Comment by chungy** [comment]
I am pretty happy with Double Impact in the slot it's in. Given how much love and care the first three chapters still need, Double Impact doesn't go high on my priority list.

**Comment by P41R47** [comment]
I am too, i love Double Impact as a Freedoom episode, but thats not what i'm talking about. I'm just talking about if there could be a legal complication here now that the wads is official downloadable content.
I'm not a lawyer but i think that WE can be called thieves and have problems, even if WE and only WE know, even if it is specified on Freedoom manual and legal .txt, that this set of maps were offered by the authors themselves.

I want Double Impact on Freedoom.

**Comment by Calinou** [comment]
@P41R47 The Double Impact authors gave Freedoom explicit permission to redistribute the levels under the BSD 3-clause license. Bethesda can't revoke this, since open source license grants are non-revokable by design.

**Comment by P41R47** [comment]
Fair enough.
I just brought this in case some body doesn't know about what could happend.
Hope if something ever happend, it could be manegeable in the right terms and we get the winning hand in the process.

**Comment by Blastfrog** [comment]
Your concern is understandable and I appreciate that you're trying to look out for us.

I suppose there is some small risk of Zenimax's lawyers not doing their research and jumping the gun, but it's likely they'd back off after being informed that we have every right to have Double Impact as well. If it came down to a court case, they would undoubtedly lose.
