### ISSUE TITLE
C1M4: A switch doesn't work in vanilla Doom

### ISSUE THREAD

**Issue by AXDOOMER** [freedoom/freedoom#688]
This is the switch:
![DOOM00](https://user-images.githubusercontent.com/6194072/83320879-658f6580-a219-11ea-8bc0-efe038b02181.PNG)

The switch is in this area:
![image](https://user-images.githubusercontent.com/6194072/83320902-91125000-a219-11ea-8d86-3bacfb644a74.png)

I got this IWAD from [here](http://freedoom.soulsphere.org/) yesterday. 

I haven't tested further to see if the whole level was completable.

**Comment by perryprog** [comment]
What part of it isn't working? It looks like it was toggled as the screen is off (it's on by default there), and it should open a door just barely south of where your screenshot ends.

**Comment by AXDOOMER** [comment]
You're right. It's probably because this area is dark so I couldn't see that it was activated by default. I jumped to the conclusion that this map was vanilla incompatible.
