### ISSUE TITLE
Player can run into an unescapeable area in C3M5 - Phase 1

### ISSUE THREAD

**Issue by ZeroTheRed** [freedoom/freedoom#700]
**Source port** : GZDoom v4.3.3
**Version** : FreeDoom Phase 1 v0.12.1

In C3M5 (Oblation Temple), once the player enters the first building and climbs up on the left platform, he can run out of the window (where the red pillar is located). While doing so, he can walk over the tree and fall into the rock structure to the player's right, forcing the player to either noclip his way out or load a previous save. I suggest marking Linedef 1913 as impassable.

![Screenshot_Doom_20200818_091015](https://user-images.githubusercontent.com/67111435/90495083-d03da680-e161-11ea-997b-84500c863265.png)

**Comment by Proluiz** [comment]
Noted, thanks for the bug report.

**Comment by Xindage** [comment]
On my way to fix it in a minute.
![Screenshot_Doom_20210725_111823](https://user-images.githubusercontent.com/6380147/126902385-296089e0-39a4-406d-8368-b8b4a46ded0a.png)
![Screenshot_Doom_20210725_111812](https://user-images.githubusercontent.com/6380147/126902389-9d1b08ea-63d2-4759-9111-a3cd6e40a0e7.png)
