### ISSUE TITLE
Freedoom 2 Map 20 - Player 1 Start position placed twice on the map

### ISSUE THREAD

**Issue by swc132994** [freedoom/freedoom#707]
I am playing Freedoom 2 Map 20 with a mod that uses stamina. I found that on this level the stamina shoots down. I first thought it was a problem with the mod. However, I later found that it is due the Player1 Start position being placed on the map twice.

I did a test and removed the other player1 start position and the mod ran fine.

![image](https://user-images.githubusercontent.com/10770202/97238996-bba31c00-183e-11eb-8811-67f3468060da.png)

**Comment by Xindage** [comment]
from what i can see just by looking in the screenshot is seems to be a leftover from the boom features, "voodoo dolls" i think it can be deleted.

**Comment by BethOfDeath** [comment]
#710 should fix this, though without the mod in question to test it with I can't be sure.

**Comment by swc132994** [comment]
The mod i used is Brutal doom 64 v2 patched. This is my own attempt at patching the main Brutal Doom 64 v2 mod.

Link:
https://www.moddb.com/mods/brutal-doom-64/downloads/brutal-doom-64-v2-patched/page/2#comments

**Comment by Catoptromancy** [comment]
It looks like there is already a pull request for this, but I also removed the unneed area as well. Simplified a nearby gate. A few small texture fixes too. Playtested to exit in choco with -nomonsters. 
http://www.geocities.ws/catodemos/freedoom/catoptromancy/2021/map20_002.wad

**Comment by mc776** [comment]
This should be closed.

**Comment by mc776** [comment]
> This should be closed.

^^^

**Comment by swc132994** [comment]
I didn't realise I could close an issue. My apologies.
