### ISSUE TITLE
Map 10 has shadow on start point

### ISSUE THREAD

**Issue by crabcrabcam** [freedoom/freedoom#714]
![image](https://user-images.githubusercontent.com/13933264/102617406-0b141300-4131-11eb-9602-e1243e552a52.png)

Tested in prboom-plus (dsda-doom fork), crispy-doom, and gzdoom. 

The shadow flickers in and out, even while staying still. (I'm firing as ctrl is part of my screenshot bind, and is also shoot)

**Comment by Xindage** [comment]
yes i remember this spawn point it's was based in plutonia start, prob it's still or it's a leftover from the previous versions.

**Comment by mc776** [comment]
I always thought this was intentional, just... weird.

Should it just have the lighting changed to match the surrounding area, or do we even want to keep the Plutonia entrances and exits at all?

**Comment by Calinou** [comment]
I think it's a neat effect, but I wouldn't mind going for a different spawn design where flickering would be placed *around* the initial player position, rather than exactly on it.

**Comment by mc776** [comment]
Changing the sector special to 17 (light flicker) gives us a nice subtle not-entirely-perfect-teleport-pad effect.

**Comment by mc776** [comment]
Since we're making some changes here, does the way that landing pad fails to tile properly bother anyone else? For all other aesthetic considerations it seems to be the best flat to use but... oof.

**Comment by mc776** [comment]
Sorry, just had to deal with this one other little aesthetic thing that's bugged me forever about this map - the way the water tunnel just kinda *ends* like that.

Here's a viny waterfall instead:
![_](https://user-images.githubusercontent.com/24984517/215050524-ce4b64f3-dfac-4d6d-806b-5e67d0914e0f.jpg)

**Comment by mc776** [comment]
I think this can be closed.
