### ISSUE TITLE
Compatibility for libre quake, libre quake 2 and possibly freedoom 3

### ISSUE THREAD

**Issue by allenwrench** [freedoom/freedoom#715]
I'm looking to see if the sprites could be modified for libre quake, libre quake 2 if that's possible and freedoom 3 based on id tech 4. Bsd I think allows that stuff but wouldn't creative commons accomplish that much better for licensing?

**Comment by Calinou** [comment]
LibreQuake also uses a BSD 3-clause license, but they don't seem interested in using Freedoom assets anyway. (They have a different color palette too.)

**Comment by chungy** [comment]
All the assets in Freedoom are available under the terms of the [license](https://github.com/freedoom/freedoom/blob/master/COPYING.adoc), any other project could use them by giving credit and including the license text along with them.

Also there is no such thing as "Freedoom 3" and please do not use our project name in the name of some other project.

**Comment by MissLav** [comment]
> 
> 
> [LibreQuake](https://github.com/MissLav/LibreQuake) uses the BSD 3-clause license just like Freedoom, but they don't seem interested in using Freedoom assets anyway. (They have a different color palette too.)
> 
> Is there any LibreQuake2 or Freedoom 3 project going on?

lol we do use Freedoom Assets 
we have a converted texture wad

**Comment by MissLav** [comment]
also who making librequake 2??? 

"Also there is no such thing as "Freedoom 3" and please do not use our project name in the name of some other project."

this applies for Librequake 2 as well. don't use our project name for some other project
