### ISSUE TITLE
Problem with C3M7 solo-net and multiplayer

### ISSUE THREAD

**Issue by Hector577** [freedoom/freedoom#721]
I was playing freedoom phase 1 co-op. When my buddy and I reached the blue door in C3M7 and climbed up the stairs we found four vases that block our path. And it's a problem because there's a switch there that is necessary to proceed. 
![Captura de pantalla de 2021-03-15 23-43-09](https://user-images.githubusercontent.com/80479550/111409368-70c65b80-869c-11eb-9eba-da5b80fc2752.png)

**Comment by Xindage** [comment]
confirmed, it happens in 2 other places as well, i'm going to fix them after cheking an older version of this map.
