### ISSUE TITLE
MAP11 too similar to Doom 2?

### ISSUE THREAD

**Issue by milasudril** [freedoom/freedoom#732]
MAP11 contains some locations that are very similar to MAP11 from Doom 2. It is like the original, but larger and somewhat shuffled. In particular, the section behind the yellow door. It also uses the same monsters for the first part. The second part in the original MAP has been moved in FreeDoom to the blue key section. The Arch-Vile appearance is identical to the original map. What do you think, should these parts of the map be reworked?

**Comment by mc776** [comment]
Screenshots?

**Comment by Calinou** [comment]
It's quite similar (and definitely "rings a bell" when playing Freedoom), but it doesn't feel so close as to be problematic.

### Freedoom MAP11 (behind the yellow key door)

![freedoom webp](https://user-images.githubusercontent.com/180032/214812838-9c0e1de4-f164-49c9-9e03-0243b9ff34a9.png)

### Doom 2 MAP11 (room on your right after spawning)

![doom2 webp](https://user-images.githubusercontent.com/180032/214812857-05e35f56-2f8b-44bc-9feb-fa897162e054.png)

**Comment by selliott512** [comment]
I tend to agree. If it were up to me there would not be any particular similarity between any FD map and the corresponding (or any, actually) Doom 1/2 map. This is both a matter of principal (that FD wishes to demonstrate that it is its own independent game) and to minimize risk of intellectual property trouble.

**Comment by mc776** [comment]
Now that I'm taking a closer look... yeah, both the twin towers and the bi-directional bars feel way too much like D2 homages now.

If anyone's got a really good mid-tier-difficulty map in the works, designed from the ground up to be vanilla compatible, this might be high priority to replace.

**Comment by milasudril** [comment]
@mc776 Perhaps you do not need to redo the entire map. I would simply redraw this area. Also, the map has a nearly identical Arch-Vile encounter to that in doom 2. You find it behind the blue door (Sector 144).

**Comment by mc776** [comment]
I'm working on a massive revision to this map. The id-style twin tower room is being overhauled into a fortified entry gate and you do not open the entrance within by going inside, accessing the symmetrical lifts and hitting two switches. That combined with the colour should hopefully mitigate any remaining idness.

The sliding bars beyond that have also been replaced with random machinery to still trip the player up without providing a hard barrier.

The stuff behind the blue key door is replaced entirely (thanks to @Xindage for this re-do almost entirely from scratch) - there's still an archvile but it's definitely not that box reveal.

Once I've gotten rid of that giant skull switch chamber behind the former tower panels I think it might be ready for testing.

**Comment by mc776** [comment]
Can this be closed now, or are those bits still too doominous?
