### ISSUE TITLE
Crush when i open the door

### ISSUE THREAD

**Issue by MishaWeb2007** [freedoom/freedoom#733]
Today i opened freedoom, chosee freedoom2 , add pk3 file brutal and wad file original doom2. It is was "refueling base" map. I go to one door, click to open it, and i have noise sound from game and crush. I can show video with my problem.

Thank you for free game :-)

**Comment by mc776** [comment]
What program are you running for this?

**Comment by MishaWeb2007** [comment]
> What program are you running for this?

https://play.google.com/store/apps/details?id=net.nullsum.freedoom

**Comment by mc776** [comment]
That app is not part of this project - this project is just the data for the game but not any specific program to run it.

No idea how to reach the developer of that program, though, and I don't see anyone in the reviews indicating they had similar problems.

Does it work on a total uninstall and reinstall, or on another phone?
