### ISSUE TITLE
Phase 1 Demo 2 desyncs

### ISSUE THREAD

**Issue by northivanastan** [freedoom/freedoom#737]
Testing the latest build of Freedoom, I found that the internal DEMO2 for Phase 1 desynced a few seconds in. I am not sure what change caused this, but in any case we probably need a new DEMO2.

I recorded a demo of E2M3 on the latest build recently which is probably suitable, but I'm too lazy to PR it at the moment.

**Comment by chungy** [comment]
Demos should be expected to break during the development cycle and they aren't necessary to be working outside of release time.
