### ISSUE TITLE
IDEA: Use Open sourced romero assets

### ISSUE THREAD

**Issue by abcd1234-byte** [freedoom/freedoom#738]
https://github.com/fragglet/RomeroDoomDump
John romero has open sourced things many years ago under gpl. OpenArena used Quake maps, why cant we use Doom maps?

**Comment by chungy** [comment]
I don't think John Romero actually has any legal power over the files. Just because he released them doesn't really mean they're open source.

Plus they probably don't mesh thematically with Freedoom.

**Comment by fragglet** [comment]
Closing for the same reason that @chungy gave.
