### ISSUE TITLE
Donate Cash/Coin?

### ISSUE THREAD

**Issue by david-a-redick** [freedoom/freedoom#739]
I was looking at the [help freedoom](https://freedoom.github.io/help.html) page but I didn't see any mention of donating money to the project.  Are you accepting that kind of donation?

**Comment by chungy** [comment]
We are not and not in a position of hiring asset designers to do so, nor do we currently use for-pay hosting services that make it necessary.

I appreciate the desire to financially support the project, but we don't have a present need for it.
