### ISSUE TITLE
Visplane Overflow in Map 12

### ISSUE THREAD

**Issue by Hector577** [freedoom/freedoom#742]
When using Chocolate-Doom in Map 12, a visplane overflow occurs in the slime area behind the starting room, more specifically here (Screenshot taken in crispy-doom)
![Captura de pantalla de 2021-06-26 18-13-57](https://user-images.githubusercontent.com/80479550/123528168-17ae9080-d6ab-11eb-9dcb-e2e16e10d3a0.png)

**Comment by HelloThereAll** [comment]
I'll go poking around to see what might be causing this many visplanes to be drawn

**Comment by HelloThereAll** [comment]
![vpp](https://user-images.githubusercontent.com/72332061/124240631-898a3e00-dae0-11eb-883e-3e0ecbd7fa2a.png)
I found our problem spot, it appears to peak at around 158 visplanes out of 128. I'd like to not there were a lot of sectors there for seemingly no reason.

**Comment by Xindage** [comment]
I've already heard about what cause vpo I'd nor the amount of sectors, 2 sectors can as well vpo wirh the right shape.
What can be causing the error there may be the excess of geometry on screen at once.

**Comment by HelloThereAll** [comment]
![vp2](https://user-images.githubusercontent.com/72332061/124296036-266bcc00-db1f-11eb-947a-a8bbd4ef185d.png)
Alright, I, ve made a version of the map where I've pretty much solved this problem. Also in my findings, the area by the southern rail is visplane hell.

**Comment by HelloThereAll** [comment]
I'm convinced that our current map12 is a lost cause. Too much geometry, no practical way to go about removing it, not to mention weird visual bugs while playing the map in chocolate doom.

**Comment by Xindage** [comment]
simplify the map, if you guys noticed in episode 4 channel in discord i saved an e4m1 map too and it was a visplane hell too.

**Comment by Xindage** [comment]
Fixed on commit 0ea4a09825236a2428b19cf442c8722e73879ef0
