### ISSUE TITLE
Add graphic lump that covers a Crispy Doom lump

### ISSUE THREAD

**Issue by Some1NamedNate** [freedoom/freedoom#743]
In the source code for Crispy Doom is a lump called `M_CRISPY` that renders the "Crispness" option in the in-game Options menu.

https://github.com/fabiangreffrath/crispy-doom/blob/524698f7bdd16aa8c97b4a538e8911cef5baa68e/src/doom/m_menu.c#L382

Can you make a graphical lump that covers this?

**Comment by fabiangreffrath** [comment]
This is already there:
https://github.com/freedoom/freedoom/commit/637d2a0b9e89675c3624b5eeafd068a2f5f6dd6f

**Comment by mc776** [comment]
I installed Crispy just to verify this works as intended before closing:
![_](https://github.com/freedoom/freedoom/assets/24984517/a8505c44-8fa3-42fc-b4bb-f0ca8b68ae4e)
