### ISSUE TITLE
Deathmatch not supported well on the Singleplayer Iwads

### ISSUE THREAD

**Issue by Catoptromancy** [freedoom/freedoom#751]
Some maps have few deathmatch starts, minimal weapons, and/or poor placements. Some maps have over 10 deathmatch starts making them a vanilla issue. 

Wadspy results as of July 29, 2021.
http://www.geocities.ws/catodemos/freedoom/catoptromancy/2021/freedoom1-wadspy.txt
http://www.geocities.ws/catodemos/freedoom/catoptromancy/2021/freedoom2-wadspy.txt

**Comment by mc776** [comment]
A lot of the maps are also pretty linear (in terms of flow, not number of options) and pretty clearly not designed with deathmatch in mind. They'll take a lot more than just item and spawn placement to make decent DM maps.

That said, it would be good to make sure they all at least *run* under DM, for those who are just trying things out or appreciate the occasional lopsidedness as an additional challenge.

**Comment by Catoptromancy** [comment]
There are many ways to make maps work in deathmatch. Spawns in walls that open up areas for deathmatch. Walkover teleports to deathmatch tagged teleport destinations. Even standard decorations can be tagged as deathmatch to block players. There are many more things that can be done that only affect deathmatch.

The old MAP07 and current E2M1 do some of these.

**Comment by mc776** [comment]
Do all singleplayer maps have between 4 and 10 DM starts now?

**Comment by Catoptromancy** [comment]
All maps have 4-10 DM starts now. 
Good deathmatch support needs careful placement of spawns and items. Should be the next milestone, more than just having the basic player starts.

**Comment by Xindage** [comment]
Closed as a different approach should be taken for a future version after the next stable (0.13)
