### ISSUE TITLE
Fist cutting off in ultra-wide ports

### ISSUE THREAD

**Issue by colinmahns** [freedoom/freedoom#760]
Using the fists on my ultra-wide display (21:9) causes a cut-off on the fist's graphic assets when playing the WAD in gzdoom. 

Comparing to the source material, Doom handles this new aspect ratio change and stretch much better as the fist is much more centered, coming from around the weapons/health is on the HUD. Freedoom's on the other hand as it's coming from the far right of the screen, isn't able to handle this shift as cleanly. 

![Screenshot from 2021-09-04 21-26-15](https://user-images.githubusercontent.com/1781677/132114339-d8c813c0-50fb-439d-8552-ba0a2e81d554.png)

I opened a new issue as I didn't see any existing issues for this, but this is similar to #95.

**Comment by mc776** [comment]
The only sure way to fix this is with sprites that only cut off at the bottom (similar to what we see in Doom).

There was some discussion about new fist sprites on Discord a few months ago. Did anything come of it?

**Comment by colinmahns** [comment]
I just did a quick search in the Discord, is this what you're referencing @mc776 ? https://discord.com/channels/616148111076884520/692858923660607518/840758020933812264

**Comment by mc776** [comment]
Yes, that was the discussion I had in mind... and it doesn't look like it did get anywhere beyond some bikeshedding about wrist alignment.

**Comment by P41R47** [comment]
now that we are at it.
We can also take of those gloves from it.
The other hands sprites doesn't show any kind of gloves, so, to differentiate again more to the original assets, we should get rid of them here, too.

**Comment by chungy** [comment]
Bottom of the screen is probably the best idea.

**Comment by mc776** [comment]
Fist has brown gloves.
Pistol has no gloves.
Shotgun has no gloves.
SSG has brown gloves.

All other weapons do not show hands.

So right now it's an even split and we could go either way.

Personally I'm in favour of moving towards all gloves because that way people can have custom mugshots and characters with different skin tones and it wouldn't clash or require a recolour.
