### ISSUE TITLE
Freedoom  Phase 2 issues in latest Development build

### ISSUE THREAD

**Issue by uhu68** [freedoom/freedoom#776]
I found the following issues with a current build of Freedoom2 (g1f7e3dde):

1. On MAP11, linedefs 1999 and 2006 are wrongly flagged as "Upper Unpegged".
2. On MAP12, the monsters thing 300, 301 and 518 cannot be killed. This is because the linedefs triggering sector tags 29 and 57 have been removed, compared to v. 0.12.1. Also the steps leading to the Berserk (thing 510) have been removed. I do not know if this was intentional and you are now expected to grep it using an archvile jump. If so, I suggest exchanging its position with the Megasphere (thing 417), since it makes sense that the most valuable item is the hardest to grab.
3. On MAP15, the imp (thing 236) does not teleport and cannot be killed, since the sector releasing it has tag 28, for which there is no linedef. The tag should probably be 30.
4. On MAP22, the cyberdemon does not teleport and cannot be killed, since its teleport destination (thing 104) does not lie in the sector tagged by the teleport line. Tag 14 should be applied to sector 264, not 20.

**Comment by mc776** [comment]
Checking all of these in latest commit now...

Map11: obsolete.

Map15: fixed.

Map22:  fixed.

Map12:
things 300-301 (worm warp): fixed.
thing 518 (western spider): fixed.
thing 510 (zerk): fixed.


I think this can be closed.
