### ISSUE TITLE
Weapons firing frames should be reworked

### ISSUE THREAD

**Issue by AXDOOMER** [freedoom/freedoom#78]
The firing frames of the weapons should be reworked. Some are fully lighted when firing and on some, the light is odd. These should then be tested in a dark sector to see if the light on them looks fine. 

-The back of the pistol is lighted when it fires. The light shouldn't reach this place. 
-On the shotgun and the chaingun, it looks like only the changed pixels of the firing frames were kept and the others were cut. 
-The other weapons, like the plasma gun, the missile launcher and the BFG are fully lighted. 

![3](https://cloud.githubusercontent.com/assets/6194072/3211920/638e0744-ef39-11e3-8bce-04f14f274fca.jpg)
![4](https://cloud.githubusercontent.com/assets/6194072/3211921/63900c1a-ef39-11e3-9af4-dfbbe6c08d00.jpg)
![2](https://cloud.githubusercontent.com/assets/6194072/3211922/639363ec-ef39-11e3-95cd-6e5e245feb0d.jpg)
![1](https://cloud.githubusercontent.com/assets/6194072/3211923/63959608-ef39-11e3-82aa-de1dfba4cd92.jpg)

**Comment by NickZ** [comment]
Resolved with robotdog's and sodaholic's replacements.
