### ISSUE TITLE
License of music/sound effects, usage outside of Freedoom

### ISSUE THREAD

**Issue by Pordrack** [freedoom/freedoom#782]
Hello, me and several classmates have a school project for which we have to make a game on Unity, following a certain theme. We intend to make an FPS and some elements are "hommages" to Doom, as such, and because we have no sound designers, we planned on using musics and sound from Freedoom, to give it a retro-FPS action packed vibe. 
Are we allowed to do it ? If so, do we have to credit the single author of each music/sound, or would a "Every sound comes from Freedoom" be enough ?
Also, I know that the GPL license is a contaminant license, so, would this apply to our case ? Would we have to publish our source  code under GPL license ?

**Comment by Calinou** [comment]
> Are we allowed to do it ? 

Yes

> If so, do we have to credit the single author of each music/sound, or would a "Every sound comes from Freedoom" be enough ?

It's best to credit individual authors for each sound. You can find their names here: https://github.com/freedoom/freedoom/blob/master/CREDITS

Do not contact these authors individually, as you already have permission to use those sounds (even commercially).

> Also, I know that the GPL license is a contaminant license, so, would this apply to our case ? Would we have to publish our source code under GPL license ?

Freedoom assets are under the BSD 3-clause license, not the GPL.

**Comment by Pordrack** [comment]
Thanks a lot, we'll do our best to credit everyone fairly :).
