### ISSUE TITLE
secret exit on Freedoom Phase I Episode 2

### ISSUE THREAD

**Issue by JimFlasch** [freedoom/freedoom#790]
Freedoom Phase I E2M5 should have a secret exit but doesn't (that's the level with E2's secret exit in the original Doom I / Ultimate Doom) and E2M9 has a secret exit, but shouldn't (like the main exit, it leads to E2M6).

**Comment by Xindage** [comment]
this is already know, give us sometime to come with a solution

**Comment by mc776** [comment]
Who's working on it right now?

**Comment by Xindage** [comment]
nobody right now, but if you want details in how you should proceed if you want to take on this issue.

**Comment by andh0g** [comment]
The scrolling green waterfall  in the secret room near the overdrive sphere was ones an exit (x: -700 y: -2900).  This can be seen in map E2M3 in the 0.11.3 release (available at https://github.com/freedoom/freedoom/releases/tag/v0.11.3 , haven't figured out what commit to check out to get this version).

This is not a bad place for the secret exit.  The room is already marked as secret and you need to discover quite a lot of the map to get there.  Maybe change the graphics to FIREBLU1 so it looks like an exit.  Perhaps also give a thought to how to signal a secret exit as opposed to a normal exit.

There are a lot more goodies in the room now than in the 0.11.3 release.  Maybe they were added to make the secret room more interesting when the exit was removed.  Perhaps some of them is not needed any more, e.g., there is already a heavy armour vest on this level.

**Comment by selliott512** [comment]
I have addressed the original comment from JimFlasch:

> Freedoom Phase I E2M5 should have a secret exit but doesn't (that's the level with E2's secret exit in the original 
> Doom I / Ultimate Doom) and E2M9 has a secret exit, but shouldn't (like the main exit, it leads to E2M6).

All levels that should have secret exits now do, and ones that should not do not.

I don't fully understand andh0g's comment, but E2M3 should not have a secret exit, if that's the suggestion. Maybe this issue can be closed.

**Comment by andh0g** [comment]
> I don't fully understand andh0g's comment, but E2M3 should not have a secret exit, if that's the suggestion. Maybe this issue can be closed.

The E2M5 level was in an earlier release placed as level E2M3 and wrongly had a secret exit in the very spot the E2M5 has one now.  It was just a suggestion for the location of the secret exit.  This comment has nothing to do with the level that today is E2M3.  As far as I'm concerned, this issue is resolved.

**Comment by jadenquinn** [comment]
Wait... so there isn't even a way to get to E2M9 through normal gameplay? No wonder I didn't find it...

**Comment by selliott512** [comment]
> Wait... so there isn't even a way to get to E2M9 through normal gameplay? No wonder I didn't find it...

It's been fixed. 
<details>
<summary>To get to E2M9 from E2M5</summary>
Use the green slime portal at the bottom of the map.</details>

**Comment by jadenquinn** [comment]
Ah, ok. Thanks Selliot.

**Comment by mc776** [comment]
I think this can be closed.

**Comment by selliott512** [comment]
I agree.
