### ISSUE TITLE
Phase 2 Map06 staircase lighting looks bad in hardware-accelerated truecolor

### ISSUE THREAD

**Issue by mc776** [freedoom/freedoom#791]
![Screenshot_Doom_20220514_115839](https://user-images.githubusercontent.com/24984517/168444969-4f332223-6d80-4f2c-86bd-fd9a44a18b25.jpg)

It seems like the light levels on the bottom two stairs should be the other way around...

**Comment by fawtytoo** [comment]
Would it though? You do have the gamma turned up in that screenshot, but the 2nd to last step has a "shadow" which is consistent with the walls either side, and the last step has lighting consistent with outside as if that's where it's lit from. Maybe?

**Comment by mc776** [comment]
I have no idea what happened to the gamma on that shot.

I did have similar thoughts when I posted this but ultimately it really makes no sense:

- the closest apparent light source should be that yellow strip.
- that sector is under a solid ceiling, but so is the one right next to it closer to the exit. If the light is coming straight down that it would create a shadow like that, surely that other sector would be similarly affected, but it isn't.
- the rationale for that other sector being brighter is that it's closer to the big open area by the exit. If that's the case, then the light must be coming in at an angle, in which case the suddenly-dark sector wouldn't be the one that's dark but rather one or two of the sectors higher up the stairs; if instead it's being lit by ambient light, then this darker sector wouldn't be that dark to begin with.

I'll post a PR at some point now that I'm a bit more confident about editing maps without breaking everything.

**Comment by mc776** [comment]
forgot to attach these
![whereisthesky](https://user-images.githubusercontent.com/24984517/214116181-faeddc36-54d1-4347-b25b-c1136f08195d.jpg)
![brightersector](https://user-images.githubusercontent.com/24984517/214116186-afbe760f-e71b-4985-a8f7-93e67ebdf16c.jpg)

**Comment by mc776** [comment]
On the other hand, the effect looks *incommensurably* better in vanilla
![_](https://user-images.githubusercontent.com/24984517/214116699-064f3335-0a4a-444b-9964-d84bdaa6836c.png)

**Comment by mc776** [comment]
compared to GZDoom
![_](https://user-images.githubusercontent.com/24984517/214116968-09c55560-d22d-43fd-ad67-f6b0ace17c6a.jpg)

It seems the problem is that the sector closest to the outside is too bright which ruins the effect...

**Comment by fawtytoo** [comment]
Also, the high up "blocks" that have strobe lighting underneath don't fit in with the general lighting scheme. I agree the lighting in that end of the room is wrong.

**Comment by mc776** [comment]
120 (from 128) for the threshold, 112 unchanged for the dark stair, 160 (from 176) for the rest.

The two red low-hanging ceiling lights don't make a whole lot of sense, but they don't *not* make sense either, so unless anyone has any really good ideas I think it's best to keep them as they are.
