### ISSUE TITLE
Suggestion: DMAPINFO

### ISSUE THREAD

**Issue by Some1NamedNate** [freedoom/freedoom#796]
The Freedoom trilogy should have [`DMAPINFO`](https://doomwiki.org/wiki/DMAPINFO) lumps for the Doom Unity port to read in the event that the Freedoom WADs are loaded there.

**Comment by selliott512** [comment]
Given Freedoom's goal to be vanilla compatible what could this lump do for Freedoom? Fredoom wouldn't want to use DMAPINFO make the map behave differently than it does in plain vanilla engines, which would seem to make it less helpful.

**Comment by Some1NamedNate** [comment]
The lump specifies information about the WADs including episode names, map names, and the text screens (i.e. after E1M8 and before MAP07) for the Doom Unity port to utilize.

**Comment by rautamiekka** [comment]
What does it give the port doesn't already do ? The page even says the port will default to vanilla behavior.

**Comment by mc776** [comment]
> What does it give the port doesn't already do ? The page even says the port will default to vanilla behavior.

Two months without an answer...

**Comment by Some1NamedNate** [comment]
It specifies level names and other information for the Unity port to use,
as well as per-episode end text.

**Comment by mc776** [comment]
what does the unity port do with a deh lump?

**Comment by Some1NamedNate** [comment]
It has nothing to do with DeHackEd.

**Comment by Some1NamedNate** [comment]
It actually makes map selection from the Unity port's menus easier.

**Comment by mc776** [comment]
Feel free to post a PR then, because I don't think any other person actively working on Freedoom stuff right now uses this port so they can't test.

**Comment by mc776** [comment]
Seriously not the slightest scrap of respect
![crap](https://github.com/freedoom/freedoom/assets/24984517/728da989-76b6-4074-9b1b-db9c13fc64f3)

There's no point in trying to chase after compatibilit with something that can't even grab the M_SKULL graphics right.
