### ISSUE TITLE
Phase 1, Episode 2, a few issues

### ISSUE THREAD

**Issue by andh0g** [freedoom/freedoom#797]
@Xindage, good update of the levels!

This is a mix between old and new issues.

E2M3: Monsters in the two southernmost "teleportation cages" (about x: -200 y: 800 and x: -200 y: 640) do not wake up when I play, effectively preventing me from getting 100% kill.  I have failed to find a way to wake them up without using any cheat codes.  Note that the monsters in the northern most cage wake up.  Possible fix could be to combine them into one cage but with for monsters impassable lines between.

E2M5: The secret at the stairs in the radioactivity (x: -1800 y: -1100) is hard to find, and more importantly, there is no second chance to search for it.

E2M5 and E2M6: I see no reason why the entrance teleporter should be radioactive.  If it should be, shouldn't it be on all levels in E2?

E2M7: Secret at x: -1900 y:700 is a trap.  There is no way out of it if the door closes without using cheat codes.

E2M7: No reason to change but the clue for the secret at x: -2200 y: -1000 is very high up.  I just want to highlight that it may be differently hard to spot depending on the aspect ratio of the screen.  The area where it is located is large so it should not be a big problem here though (well, I had big problem finding it ;-) but I liked the challenge of finding a way to climb up to the secret).

**Comment by Xindage** [comment]
I'll take a better look when in home

**Comment by Xindage** [comment]
Thanks for the feedback, all fixed
