### ISSUE TITLE
MAP12, switch offsets

### ISSUE THREAD

**Issue by PROPHESSOR** [freedoom/freedoom#800]
Hello
Is it OK?

![image](https://user-images.githubusercontent.com/19251320/175792315-83ec4699-17d6-432a-a749-3f9860fc8c20.png)
![image](https://user-images.githubusercontent.com/19251320/175792326-e2833ce1-d7f0-43ae-afbf-c2182fc4cd84.png)

![image](https://user-images.githubusercontent.com/19251320/175793022-299c13fc-4f93-4988-a6b6-3809d4bd1203.png)
![image](https://user-images.githubusercontent.com/19251320/175793024-2ea97a2e-1a07-4375-9fbc-91ade2440e88.png)

![image](https://user-images.githubusercontent.com/19251320/175793074-9865c4a1-e80c-4760-9140-4148ad15fc21.png)
![image](https://user-images.githubusercontent.com/19251320/175793077-b4577a73-95e8-45ac-b778-f4411f6b1d69.png)

![image](https://user-images.githubusercontent.com/19251320/175793222-2fe2110c-0cb8-475a-a53f-41ab37004f18.png)
![image](https://user-images.githubusercontent.com/19251320/175793224-dedd7272-c317-47a6-8ca0-8120709b46f4.png)

And other switches like these

**Comment by Catoptromancy** [comment]
Current map is a hastily made vanilla version. Map really should be preserved in its boom version elsewhere and replaced in Freedoom.

**Comment by Xindage** [comment]
requires confirmation now.

**Comment by mc776** [comment]
Lift switch is OK.
![1_lift_ok png](https://user-images.githubusercontent.com/24984517/206928045-2d89250e-513e-4caf-befc-2ec700d2ee89.jpg)

Other-side yellow door switch is not OK.
![2_yellowswitch_bad png](https://user-images.githubusercontent.com/24984517/206928054-7a373145-884a-443f-a9ff-98b569d2d35d.jpg)

Blue door switch is OK. (Assuming I'm looking at the right one - the actual architecture seems to have changed, not just the texture alignment.)
![3_blueswitch_ok png](https://user-images.githubusercontent.com/24984517/206928074-e5592869-b87b-471c-a1d3-2c9e00917a32.jpg)
