### ISSUE TITLE
E4M2: Savegame buffer overrun on Chocolate Doom

### ISSUE THREAD

**Issue by Snoucher** [freedoom/freedoom#822]
When You load into E4M2, attempting to save the game on Chocolate Doom results in the game crashing with a the message "Savegame buffer overrun" shown in the terminal.

**I have verified that I downloaded the latest freedoom wad and when checking, there isn't anything to update for chocolate-doom too.**

Here are my specs:
`OS: Manjaro Linux x86_64
Kernel: 5.15.74-3-MANJARO
CPU: Intel i5-2500 (4) @ 3.700GHz
GPU: NVIDIA GeForce GTX 1050 Ti
Memory: 3952MiB / 7903MiB`

Here is a video demonstration of the issue: 

https://user-images.githubusercontent.com/46611027/200652101-0bc00c29-b550-4dd2-8a1d-14c4a462dfbc.mp4

**Comment by Catoptromancy** [comment]
That limit can be disabled in the chocolate-doom-setup program under the Compatibility options menu. 

Savegame buffer overruns are known issues and will not be fixed, easily avoided though. There was discussions on the forum on why fixing these are a bad idea.

**Comment by Snoucher** [comment]
Thank you for providing a solution to this. I'm sorry for clogging up the issues with this meaningless issue. I hope more people are aware that this is a will-not-fix thing, now that this is floating around.
