### ISSUE TITLE
Contributing a sound effect.

### ISSUE THREAD

**Issue by SuperSomariDX** [freedoom/freedoom#84]
Got a sound I made with my own voice and audacity from a long while back. Maybe it could be of use somewhere if any?

It would be best if mixed with a thud or some gurgling sound effect for an enemy death, or just alone as a weird pain sound, the usage idea is up to you.

If you need me to convert it to wav or so, just tell me.

https://drive.google.com/file/d/0B7KVa3rJCvDDNjR2Skk1NnpMUk0/edit?usp=sharing

**Comment by Xindage** [comment]
seems like we'll not need it sorry.
