### ISSUE TITLE
Episode 4 music

### ISSUE THREAD

**Issue by fawtytoo** [freedoom/freedoom#845]
I know vanilla Doom uses music from the first 3 episodes for episode 4, but is it worth having separate music tracks for episode 4 anyway? Just for ports that can support it?

**Comment by fawtytoo** [comment]
As adding specific Episode 4 music would not be heard on Vanilla Doom, this issue may violate Freedoom's goal. However, if supporting Linux Doom is included, the source code requires minimal changes to achieve this.
After all, effort has already been made to have individual music for each map, but Episode 4 does not. And Freedoom Phase 1 does have 4 episodes.

**Comment by northivanastan** [comment]
This is what the [Double Impact MIDI Pack](https://www.doomworld.com/forum/topic/135660-idgames-double-impact-midi-pack-a-community-soundtrack-for-double-impact-and-freedoom-e4/) is trying to do. #971 is an attempt to incorporate it into the PWAD, but unfortunately at this time there's no one way to make all the ports recognize them.

**Comment by mc776** [comment]
Closing this now that #971's been merged.
