### ISSUE TITLE
DM music ending with long silences

### ISSUE THREAD

**Issue by fawtytoo** [freedoom/freedoom#847]
Plays fine until approx 1:36, then goes silent for the rest of the score: 3:43.

Had a look in a hex editor, but the problem isn't immediately apparent. However, there are an extraordinary amount of tempo changes in track 1.

Tested with vanilla Doom in DosBox and my own midi player.

**Comment by selliott512** [comment]
Sounds like some good research to me. Are you aware of the [#freedoom-music-dev Discord channel](https://discord.com/channels/616148111076884520/692859049921740831)?

**Comment by fawtytoo** [comment]
I now have a list of 7 tracks that exhibit the same behaviour:
The first time stamp is where the silence begins and the 2nd time stamp is the overall length of the score.
1. d_dm12 - 1:36 of 3:43
2. d_dm18 - 1:12 of 2:12
3. d_dm19 - 1:30 of 3:28
4. d_dm21 - 1:53 of 3:45
5. d_dm23 - 1:24 of 1:46
6. d_dm25 - 1:39 of 3:44
7. d_dm30 - 1:45 of 2:56

As you can see, there is a significant amount of silence in each. Chances are nobody's noticed because the midi player in some ports may "trim" the silence. However, vanilla Doom does not.

As there are 7 tracks, could there be a common author?

**Comment by northivanastan** [comment]
If replacing these with something reused/from another project is an acceptable solution, I might offer some of my [public domain MIDIs](https://opengameart.org/users/northivanastan) for use, which are mostly intended to fit Doom maps. I'll experiment with pairings later if I have the time and inclination. Xindage also suggested including tracks from the [Double Impact MIDI Pack](https://www.doomworld.com/forum/topic/135660-release-double-impact-midi-pack-a-community-soundtrack-for-double-impact-and-freedoom-e4/), especially if PR #971 is denied.

**Comment by Xindage** [comment]
i dont said its denied, i just told that it's very likely to dont pass

**Comment by northivanastan** [comment]
Right, sorry my wording wasn't sufficiently precise. What I meant is that if, ultimately, it is not merged, I would be happy with some of the tracks being used in FreeDM.

**Comment by mc776** [comment]
>     1. d_dm12 - 1:36 of 3:43
> 
>     2. d_dm18 - 1:12 of 2:12
> 
>     3. d_dm19 - 1:30 of 3:28
> 
>     4. d_dm21 - 1:53 of 3:45
> 
>     5. d_dm23 - 1:24 of 1:46
> 
>     6. d_dm25 - 1:39 of 3:44
> 
>     7. d_dm30 - 1:45 of 2:56
> 
> As there are 7 tracks, could there be a common author?

All of these tracks have a distinct common musical style and their instrumentation makes them all unfortunately much, much quieter in OPL than that style suggests they were ever intended to be. Who is the author?

**Comment by fawtytoo** [comment]
@mc776  OT: The quietness could be attributed to the GENMIDI instruments (I don't know which ones) used in these midi files. They have the same volume if using GUS patches.

**Comment by mc776** [comment]
What's a good FOSS midi editor?

**Comment by mc776** [comment]
> If replacing these with something reused/from another project is an acceptable solution, I might offer some of my [public domain MIDIs](https://opengameart.org/users/northivanastan) for use, which are mostly intended to fit Doom maps. I'll experiment with pairings later if I have the time and inclination.

I'd still like to figure out what's wrong with the current tracks, in case there's any issue with the build system or some other technical issue that we should watch out for going forward.

However, I'm honestly not attached to the current affected tunes at all and this may well be worth the change...

**Comment by Xindage** [comment]
if any new issue arise, please do a new issue on the related map. (fixed by: https://github.com/freedoom/freedoom/pull/1017)

**Comment by mc776** [comment]
AFAIK d_dm23 wasn't actually touched by any of the updates, so if anyone's looking to replace any current FreeDM track you may consider that a priority

**Comment by KorpKat** [comment]
I'll get to it tomorrow midnight, hopefully.
