### ISSUE TITLE
Cheats section for Phase 2?

### ISSUE THREAD

**Issue by StupidRepo** [freedoom/freedoom#854]
I'm very new to this and I do not know what Phase 1 or Phase 2 is or what the phases mean. All I know is that phase 1 doesn't let me play doom but phase 2 does. I press the squiggly key button (~) and open the console/command prompt/whatever and try the IDCLIP cheat and stuff but it doesn't work. The command `noclip` does but the command `IDCLIP` doesn't.

Please help!

**Comment by Calinou** [comment]
`idclip` is a *cheat code*, not a console command. This means you need to enter it during gameplay, without opening the console. You will see a message appear in the top-left corner once the cheat is activated.

To clarify:

- Original Doom did not have a Quake-style console you can toggle by pressing Tilde/Shift+Esc.
- Original Doom did support cheat codes like `idclip`, `idkfa` or `iddqd`.
- Many source ports such as GZDoom have added a Quake-style console for convenience.
  - Source ports generally don't allow entering cheat codes in the console (although this could be a good idea to allow, for usability reasons).

**Comment by selliott512** [comment]
That's a great explanation, Calinou. I wanted to add a few points in case it's helpful.

This project, Freedoom, only produces the IWADs that Calinou mentioned. It does not produce any executables. If you're using a program that calls itself "Freedoom", possibly an app on a cell phone, that program still does not have anything to do with this project other than the fact that it may bundle the IWADs produced by this project.

Issues are not the best place to get technical support. They are meant to report bugs that need to be fixed. The [#help channel](https://discord.com/channels/616148111076884520/791693298724765757) might be better. It looks like you've already found it (or there is someone there asking a similar question).

**Comment by jadenquinn** [comment]
> I'm very new to this and I do not know what Phase 1 or Phase 2 is or what the phases mean. All I know is that phase 1 doesn't let me play doom but phase 2 does. I press the squiggly key button (~) and open the console/command prompt/whatever and try the IDCLIP cheat and stuff but it doesn't work. The command `noclip` does but the command `IDCLIP` doesn't.
> 
> 
> 
> Please help!

If you mean you don't exactly know how to enter a cheat code in the Doom engine, since it's pretty strange, all you have to do is during gameplay, not even paused or anything, just type idclip, like you would into a text document for example, just do it basically, and it should popup a string of text in the corner if you were successful that says it's been turned on or something to that effect.

I didn't know this when I got back into doom in 2017/2018, but I figured it out on my own the same day, so chances are you probably have since this issue was opened. I wanted to post it anyway. Hope it helps!

**Comment by mc776** [comment]
I think this can be closed.

**Comment by StupidRepo** [comment]
> but I figured it out on my own the same day, so chances are you probably have since this issue was opened.

Lol, yeah.
