### ISSUE TITLE
Update the remaining CxMx references to ExMx

### ISSUE THREAD

**Issue by selliott512** [freedoom/freedoom#856]
It used to be that phase 1 had chapters instead of episodes which means that files like `e1m1.wad` used to be named something like `c1m1.wad`. However, there are still some references to the older chapter naming convention. The goal for this issue is to identify the ones that need to be updated (that aren't just historical), and update them.

This may be a good first issue to work on, but you'll probably need to chat with folks in Discord or otherwise to figure out which ones need to be updated.

This is not urgent enough to hold up the release.

Some files to consider:
```
git grep -Pil 'c\dm\d' | grep -vP '\.(png|wad)'

CREDITS
NEWS.adoc
dist/io.github.freedoom.Phase1.metainfo.xml
manual/manual-es.adoc
manual/manual.adoc

git ls-files | grep -Pi 'c\dm\d' 

manual/images/c5m1-sshot.png
```

**Comment by mc776** [comment]
Are there any references left now?

**Comment by selliott512** [comment]
Looks like exactly the same ones. I thought this would be a good first issue for someone, but I can take a shot at it. Maybe this weekend.

**Comment by selliott512** [comment]
They are all pretty much historical. The one exception might be “C1M3 - Blue Key Door.” as an example of a save game name, but it doesn't feel like it's even worth changing. We can probably close this.

**Comment by mc776** [comment]
It should be changed if it's referring to a current thing.

**Comment by selliott512** [comment]
Sure. It will be done with PR #880 I just submitted. The rest of them seem historical.

**Comment by Xindage** [comment]
i think its fixed right?

**Comment by mc776** [comment]
It's been quite some time since anyone's found anything else, and enough stuff says "Episode" that anything still saying "Chapter" is going to stick out like a sore thumb, so I would think it's safe to close...
