### ISSUE TITLE
Potentially forgotten secret area in Freedoom Phase 1 C2M1?

### ISSUE THREAD

**Issue by FistsAkimbo** [freedoom/freedoom#864]
The door across the gap at the start of the map has the accessible side locked, but the opposite side unlocked; this implies you're meant to go another way. However, the only other area you could possibly access this area is from the stone path later on with the high up ledge flanked by two tech lights. But it's too high up to jump, unless you potentially jump on the center pedestal and then the shotgunner's head, but that seems too finnicky and inconsistent to be the intention. You also have no rocket launcher given that this is the start of the episode, made more pointless because the area you're trying to reach leads to the first rocket launcher of the episode. Is this area just forgotten (given that there's no secret immediately within the location) or am I missing something?

**Comment by mc776** [comment]
There's a bunch of areas in that map that's supposed to be only available for deathmatch.

Personally I'd rather see those made accessible in singleplayer, but I suppose it needs to be done in a way that doesn't allow *too* egregious a sequence break or give too much weapons and ammo this early in the episode.

This will take some tweaking.

**Comment by mc776** [comment]
The rest of the map is OK as it is though.

If the only issue is with the misleading suggestiveness of the broken bridge, one possibility is to make it visibly blocked off by rubble, but add a walk line that's immediately triggered by the deathmatch start there that lowers all the rubble sectors (lower to lowest adjacent and change floor texture to match).

That way anyone playing in singles will just see a static "don't go here" map geometry of the sort that we see all the time, but doesn't (ultimately) get in the way in DM.

**Comment by FistsAkimbo** [comment]
Shortly after I made this thread, I realized that the only possible remaining (logical) explanation would be that this is for deathmatch. However:

1: Doom maps having exclusive areas limited to deathmatch generally feels quite limiting, as it removes content that should generally be accessible for all game modes. Flagging actors (monsters, pickups) for which game modes and difficulties they should appear in is generally the way to go rather than omitting entire fleshed out areas.

2: The fact that it's a one time jump unless you cheat (or, if the map had stairs or a lift in the relevant connecting area, you could backtrack) could also be used as a fun alternative approach to the map.

Either way, it would be nice to have a means of accessing this area from the drop down leading to the stone path.

**Comment by mc776** [comment]
I agree. Frankly I'm pretty sure that making those areas accessible - if optional - would only improve the singleplayer experience.

**Comment by SmokeyDope** [comment]
OOOOh So thats why its inacessable. I honestly thought that some parts of freedoom maps were built around jumping mechanic. Stupid In hindsight, I know. 

It would be cool to have a secret as a way to get over there. Some ideas for a secret:

on the outside - perhaps a hidden door activated by one of the faces of the pillar things (Its really annoying to pistol start the stealth worms, a secret shotty would be neat)
A false wall of the hallway leading into the base leading across
just after dropping down turn left and activate a hidden door leading up
![Screenshot from 2023-03-13 15-06-54](https://user-images.githubusercontent.com/122294027/224807116-539417f6-9581-4164-b0d7-3ed966abd0ac.png)
![Screenshot from 2023-03-13 15-07-35](https://user-images.githubusercontent.com/122294027/224807131-c1ce57a3-4840-4c4c-97e1-33ccd948a0ab.png)
![Screenshot from 2023-03-13 15-09-06](https://user-images.githubusercontent.com/122294027/224807138-4457ac67-72f2-43c3-ac67-56e61e05d2e8.png)

**Comment by mc776** [comment]
Conversely, if we do replace this (and after seeing the equivalent on e2m7 it sounds like a good idea) this might be a worthwhile replacement for some of the maps flagged as to be removed in #722.

**Comment by jadenquinn** [comment]
Deathmatch-specific secrets are just dumb in my opinion, especially if a deathmatch-specific WAD is being provided right from the get-go. If one wants to play the normal Freedoom maps on a deathmatch mode, they should be alright with the fact that it's not intended for that, the other way from this being that EVERYONE should implement deathmatch-specific secrets in every single map, but that's even more idiotic to me.
The best solution is just to not have any deathmatch-specific secrets tagged as such (or at least not visible to the player on a non-deathmatch mode for a hot tease), and to instead put those types of things in the deathmatch-specific Freedoom maps.

But that's just my thought on this subject.
