### ISSUE TITLE
Map starts and exits with that zero-light effect

### ISSUE THREAD

**Issue by mc776** [freedoom/freedoom#867]
Starting this issue as a continuation of #714 (which I'd kinda hijacked for general Map10 improvements, sorry)

So IIRC this is an effect inherited from Plutonia, so it's got 2 things against it:
1. clearly copied from one of the proprietary IWADs
2. looks goofy enough that it gets reported as a bug

In Phase 2 I've seen them in the following maps:
(P=uses that pad-and-diamond Plutonia start/exit marker; P*=uses this style of exit marker *but does not actually have this lighting effect*)

4 end  (but maybe keep it cuz it's actually cool-looking? Still looks like a rendering error to modern eyes though)
~~6 start P, end P~~
~~10 start~~
~~11 start, end~~
~~13 start P, end P~~
~~14 start P, end P~~
31 end P (both exits)
~~32 end P*~~
17 start P, end P
18 start P, end P
~~19 start P, end P~~
~~24 start P, end P~~

Phase 1 does not have anything resembling this kind of map start/end marker.

**Comment by Xindage** [comment]
seems like it was fixed by #949
