### ISSUE TITLE
MAP25 Starting area lift not working properly in GZDoom

### ISSUE THREAD

**Issue by Talon1024** [freedoom/freedoom#902]
The lift at the start of MAP25 isn't working properly in GZDoom. It only takes you one inch up, and then it stops. Even with the compatibility settings set to "Doom (strict)", it doesn't raise enough to allow players to really start playing through the level.

**Comment by mc776** [comment]
Keep punching - it's supposed to be equivalent to the old start (which I always noclipped out of for ages).

But yeah, I'll see what I could do to better signpost that you're supposed to shoot the exposed circuitry by the switch.

**Comment by mc776** [comment]
Not sure how I feel about having the switch be obligatory now...

**Comment by Xindage** [comment]
addressed.
