### ISSUE TITLE
textures: any compatibility reason to show the full length of patch SUPPORT2 in texture SUPPORT2?

### ISSUE THREAD

**Issue by mc776** [freedoom/freedoom#904]
TIL the patch SUPPORT2 tiles vertically almost seamlessly *if you crop off the bottom 8 pixels for a 24x64 image*.

The one and only texture it's used in is SUPPORT2, which is 64x128.

There was never, ever any good reason to show the full 72.

Maps are full of tiling problems where we see that SUPPORT2 seam in ugly, strange places.

All of those problems could be avoided if we just treated the patch as 
```
SUPPORT2        64      128
*   SUPPORT2    0       0
*   SUPPORT2    40      0
*   SUPPORT2    20      0
*   SUPPORT2    0       64
*   SUPPORT2    20      64
*   SUPPORT2    40      64
```
So before I post a PR: is there any reason why this should not be done? Are there any maps that rely on this behaviour that would be seriously broken by a change like this?

Screenshots for comparison:
![DOOM01](https://user-images.githubusercontent.com/24984517/224576347-bb5fb9b5-25be-4e16-88fc-c3dfb6780e20.png)
![DOOM02](https://user-images.githubusercontent.com/24984517/224576352-530b6c21-fe25-4c83-9aa6-597f886c7b2f.png)

**Comment by Xindage** [comment]
i think its ok to go, not all freedoom textures as far i know respect the same texture defs of doom, so fell free to fix it as long the texture keeps its original height its all fine, i believe.
