### ISSUE TITLE
HTTPS certificate issue on the ''freedoom.soulsphere.org'' site

### ISSUE THREAD

**Issue by dftf-stu** [freedoom/freedoom#918]
The [webpage](https://freedoom.soulsphere.org) where you can download the development (live) builds of Freedoom appears to have a certificate issue:

![FreedoomDevBuildHTTPSIssue](https://user-images.githubusercontent.com/83965343/226582633-d8493567-1508-4d78-826a-f188e5c890e0.png)

While you can work-around around this, I just thought I'd mention it in-case people weren't aware.

Thanks

**Comment by selliott512** [comment]
As far as I know [Freedoom's download page](https://freedoom.github.io/download.html) links to the HTTP version of the above in the "Development snapshots" section (and a few other places), and does not use the HTTPS URL. I agree with the idea that it would be nice if it, and all websites, had a functioning HTTPS SSL certificate, but it's not my website.

**Comment by dftf-stu** [comment]
Advised website is not owned by this project, and needs to be reported to the team who manages it (though does seem odd to me that the official website for _Freedoom_ links to that page, if it's not controlled by the project -- might make more-sense to host the development-build WADs somewhere the team behind it does control?)

I will try to contact "Simon Howard" using the GMail address given on the [homepage](http://insecure.soulsphere.org) of that website
