### ISSUE TITLE
Freedoom still has some ugly TNT placeholder textures

### ISSUE THREAD

**Issue by fragglet** [freedoom/freedoom#92]
Freedoom has a bunch of textures for TNT compatibility that are just placeholders. Some of these are quite ugly (see eg. #76). We've done some work to improve these recently but there are still a few that look bad and ought to be improved.

**Comment by uhbooh** [comment]
Here's a DISASTER patch i made with the old font.
![disaster](https://cloud.githubusercontent.com/assets/22185239/18564408/503fc3ea-7b59-11e6-8662-be2a3f7009ea.GIF)

Also you forgot a placeholder texture, POISON. I made one as well.
![poison](https://cloud.githubusercontent.com/assets/22185239/18564426/6a29ae92-7b59-11e6-9b1f-905bcd55707c.GIF)

**Comment by AXDOOMER** [comment]
Nice work. I am flabbergasted that a poison texture still wasn't done though.

**Comment by chungy** [comment]
I believe this issue is now resolved.

**Comment by AXDOOMER** [comment]
Were DOGRIG, FENCE4, PSTON2 and REDTNT2 replaced? 
DISASTER was replaced with  https://github.com/freedoom/freedoom/commit/ffc71c8362990603af004255eee6ea2088320864 which still looks like a place holder.

**Comment by Voros2** [comment]
There are still TNT placeholders in Freedoom, such as FENCE4. Best not to close this until everything has been resolved.

**Comment by AXDOOMER** [comment]
I checked through the entire version of the latest IWAD and found the name of the patches that are remaining to do: 
* DISASTER
* DOGRID
* FENCE4
* PSTON2
* REDTNT2

Some of them use text, other use ugly images as placeholders. 

Please reopen this issue.

**Comment by NickZ** [comment]
It looks like @Talon1024 got all of these in b92e8578f2870f23a01199a6f8108f14f94d82cf, and Red TNT2 looks acceptable.  Nicely done!
