### ISSUE TITLE
Phase 1 E4M1 crashes most source ports in latest version

### ISSUE THREAD

**Issue by northivanastan** [freedoom/freedoom#939]
In the latest autobuild, as well as my own build from the master branch of this repository, starting Double Impact or typing idclev41 in Freedoom: Phase 1 crashes most source ports. GZDoom loads the level just fine, but chocolate-doom crashes with no error, crispy-doom segfaults, eternity-engine gives "not a valid level", dsda-doom outputs this interesting error message:

```
dsda-doom v0.25.6 (https://github.com/kraflab/dsda-doom/)
dsda-doom is released under the GNU General Public license v2.0.
You are welcome to redistribute it under certain conditions.
It comes with ABSOLUTELY NO WARRANTY. See the file COPYING for details.

Playing: The Ultimate DOOM
 adding freedoom1.wad
 adding /usr/share/dsda-doom/dsda-doom.wad
Loading DEH lump from freedoom1.wad

P_VerifyBlockMap: list offset overflow
P_LoadBlockMap: erroneous BLOCKMAP lump may cause crashes.
P_LoadBlockMap: use "-blockmap" command line switch for rebuilding
Z_Malloc: Failure trying to allocate 18446744073341370368 bytes
```

and woof-doom shows a wall of `R_FlatNumForName:  not found` before crashing with `Z_Malloc: Failure trying to allocate 33991557120 bytes`.

Maybe the WAD file is corrupt? In any case something about E4M1 is causing more strict ports to allocate memory incorrectly. No other levels seem to be affected.

**Comment by mc776** [comment]
Getting R_FlatNumForName: [tofu] not found.

Might be a copypaste error when setting a flat somewhere?

**Comment by northivanastan** [comment]
Did not expect this to be fixed in two hours, but with that latest commit E4M1 now runs on chocolate-doom. Thanks @mc776 for fixing it.

**Comment by mc776** [comment]
You're welcome, I was the one who broke it 😅
