### ISSUE TITLE
dehacked: do we even want blinking armor?

### ISSUE THREAD

**Issue by mc776** [freedoom/freedoom#945]
There was never a good reason to make the armour sprite constantly flashing like that. It never made any diegetic sense at all in id and even with the new sprites working with it it still looks... *bad.*

Arguably it's a good way to indicate the presence of a clear objective in a dark room, but it doesn't really illuminate anything else, making navigation difficult anyway, and in vanilla from a distance it just looks at first like a zombie shooting at you. It might even make more sense to make the armour *always* fullbright.

Thoughts?

**Comment by jadenquinn** [comment]
I would prefer dimly lit armor that flashes in the same way, so it's always illuminated, but still flashes.

**Comment by mc776** [comment]
...suppose we were limited to things that were possible in vanilla...

**Comment by mc776** [comment]
This seems to have less demand than I might have thought... though tbh this only really came up for me while staring directly at the armour pickup for prolonged periods of time during testing and getting annoyed at the blinking.
