### ISSUE TITLE
Check if all levels can be completed fully FD1.

### ISSUE THREAD

**Issue by Xindage** [freedoom/freedoom#958]
**This list is for freedoom 1**
This list is to keep track of every map in every skills, all map should be completed fully with all secret items and monsters.
provide me the data on Direct messages on discord (i prefer that please) )or here and i'll edit this issue with the data provided.
Note: TBC means "To be Confirmed" this mean that slot is open to test so you can provide me the info if its beatable.
If a map is not beatable fully in any of the skills, please open a issue.

**_Freedoom 1_**
**Episode 1**
E1M1: Easy (Completed) Medium (Completed) Hard (Completed) - Xindage
E1M2: Easy (Completed) Medium (Completed) Hard (Completed) - Nful2
E1M3: Easy (Completed) Medium (Completed) Hard (Completed) - Nful2
E1M4: Easy (Completed) Medium (Completed) Hard (Completed) - Nful2
E1M5: Easy (Completed) Medium (Completed) Hard (Completed) - Nful2
E1M6: Easy (Completed) Medium (Completed) Hard (Completed) - Nful2
E1M7: Easy (Completed) Medium (Completed) Hard (Completed) - Nful2
E1M8: Easy (Completed) Medium (Completed) Hard (Completed) - Nful2
E1M9: Easy (Completed) Medium (Completed) Hard (Completed) - Nful2
**Episode 2**
E2M1: Easy (TBC) Medium (TBC) Hard (Completed) - Sgt. Major Kiwi
E2M2: Easy (TBC) Medium (TBC) Hard (Completed) - Sgt. Major Kiwi
E2M3: Easy (TBC) Medium (TBC) Hard (Completed) - Sgt. Major Kiwi
E2M4: Easy (Completed) Medium (Completed) Hard (Completed) - Xindage
E2M5: Easy (TBC) Medium (TBC) Hard (Completed) - Sgt. Major Kiwi
E2M6: Easy (Completed) Medium (Completed) Hard (Completed) - Nful2, Xindage
E2M7: Easy (TBC) Medium (TBC) Hard (Completed) - Sgt. Major Kiwi
E2M8: Easy (TBC) Medium (TBC) Hard (Completed) - Sgt. Major Kiwi
E2M9: Easy (TBC) Medium (TBC) Hard (Completed) - Sgt. Major Kiwi
**Episode 3**
E3M1: Easy (Completed) Medium (Completed) Hard (Completed) - Nful2
E3M2: Easy (Completed) Medium (Completed) Hard (Completed) - Nful2
E3M3: Easy (Completed) Medium (Completed) Hard (Completed) - Nful2
E3M4: Easy (Completed) Medium (Completed) Hard (Completed) - Nful2
E3M5: Easy (Completed) Medium (Completed) Hard (Completed) - Nful2
E3M6: Easy (Completed) Medium (Completed) Hard (Completed) - Nful2
E3M7: Easy (Completed) Medium (Completed) Hard (Completed) - Nful2
E3M8: Easy (Completed) Medium (Completed) Hard (Completed) - Nful2
E3M9:  Easy (Completed) Medium (Completed) Hard (Completed) - Nful2
**Episode 4**
E4M1: Easy (Completed) Medium (Completed) Hard (Completed) - Nful2
E4M2: Easy (Completed) Medium (Completed) Hard (Completed) - Nful2
E4M3: Easy (Completed) Medium (Completed) Hard (Completed) - Nful2
E4M4: Easy (Completed) Medium (Completed) Hard (Completed) - Nful2
E4M5: Easy (Completed) Medium (Completed) Hard (Completed) - Nful2
E4M6: Easy (Completed) Medium (Completed) Hard (Completed) - Nful2
E4M7: Easy (Completed) Medium (Completed) Hard (Completed) - Nful2
E4M8: Easy (Completed) Medium (Completed) Hard (Completed) - Nful2
E4M9: Easy (Completed) Medium (Completed) Hard (Completed) - Nful2

**Comment by mc776** [comment]
(and pistol start)

**Comment by Xindage** [comment]
yes, exactly that.

**Comment by nful2** [comment]
I think i can contribute in this. But how?
Do i have to just submit a demo file? Do i have to use the iwad in http://freedoom.soulsphere.org/? Source port?

**Comment by Xindage** [comment]
using the iwad in soulsphere is a good choice, and no you dont need to provide a demo, i'm accept proof word, and maybe a 100% screenshot as well, just beat the level completely and its good to go here.

**Comment by Xindage** [comment]
e2m1 and e2m4 (not e2m2) are under rework, but its not sure if they'll be done before or after the release. if they're done and proofed that both are 100% completable in both skills they can get in

**Comment by nful2** [comment]
@Xindage Completed episode 1. But how to send so many screenshots?

**Comment by nful2** [comment]
Episode 1 done! 
Freedoom version: freedoom-0.12.0-486-g4b002550
Source port: gzdoom v4.10.0

[Freedoom testing episode 1.zip](https://github.com/freedoom/freedoom/files/11646082/Freedoom.testing.episode.1.zip)

Issues in episode 1: #976. Didn't face any other problem.

**Comment by nful2** [comment]
E2m6, freedoom-0.12.0-489-ge88e1020, crispy-doom-6.0.0
Issues - #982. Didn't face any other problem

Easy
![E - e2m6](https://github.com/freedoom/freedoom/assets/100768714/a17b580d-4564-4db0-9ddc-2dddb327fa9d)
Medium
![M - e2m6](https://github.com/freedoom/freedoom/assets/100768714/3b974250-8fb2-478c-937e-7babcfb138d0)
Hard
![H - e2m6](https://github.com/freedoom/freedoom/assets/100768714/1757a67d-47ca-45c2-85dc-931ae714bf3c)

**Comment by nful2** [comment]
E3m1, freedoom-0.12.0-489-ge88e1020, crispy-doom-6.0.0
Easy
![E](https://github.com/freedoom/freedoom/assets/100768714/7e8b44cd-59d0-4bac-bd15-6a8badac7300)
Medium
![M](https://github.com/freedoom/freedoom/assets/100768714/b3212a41-8cf7-4615-b432-bba7b26db03c)
Hard
![H](https://github.com/freedoom/freedoom/assets/100768714/2201da07-8b49-431a-a531-688fa44ee769)

**Comment by Xindage** [comment]
there's something strange on that screenshots, all easy/medium shots has the same amount of monsters... i'll double check it better tonight.

**Comment by nful2** [comment]
@Xindage I used -skill 1 for easy, -skill 2 for medium and -skill 3 for hard. Am I testing wrong?

**Comment by mc776** [comment]
The difference might be a matter of placement or type of enemy while keeping the numbers the same, or the difference might be a matter of placement of health/ammo/armour/weapons, so it's not entirely unusual (let alone wrong) that a map might have the same monster count on different skill levels.

**Comment by Xindage** [comment]
> @Xindage I used -skill 1 for easy, -skill 2 for medium and -skill 3 for hard. Am I testing wrong?
1 is easy 2 is also easy 3 is hurt me plenty. 
https://doomwiki.org/wiki/Parameter#-skill

**Comment by mc776** [comment]
-skill 1 = Easy placements with reduced damage and double ammo
-skill 2 = Easy placements
-skill 3 = Medium placements
-skill 4 = Hard placements
-skill 5 = Hard placements with fast respawning monsters

so testing should be done with 2, 3 and 4

**Comment by Catoptromancy** [comment]
Can load chocolate-doom savegames in crispy-doom and type "skill" similar to a cheat code, and the skill level you are playing will be displayed.

**Comment by mc776** [comment]
> Can load chocolate-doom savegames in crispy-doom and type "skill" similar to a cheat code, and the skill level you are playing will be displayed.

What's the output of that? I know in GZDoom it's super confusing because its skill levels start at 0...

**Comment by nful2** [comment]
Ok, I will retest and replace the -skill 1 screenshots with -skill 4 ones.

**Comment by nful2** [comment]
@mc776 See https://zdoom.org/wiki/ChangeSkill for gzdoom. And https://doomwiki.org/wiki/Parameter#-skill for close-to-vanilla source ports.

**Comment by nful2** [comment]
Episode 1 in hard
freedoom-0.12.0-489-ge88e1020, crispy-doom-6.0.0

Issues in episode 1: https://github.com/freedoom/freedoom/issues/976. Didn't face any other problem.

![e1m2](https://github.com/freedoom/freedoom/assets/100768714/d0c1bb18-e9fb-4527-b471-a1fd512be746)
![e1m3](https://github.com/freedoom/freedoom/assets/100768714/16773bbc-6334-4665-b5ff-96487453ae3f)
![e1m4](https://github.com/freedoom/freedoom/assets/100768714/00fdf6dc-62ca-4821-9947-7a74ab35e25a)
![e1m5](https://github.com/freedoom/freedoom/assets/100768714/a718269a-3766-47d3-8544-e9242b022296)
![e1m6](https://github.com/freedoom/freedoom/assets/100768714/9ca37028-4c64-4157-8c1a-7413c607c7fa)
![e1m7](https://github.com/freedoom/freedoom/assets/100768714/4ee3f612-db7e-401d-ad5c-642e173e545a)
![e1m8](https://github.com/freedoom/freedoom/assets/100768714/3ea228bf-4956-4d56-b211-0a16d70623a5)
![e1m9](https://github.com/freedoom/freedoom/assets/100768714/63590634-481e-4c66-bed8-6e26d9b9c488)

**Comment by nful2** [comment]
@Xindage Now I have changed screenshots. You can verify them?

**Comment by Xindage** [comment]
ok ill be reviewning and updating this post soon

**Comment by Xindage** [comment]
> E2m6, freedoom-0.12.0-489-ge88e1020, crispy-doom-6.0.0 Issues - #982. Didn't face any other problem
> 
> Easy ![M - e2m6](https://user-images.githubusercontent.com/100768714/246367009-3b974250-8fb2-478c-937e-7babcfb138d0.png) Medium ![H - e2m6](https://user-images.githubusercontent.com/100768714/246367056-1757a67d-47ca-45c2-85dc-931ae714bf3c.png) Hard ![e2m6](https://user-images.githubusercontent.com/100768714/247520250-1d2772b8-993b-4b0c-bf48-0e9e660c9c5a.png)

this map in hard has 157 monsters, you duplicated the run in normal unfortunately. but i tested it on hard.
![Screenshot_Doom_20230623_220436](https://github.com/freedoom/freedoom/assets/6380147/57d4f10f-c4db-4668-86d6-4d135dfb3fc6)

**Comment by nful2** [comment]
@Xindage I have downloaded latest beta wad but it still shows 144 monsters. Weird. Using crispy-doom-6.0.0.

**Comment by mc776** [comment]
157 for me.

**Comment by nful2** [comment]
@mc776 Now I checked on gzdoom and it shows different monster count - 157. So should I just stick with gzdoom?

**Comment by mc776** [comment]
what were you using before?

**Comment by mc776** [comment]
can you post the exact command line thing you use to test in hard?

**Comment by nful2** [comment]
.\gzdoom.exe -iwad ..\Wads\freedoom-0.12.0-493-gf1c7a44a\freedoom1.wad -warp 2 6 -skill 4

**Comment by mc776** [comment]
No idea why that would give you not 157 monsters then.

**Comment by mc776** [comment]
What about crispy though? that's where you got the 144, right?

**Comment by nful2** [comment]
@mc776 I just replace gzdoom with crispy-doom. No other changes

**Comment by Xindage** [comment]
i know the issue, crispy and choco use the same engine and they ignore lost souls as monsters, because doom2 intruduced a bug that the devs fixed, where lost souls used to break the total monsters count, zdoom derivated ports dont suffer from this issue, then it shows the TRUE real monsters count.

**Comment by Catoptromancy** [comment]
Can use "KILLEM" as a cheat code in crispy at exit to make sure lost souls are also dead. There is a good chance lost souls are stuck in walls though. Can use IDDT to find leftover monsters, or lost souls stuck in walls.

**Comment by Xindage** [comment]
tbh i'm not sure what we should do about it, lost soul can/cannot be issue depending on the port that you use.

**Comment by Catoptromancy** [comment]
The KILLEM code will display how many monsters are killed on chocolate saves. This somewhat emulates advanced ports that display lost souls. Just for making sure everything is dead (besides lost souls stuck in walls).

**Comment by nful2** [comment]
@Xindage e3m3, freedoom-0.12.0-507-ga0aa5f43, gzdoom-4-10-0 
Didn't face any issues

Easy
![e- e3m3](https://github.com/freedoom/freedoom/assets/100768714/457d1f3e-aa10-4062-9bf1-03cca197307a)
Medium
![m e3m3](https://github.com/freedoom/freedoom/assets/100768714/d3c1d16b-ea90-40e5-b201-a2eb127ecc96)
Hard
![h e3m3](https://github.com/freedoom/freedoom/assets/100768714/f33fc973-85d8-42af-981e-2d8b8181cff5)

**Comment by nful2** [comment]
@Xindage e3m4, freedoom-0.12.0-507-ga0aa5f43, gzdoom-4-10-0
Didn't face any issue.

Easy
![e e3m4](https://github.com/freedoom/freedoom/assets/100768714/b8d55baf-0176-47e2-aa32-f8134f792902)
Medium
![m e3m4](https://github.com/freedoom/freedoom/assets/100768714/19f34aa6-2326-4f56-b7c1-1068da90b904)
Hard
![h e3m4](https://github.com/freedoom/freedoom/assets/100768714/59900f07-070c-4b42-b276-8368db9f2f2e)

**Comment by nful2** [comment]
@Xindage e3m5, freedoom-0.12.0-507-ga0aa5f43, gzdoom-4-10-0
Didn't face any issue.

Easy
![e e3m5](https://github.com/freedoom/freedoom/assets/100768714/97ffb6d6-42e9-4a44-92a7-53cc9ca3709b)
Medium
![m](https://github.com/freedoom/freedoom/assets/100768714/94b9e3b0-3565-48c8-ac0f-1c796baab4fb)
Hard
![h](https://github.com/freedoom/freedoom/assets/100768714/8c16e9d3-fcc4-49b3-8e79-818a7d85947a)

**Comment by nful2** [comment]
@Xindage e3m6, freedoom-0.12.0-507-ga0aa5f43, gzdoom-4-10-0
Issues/Suggestions - #998. Didn't face any other problem

Easy
![e e3m6](https://github.com/freedoom/freedoom/assets/100768714/512babde-b03d-4e71-a87c-e84f2027a19f)
Medium
![m](https://github.com/freedoom/freedoom/assets/100768714/0a7297cb-e938-4374-b200-155f27d87616)
Hard
![h](https://github.com/freedoom/freedoom/assets/100768714/03c61eae-fda3-4104-b205-9a8ade00de8e)

**Comment by nful2** [comment]
@Xindage e3m9, freedoom-0.12.0-508-g03f157af, gzdoom-4-10-0
Issues/Suggestions - #999. Didn't face any other problem

Easy
![e e3m9](https://github.com/freedoom/freedoom/assets/100768714/a7c092c5-67b4-40e9-9879-953d3ca9eb9c)
Medium
![m](https://github.com/freedoom/freedoom/assets/100768714/7ecab80e-b9d2-4823-8610-e98d51c8d9fb)
Hard
![h](https://github.com/freedoom/freedoom/assets/100768714/37e85193-fd3a-4da0-9d6f-b9ae2a50a634)

**Comment by nful2** [comment]
@Xindage e4m1,2,3,4, freedoom-0.12.0-509-gd71ac12c, gzdoom-4-10-0
Issues/Suggestions - #1004. Didn't face any other problem.

Arranged in easy, medium and hard
![e e4m1](https://github.com/freedoom/freedoom/assets/100768714/b302a124-cc9c-41fa-b10b-a45a74a15f6e)
![m e4m1](https://github.com/freedoom/freedoom/assets/100768714/0e6fcbfe-8682-4e5e-b830-39e99a651b70)
![h e4m1](https://github.com/freedoom/freedoom/assets/100768714/57f75886-f08a-4539-aa57-f91be1735dbf)
![e e4m2](https://github.com/freedoom/freedoom/assets/100768714/7f2c19b6-3b91-47f6-b531-aa78bed17582)
![m e4m2](https://github.com/freedoom/freedoom/assets/100768714/1a2530bd-1bdb-402e-8b69-c7d424d6da1f)
![h e4m2](https://github.com/freedoom/freedoom/assets/100768714/81e5305d-9d96-44cb-93d3-c45af9083c67)
![e e4m3](https://github.com/freedoom/freedoom/assets/100768714/bbde5d20-393b-446e-a4e6-dd9cbdbdc6e6)
![m e4m3](https://github.com/freedoom/freedoom/assets/100768714/5fca327a-ef5a-43e1-ab5b-fb60ca023426)
![h e4m3](https://github.com/freedoom/freedoom/assets/100768714/f5e854ac-f275-4c38-8107-9674b51db4ef)
![e e4m4](https://github.com/freedoom/freedoom/assets/100768714/b8baece0-a3bb-4b34-a8f3-5804ab6870b3)
![m e4m4](https://github.com/freedoom/freedoom/assets/100768714/721523af-2d8e-42c4-953b-4140c34588b5)
![h e4m4](https://github.com/freedoom/freedoom/assets/100768714/650505e5-7f90-4259-b43d-ea866b095ac5)

**Comment by nful2** [comment]
@Xindage e4m5, freedoom-0.12.0-509-gd71ac12c, gzdoom-4-10-0
Didn't face any issue.

Easy
![e e4m5](https://github.com/freedoom/freedoom/assets/100768714/df79390b-ef77-4cd8-8c17-2f4cf7d6596c)
Medium
![m](https://github.com/freedoom/freedoom/assets/100768714/cdc11aa0-9d71-4445-8256-4dfefb619e1a)
Hard
![h](https://github.com/freedoom/freedoom/assets/100768714/1e4a7a7e-22b9-4b30-b28d-d61900f01c37)

**Comment by nful2** [comment]
@Xindage e4m6, freedoom-0.12.0-509-gd71ac12c, gzdoom-4-10-0
Didn't face any issue.

Easy
![e e4m6](https://github.com/freedoom/freedoom/assets/100768714/51489235-8023-489a-b0ed-384db3dde41a)
Medium
![m e4m6](https://github.com/freedoom/freedoom/assets/100768714/7423e7a5-c665-40e6-9137-7c21aa578e99)
Hard
![Uploading h e4m6.png…]()

**Comment by nful2** [comment]
@Xindage e4m7, gzdoom-4-10-0
Didn't face any issues.

Easy (freedoom-0.12.0-514-g0f8641d9)
![e e4m7](https://github.com/freedoom/freedoom/assets/100768714/5a93ae98-56a5-4fe1-b5b3-4c7552d39a24)
Medium (freedoom-0.12.0-514-g0f8641d9)
![m e4m7](https://github.com/freedoom/freedoom/assets/100768714/b4e5b184-38d3-444b-baf2-b559ad311dca)
Hard (freedoom-0.12.0-517-g0d16f842)
![h e4m7](https://github.com/freedoom/freedoom/assets/100768714/50ec0e03-54c5-442d-82dd-3824db16b121)

**Comment by nful2** [comment]
@Xindage e4m8,9, gzdoom-4-10-0

freedoom-0.12.0-517-g0d16f842
![e e4m8](https://github.com/freedoom/freedoom/assets/100768714/6f2ab9e9-0853-4ec0-ad5f-4039424e678e)
freedoom-0.12.0-519-g5fcfb603
![m e4m8](https://github.com/freedoom/freedoom/assets/100768714/a94484dc-efa6-47d8-9502-e1986ce99418)
freedoom-0.12.0-519-g5fcfb603
![h e4m8](https://github.com/freedoom/freedoom/assets/100768714/d20b7b08-b8f1-46b3-9486-29a2eb38f9e7)
freedoom-0.12.0-521-g8440307d
![e e4m9](https://github.com/freedoom/freedoom/assets/100768714/dc99461d-6521-4344-bd4d-1f3e1f36f2f1)
freedoom-0.12.0-521-g8440307d
![m e4m9](https://github.com/freedoom/freedoom/assets/100768714/ca95be45-7ee5-44b7-bb55-147423dba46e)
freedoom-0.12.0-533-g00e4c581
![h e4m9](https://github.com/freedoom/freedoom/assets/100768714/66c348b5-9a1a-41b7-93fc-5f37134f31e6)

**Comment by nful2** [comment]
@Xindage gzdoom-4-10-0

e3m7
Easy - freedoom-0.12.0-533-g00e4c581
Medium & hard - freedoom-0.12.0-537-g24c40762
![e e3m7](https://github.com/freedoom/freedoom/assets/100768714/dd8f9860-6dc9-48b8-9e31-8fd091eb5784)
![m e3m7](https://github.com/freedoom/freedoom/assets/100768714/8ace4135-3732-4d77-9255-843d818c211f)
![h e3m7](https://github.com/freedoom/freedoom/assets/100768714/8a2913d5-f42d-48a3-ac27-a0915b8ac02a)

E3m8 - all with freedoom-0.12.0-533-g00e4c581
![e e3m8](https://github.com/freedoom/freedoom/assets/100768714/5fad4289-b69f-4de3-a081-7a22112c3212)
![m e3m8](https://github.com/freedoom/freedoom/assets/100768714/78fc2548-a298-4f7b-b139-95a856e90da7)
![h e3m8](https://github.com/freedoom/freedoom/assets/100768714/9ff304eb-7c06-4902-b36b-3eeb03a57bb2)

**Comment by Xindage** [comment]
Mostly by Nful2 effort this one is closing, thanks for the support.
