### ISSUE TITLE
Check if all levels can be completed fully FD2.

### ISSUE THREAD

**Issue by Xindage** [freedoom/freedoom#959]
**This list is for freedoom 2**
This list is to keep track of every map in every skills, all map should be completed fully with all secret items and monsters.
provide me the data on Direct messages on discord (i prefer that please) )or here and i'll edit this issue with the data provided.
Note: TBC means "To be Confirmed" this mean that slot is open to test so you can provide me the info if its beatable.
If a map is not beatable fully in any of the skills, please open a issue.

**_Freedoom 2_**
**Cluster 1**
MAP01: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed) - MRS
MAP02: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed) - MRS
MAP03: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed) - MRS
MAP04: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed) - nful2
MAP05: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed) - nful2
MAP06: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed) - nful2
MAP07: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed) - nful2
MAP08: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed) - nful2
MAP09: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed) - Catoptromancy
MAP10: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed) - nful2
MAP11: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed) - nful2
**Cluster 2**
MAP12: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed) - nful2
MAP13: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed) - nful2
MAP14: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed) - nful2
MAP15: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed) - nful2
MAP16: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed) - nful2
MAP17: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed) - nful2
MAP18: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed) - nful2
MAP19: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed) - nful2
MAP20: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed) - nful2
MAP31: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed)  - Catoptromancy
MAP32: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed)  - Catoptromancy
**Cluster 3**
MAP21: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed) - nful2
MAP22: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed) - nful2
MAP23: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed) - nful2
MAP24: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed) - nful2
MAP25: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed) - nful2
MAP26: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed) - nful2
MAP27: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed)  - Catoptromancy
MAP28: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed)  - Catoptromancy
MAP29: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed) - nful2
MAP30: Easy (Confirmed) Medium (Confirmed) Hard (Confirmed)  - Catoptromancy

**Comment by nful2** [comment]
Map04
gzdoom 4.10.0
Didn't face any issues

Hard
![Hard](https://github.com/freedoom/freedoom/assets/100768714/00271dae-b76d-4ce2-81f3-aa2d6dafb9ab)
Medium
![Med](https://github.com/freedoom/freedoom/assets/100768714/1d5fbea3-6b6d-4f39-b9a1-bb7d423bc672)
Easy
![Easy](https://github.com/freedoom/freedoom/assets/100768714/f105e853-96a0-4c44-bc8e-fb230f7c3264)

**Comment by nful2** [comment]
Map04 hard
freedoom-0.12.0-489-ge88e1020, crispy-doom-6.0.0
Didn't face any issue
![map04](https://github.com/freedoom/freedoom/assets/100768714/8bcec20d-5306-4705-b476-80ca9817aa2a)

**Comment by nful2** [comment]
@Xindage Map06,7, freedoom-0.12.0-509-gd71ac12c, gzdoom-4-10-0
Didn't face any issue.
Arranged in easy, medium and hard respectively

![e map06](https://github.com/freedoom/freedoom/assets/100768714/3b40bdfb-df88-4f49-8e1d-89d9062d24d8)
![m map06](https://github.com/freedoom/freedoom/assets/100768714/23e39efe-0765-4342-98cb-32f3c3ecf505)
![h map06](https://github.com/freedoom/freedoom/assets/100768714/1720a9bd-942d-419c-9def-af97c40d702f)
![e map07](https://github.com/freedoom/freedoom/assets/100768714/6070c2ad-776c-4cd4-b6d4-3150e0a50e50)
![m map07](https://github.com/freedoom/freedoom/assets/100768714/d7ec81af-a614-4fe4-9876-f73af5a7a6c6)
![h map07](https://github.com/freedoom/freedoom/assets/100768714/35a12256-48a8-4578-891d-f345695d4cda)

**Comment by nful2** [comment]
@Xindage map08, freedoom-0.12.0-511-g8f8ed90a, gzdoom-4-10-0
Didn't face any issues

![e map08](https://github.com/freedoom/freedoom/assets/100768714/e0e2880b-a861-4c3b-b081-87dc8260d1b7)
![m map08](https://github.com/freedoom/freedoom/assets/100768714/30a703e6-f85e-4f98-98b7-dae8cdd8db91)
![h map08](https://github.com/freedoom/freedoom/assets/100768714/5202a88c-5238-4f1a-952c-2acf4a8df562)

**Comment by nful2** [comment]
@Xindage map10, freedoom-0.12.0-539-g3a74d144, gzdoom-4-10-0
![e 10](https://github.com/freedoom/freedoom/assets/100768714/74037b20-082e-40b1-a769-1dd294e69536)
![m 10](https://github.com/freedoom/freedoom/assets/100768714/f6967370-4793-4431-b7bc-8b0e9379a613)
![h 10](https://github.com/freedoom/freedoom/assets/100768714/7758887a-e37e-4e90-a8c9-3a53653f8a94)

**Comment by nful2** [comment]
@Xindage map12, freedoom-0.12.0-540-g9135b52e, gzdoom-4-10-0
![e 12](https://github.com/freedoom/freedoom/assets/100768714/adc1c8af-a44b-489d-9365-27ed82a8dfca)
![m 12](https://github.com/freedoom/freedoom/assets/100768714/6a9cf2f2-0a12-4f68-9e10-ee6e63b84736)
![h 12](https://github.com/freedoom/freedoom/assets/100768714/0e894eef-c890-4cb8-a792-335d1f8b8342)

**Comment by nful2** [comment]
@Xindage map13, freedoom-0.12.0-540-g9135b52e, gzdoom-4-10-0
![e 13](https://github.com/freedoom/freedoom/assets/100768714/9b63979f-9a46-4fad-ae92-f7e7f028ae74)
![m 13](https://github.com/freedoom/freedoom/assets/100768714/b8894969-2d10-4ae5-92fc-075d32608c8c)
![h 13](https://github.com/freedoom/freedoom/assets/100768714/b3990c3c-dfe7-4171-b70e-6549b7d3340e)

**Comment by Catoptromancy** [comment]
map09 all skills are good 100%

**Comment by nful2** [comment]
@Xindage map15,16, freedoom-0.12.0-540-g9135b52e, gzdoom-4-10-0
![e 15](https://github.com/freedoom/freedoom/assets/100768714/9c6839c0-fa9a-4b26-8fa4-53569fb166c6)
![m 15](https://github.com/freedoom/freedoom/assets/100768714/af860cd2-8f3c-46a7-b525-fb7a45cb804d)
![h 15](https://github.com/freedoom/freedoom/assets/100768714/b53aaaad-d809-4d95-b21e-35b960db9b1c)
![e 16](https://github.com/freedoom/freedoom/assets/100768714/2fe6a242-1f60-4078-85f5-725f0f704cd7)
![m 16](https://github.com/freedoom/freedoom/assets/100768714/9675aad7-cd27-4370-a171-b7415c7ed31d)
![h 16](https://github.com/freedoom/freedoom/assets/100768714/68d608c6-405a-4fba-bb1d-e87164b48ee9)

**Comment by nful2** [comment]
@Xindage map17, freedoom-0.12.0-540-g9135b52e, gzdoom-4-10-0
![e 17](https://github.com/freedoom/freedoom/assets/100768714/a0511402-2d0b-43db-a07e-41aab7306866)
![m 17](https://github.com/freedoom/freedoom/assets/100768714/40073c80-2833-413a-b564-292c061b3570)
![h 17](https://github.com/freedoom/freedoom/assets/100768714/146512c4-d119-4696-9d62-9cc6a9a80e2c)

**Comment by nful2** [comment]
@Xindage map19,20, freedoom-0.12.0-541-ga8a4ae5d, gzdoom-4-10-0 
![e 19](https://github.com/freedoom/freedoom/assets/100768714/d30035dd-bbf2-4a8a-9489-b2426feeb425)
![m 19](https://github.com/freedoom/freedoom/assets/100768714/519aad27-b2e3-4ac0-8840-86bb69b94cd2)
![h 19](https://github.com/freedoom/freedoom/assets/100768714/d41e0c35-fe6a-457d-b5af-e098bb6ea2ca)
![e 20](https://github.com/freedoom/freedoom/assets/100768714/73f59e00-f237-45b8-82f2-b08842043946)
![m 20](https://github.com/freedoom/freedoom/assets/100768714/5cd97781-45b5-41c9-ab31-e5cca077d69e)
![h 20](https://github.com/freedoom/freedoom/assets/100768714/ad1a4f76-ad98-44d3-a372-705306cf8191)

**Comment by Xindage** [comment]
updated, what happened in 11 14 and 18?

**Comment by nful2** [comment]
Either I was unable to find secrets, or the maps are not completable. Will post all issues together, after I finish all levels.

**Comment by Catoptromancy** [comment]
Map11 is/was updated, one secret was too hard to trigger. 

Also MAP27 100% all skills.

**Comment by nful2** [comment]
@Xindage map21,22, freedoom-0.12-0-545-g13f70d1e, gzdoom-4-10-0
![e 21](https://github.com/freedoom/freedoom/assets/100768714/d8a1e557-52fe-4ca2-b9b9-a292103cdb6e)
![m 21](https://github.com/freedoom/freedoom/assets/100768714/ddc78802-efeb-48ff-b8ce-b0290906d2ab)
![h 21](https://github.com/freedoom/freedoom/assets/100768714/15cb293b-bba7-450a-a6ce-e30759bda37d)
![e 22](https://github.com/freedoom/freedoom/assets/100768714/0c62b89f-fd18-48f7-ac29-6e8599109703)
![m 22](https://github.com/freedoom/freedoom/assets/100768714/44835291-45bf-4618-85d2-5c7add2ea7a0)
![h 22](https://github.com/freedoom/freedoom/assets/100768714/b116e6c4-e582-4301-8b5a-feec3cd63d30)

**Comment by nful2** [comment]
@Xindage map23,24, freedoom-0.12-0-545-g13f70d1e, gzdoom-4-10-0
![e 23](https://github.com/freedoom/freedoom/assets/100768714/e9624685-a37f-41be-830f-b777a4aca493)
![m 23](https://github.com/freedoom/freedoom/assets/100768714/99fbe524-9449-40e8-9475-7c86f3ec07fd)
![h 23](https://github.com/freedoom/freedoom/assets/100768714/0fbc7ab7-b658-483d-8f68-9e40ab6f5583)
![e 24](https://github.com/freedoom/freedoom/assets/100768714/51762c44-956c-409b-8835-8bcbe8f25a8d)
![m 24](https://github.com/freedoom/freedoom/assets/100768714/2b62834a-f039-40cb-a2f1-bdf071e635df)
![h 24](https://github.com/freedoom/freedoom/assets/100768714/3869693b-ca76-4f35-bf5e-fc8fdcee5d42)

**Comment by nful2** [comment]
@Xindage map25, freedoom-0.12-0-545-g13f70d1e, gzdoom-4-10-0
![e 25](https://github.com/freedoom/freedoom/assets/100768714/b92d5b42-c0e4-4c44-94bb-2b86b73c74d6)
![m 25](https://github.com/freedoom/freedoom/assets/100768714/f0f94171-32e3-43f4-959e-b14d3afed5b2)
![h 25](https://github.com/freedoom/freedoom/assets/100768714/48c62a88-afa1-42a3-b653-e338a2dc74a4)

**Comment by nful2** [comment]
@Xindage map18,26,29, freedoom-0.12.0-546-g6a544714, gzdoom-4-10-0

**Comment by nful2** [comment]
Will do map14 as soon as #1040 is merged

**Comment by nful2** [comment]
@Xindage map14,  freedoom-0.12.0-550-ga3dbe95f, gzdoom-4-10-0
No issues faced
![e 14](https://github.com/freedoom/freedoom/assets/100768714/1738a5ef-46d0-43f0-89d4-a41d94b57e3a)
![m 14](https://github.com/freedoom/freedoom/assets/100768714/e58de20a-faf1-4fb8-a74e-a65862513634)
![h 14](https://github.com/freedoom/freedoom/assets/100768714/a69e9582-321e-4db2-a1ea-cdea684a7b8f)

**Comment by nful2** [comment]
@Xindage is map11 done or not?

**Comment by nful2** [comment]
@Xindage map11,  freedoom-0.12.0-550-ga3dbe95f, gzdoom-4-10-0
No issues faced
![e 11](https://github.com/freedoom/freedoom/assets/100768714/eb99d1bf-923f-490f-9471-9f85dd671512)
![m 11](https://github.com/freedoom/freedoom/assets/100768714/fd5f6c54-7601-4f9b-8c0f-702878793a57)
![h 11](https://github.com/freedoom/freedoom/assets/100768714/4c5de2ec-a246-4f2c-a17c-e3a843fb1dc0)

**Comment by Xindage** [comment]
Closed ad finished
