### ISSUE TITLE
Check and provide new demos for all iwad.

### ISSUE THREAD

**Issue by Xindage** [freedoom/freedoom#960]
On Hold for milestone 0.13. 
New demos for 0.13  should be necessary but this should be done only when the last steps are ready to be done.

**Comment by nful2** [comment]
@Xindage Should I do this? If yes, then which source port?

**Comment by nful2** [comment]
@mc776 all 3 skills?

**Comment by Xindage** [comment]
That would be better to discuss in the server like we did before. So we can provide multiplayer demos as well.

**Comment by mc776** [comment]
Pretty sure nful2 is not on Discord.

Doesn't each IWAD only have 4 demos?

**Comment by selliott512** [comment]
FD 1 and FD 2 have 4 demos each, and DM has 3 demos having to do with the fact that one of them was broken, and it was hard to create a multiplayer match to fix it.

The current demos are listed in `lumps/README.DEMO`. The relevant part of that file:
```
Phase 1:
DEMO1: E1M4 single-player by Erick - v0.12
DEMO2: E2M3 single-player by Steven Elliott - v0.13.0
DEMO3: E3M3 single-player by Steven Elliott - v0.13.0
DEMO4: E4M6 single-player by Erick - v0.12

Phase 2:
DEMO1: MAP06 single-player by Steven Elliott - v0.13.0
DEMO2: MAP11 single-player by Steven Elliott - v0.13.0
DEMO3: MAP16 single-player by Steven Elliott - v0.13.0
DEMO4: MAP21 single-player by Steven Elliott - v0.13.0

FreeDM:
DEMO1: DM21 by Xindage, Chungy, Erick, and Xer - v0.12
DEMO2: DM06 by Chungy, Xindage, and Erick - v0.12
DEMO3: DM18 by Chungy, Xindage, and Erick - v0.12
```

An example of recording E2M3 as DEMO2:
```
time chocolate-doom -iwad wads/freedoom1.wad -strictdemos -skill 4 -warp 2 3 -record lumps/demo2_p1
```
Replaying the above after everything is rebuilt:
```
time chocolate-doom -iwad wads/freedoom1.wad -playdemo demo2
```
IMHO it's good to keep demos short, like a minute or less. They should probably end with the player dying.

**Comment by nful2** [comment]
Is this good? [e1m1.zip](https://github.com/freedoom/freedoom/files/12447452/e1m1.zip)

**Comment by mc776** [comment]
Personally I'd really rather not have one of the demos be for the very first map of any given IWAD since a naive new player who just mashes Enter to get into the game would end up seeing everything twice.

Any of the other episode start maps seems like a bad idea but not quite as bad.

**Comment by nful2** [comment]
Then which maps should I do and which not to do?

**Comment by mc776** [comment]
It won't start... what did you record this in?

**Comment by EnzoCarozza** [comment]
It started for me.

DSDA-Doom 0.26.2
-complevel 3

**Comment by mc776** [comment]
> Compatibility: Ultimate Doom/Doom95

According to this https://doomwiki.org/wiki/DSDA-Doom it should be complevel 2.

**Comment by EnzoCarozza** [comment]
Please re-read that wiki page.
-complevel 2 = Doom v1.9 (Doom II)
-complevel 3 = The Ultimate Doom

**Comment by mc776** [comment]
okay for some reason I just can't play demos and I have no idea why

**Comment by mc776** [comment]
Anyway while trying to figure that out I've done a demo for Map20 and E3M6 that might be usable (and in the case of the former has a bit of decent comedic timing if I dare say) [Uploading señordedolor.zip…]()

**Comment by nful2** [comment]
@mc776 I too got that error, just rename it shorter and play it again. That is why i have named the lmp files as 1.lmp

**Comment by mc776** [comment]
Sweet, thanks!

I'm a little concerned about your demo being a bit too short - it's just under 20 seconds and barely 2 rooms into the map. (Meanwhile mine are relatively long, about 2 minutes each)

All 3 demos currently in Phase 1 are about 40 seconds. Are we supposed to be aiming for that, or are we free to do whatever?

**Comment by mc776** [comment]
Why is this labeled "enhancement" anyway? Getting this done seems like a precondition for release, rather than the sort of optional additional bonus that "enhancement" tends to imply...

**Comment by nful2** [comment]
@mc776 did you confirm the time limit of a demo?

**Comment by mc776** [comment]
I have not found anything so I think anything under 5 minutes should be fine.

**Comment by fawtytoo** [comment]
Should these demos be recorded with the LOS (line of light) bug corrected?

**Comment by mc776** [comment]
Is there any version of vanilla Doom that has that correction?

**Comment by Xindage** [comment]
All demos required was provided as multiplayer demos recorded on chocolate doom.
