### ISSUE TITLE
Custon TNT doors are bugged

### ISSUE THREAD

**Issue by Xindage** [freedoom/freedoom#961]
I noticed on slade that the locked key droos for TNT has bugged offsets in the patch tables, someone wanna fix it?

**Comment by mc776** [comment]
screenshots? might have been intentional...

**Comment by Xindage** [comment]
it was not intentional, i did them and i messed up two out of three keyed marked doors

**Comment by Xindage** [comment]
names are M_RDOOR - M_YDOOR - M_BDOOR

**Comment by mc776** [comment]
So that's what these weird transparent door texture are about!
![image](https://user-images.githubusercontent.com/24984517/236066290-4146b145-9bab-4261-9126-ae5d35bd25fd.png)

(seems like blue is okay though?)

**Comment by Xindage** [comment]
ye the blue is not bugged indeed :)
