### ISSUE TITLE
Player view stuck to a designated area

### ISSUE THREAD

**Issue by WriterShoe** [freedoom/freedoom#968]
For some reason, how much I can turn is limited. It's almost as if the amount I can turn was automatically determined as I spawned. I can still go past this "designated" area with the arrow keys-if I set it to. But once I use my mouse it just doesn't work; of course, I can still use my mouse to turn but I can never do a full turn with it. I'm currently using the default keybindings that came with it. I'm not sure if I'm suppose to change a keybinding or if there's a bug with the current version of freedoom I'm using, which is the one that comes with the fedora repositories. Would appreciate some insight into this, thanks.

**Comment by mc776** [comment]
This is a technical issue with your sourceport and not Freedoom.

**Comment by Calinou** [comment]
It sounds like the source port you're using isn't capturing the mouse correctly, so the mouse cursor is still moving on top of the window but is clamped by the screen's coordinates.

**Comment by WriterShoe** [comment]
Alright, so I've switched out the precompiled GZDoom from Fedora for the Flatpak version of it but it still doesn't work. And the entire time, by default, the game had been set to full-screen.

**Comment by Calinou** [comment]
Are you using Wayland? Pointer lock may not be working there.

**Comment by WriterShoe** [comment]
Yup, it's just an issue with Wayland. I guess I'll just have to switch to dwm everytime I decide to use GZDoom. Thanks for the help!
