### ISSUE TITLE
Freedoom2.wad map 13 is impossible to max on vanilla-compatible ports.

### ISSUE THREAD

**Issue by JamesC0222** [freedoom/freedoom#975]
After crossing the linedef near the yellow key to trigger the ambush, the sector containing the arch-vile and two revenants (or freedoom equivalents thereof) fails to lower when playing in DSDA-Doom or Crispy Doom.  This is easily fixed by moving the arch-vile a few map units east so that its hitbox is no longer partially inside the wall. This bug does not occur in the latest GZDoom.

**Comment by mc776** [comment]
I recall this had been fixed a while ago. Are you running the latest commit? http://freedoom.soulsphere.org/

**Comment by JamesC0222** [comment]
Just tried both this and the version listed as the most recent release on Github. Those both work fine, I must be using a weird 12.1 IWAD. Sorry for the false alarm.

**Comment by JamesC0222** [comment]
EDIT: This problem still exists in the 12.1 IWAD, I used the wrong complevel the first time I tried it. The latest commit works perfectly, though.

**Comment by JamesC0222** [comment]
Thanks
