### ISSUE TITLE
Some issues in episode 1

### ISSUE THREAD

**Issue by nful2** [freedoom/freedoom#976]
Version used: freedoom-0.12.0-486-g4b002550
Source port used: gzdoom v4.10.0

1. e1m9 - In megarmor area, if you leave some enemies above the lift, you are unable to go up the lift due to the enemies blocking it. You are able to go up when enemies move away a bit. I think the enemies are able to control the lift.
2. e1m6 - Zombieman is stuck near red key
![e1m6](https://github.com/freedoom/freedoom/assets/100768714/0825b98e-9d62-4bc7-a7a0-1cb87aa9051f)
3. e1m7 - Map only shows 8 secrets, but tally shows 9 secrets. On my first attempt on easy, i was not able to tag one secret (e1m7). Though i was able to do it in second run. BUT in the main release (v0.12.1), the tally shows 8 secrets.
![e1m7](https://github.com/freedoom/freedoom/assets/100768714/47e6a699-02e9-4c99-8f0f-59ea8e110992)

**Comment by mc776** [comment]
1. Do you mean here?
![_](https://github.com/freedoom/freedoom/assets/24984517/479414cd-4bef-4ff4-b3ca-6859a8f1d267)

**Comment by nful2** [comment]
@mc776 yeah, in here. You can get stuck here if enemies are above the lift.

**Comment by nful2** [comment]
Would recommend to add this in to primary objectives for 0.13 release

**Comment by Xindage** [comment]
fixed by #978
