### ISSUE TITLE
Issues/Suggestions for e2m6

### ISSUE THREAD

**Issue by nful2** [freedoom/freedoom#982]
1. Jump seems a bit difficult to make
![Screenshot (2)](https://github.com/freedoom/freedoom/assets/100768714/099adad0-b3ec-4e65-9492-cadbe4cc72d3)
2. Superchrge secret shows in the map in skill 1 but doesn't in skill 2 & 3. Played it again in skill 1 and it doesn't show up.
3. Two worms behind the wall near baron (after chainsaw) open up too late in skill 3

**Comment by mc776** [comment]
1. Seems OK to me - pretty sure someone will have figured out straferunning after playing at least 15 levels.

2. If you're playing GZDoom, does it sometimes not give you the "A secret is revealed!" alert? Just looking at the map you posted on #958 it looks like the sector is so thin you could have grabbed the soulsphere without actually triggering the secret.

3. Define "too late" - what is expected and what is actual?

**Comment by nful2** [comment]
2. Yeah I think that is what happened. No, I am using crispy doom now. It showed the secret revealed message but doesn't mark it on the map
3. Tested it again on all 3 skills and it works as expected now

**Comment by nful2** [comment]
Btw can you please tell @Xindage to check and verify my screenshots?

**Comment by Xindage** [comment]
i cant do anything on weekends on github, so that's why i havent reviewned anything yet

**Comment by Xindage** [comment]
can i close this?

**Comment by mc776** [comment]
Turns out you can jump across that gap without straferunning.

Which leaves us with issue 2 which I can totally see being a legit problem...

**Comment by Xindage** [comment]
adressed in https://github.com/freedoom/freedoom/commit/99149fba2d2dd99ff83cf304e80e1f49ae0affc3
