### ISSUE TITLE
COMPUTE4 and SKSPINE2 look different in chocolate

### ISSUE THREAD

**Issue by mc776** [freedoom/freedoom#995]
Chocolate:
![choco](https://github.com/freedoom/freedoom/assets/24984517/e513be4f-81ad-4cf9-8dfb-030bdbdbc9a8)

DSDA:
![dsda](https://github.com/freedoom/freedoom/assets/24984517/2447e8a2-c09c-40a7-9a3f-3555214681c4)

SLADE:
![slade](https://github.com/freedoom/freedoom/assets/24984517/e5f9684c-83ad-42e2-975a-91187c0e2b9c)

(GZDoom has the same output as DSDA and SLADE but i'm too lazy to navigate to its screenshots folder and crop/optimize that)

I don't see anything unusual in textures.cfg and it does appear to be loading the correct IWAD (and not the release version that comes with choco in the repository) so I really can't figure out what's going on - or if it's just some weird thing with my own setup.

**Comment by mc776** [comment]
E1M1 is a good demonstration since it has a single straight line with nothing but this texture with no offset:

![_](https://github.com/freedoom/freedoom/assets/24984517/95409ed2-819a-49ac-8ade-5e8c9ca0b21f)

![_](https://github.com/freedoom/freedoom/assets/24984517/c0b0352b-9ff3-4a43-8ad8-edb24fd11d2d)

I have no idea what is being misparsed in the textures lump.

**Comment by mc776** [comment]
I have no idea if this could be related or not: this rib texture seems to be cut off at the top in chocolate.
![DOOM03](https://github.com/freedoom/freedoom/assets/24984517/e13f43ac-a74b-4900-8e8c-f7a358ed7797)

![DOOM00](https://github.com/freedoom/freedoom/assets/24984517/53ccd2f5-12c4-4ecf-b88a-758c309d1445)
![_](https://github.com/freedoom/freedoom/assets/24984517/5b90065b-1bc3-42b2-b094-c2f327c81351)

**Comment by mc776** [comment]
COMPUTE4: 196 wide

SKSPINE2: 96 tall

...is this tutti-frutti!?

**Comment by Talon1024** [comment]
> COMPUTE4: 196 wide

I think it's worth noting that 196 is not a multiple of 64. 192 is.

**Comment by mc776** [comment]
yeah, misremembered the final digit when I posted, the actual texture is a correct multiple of 64.

The actual problem though is that it's not a power of 2.
