### ISSUE TITLE
E3m6 issues/suggestions

### ISSUE THREAD

**Issue by nful2** [freedoom/freedoom#998]
1. No way to escape if you fall in this pit (located opposite to the other pit with secret)
![Screenshot (47)](https://github.com/freedoom/freedoom/assets/100768714/ba36dc99-546f-4c64-92c6-847d08a637a8)
2. Pain lord can go into the red teleporter can pose a problem.

**Comment by mc776** [comment]
lol didn't even see point 2 until now

Honestly doesn't seem that bad  to me - I remember seeing that a few times while dealing with other stuff on this map, but it would just disappear and reappear without getting stuck. It made for a more interesting and dynamic fight than just another bullet-sponge turret on a platform.
