### ISSUE TITLE
e3m7 & e3m8 & e3m9 issues/suggestions

### ISSUE THREAD

**Issue by nful2** [freedoom/freedoom#999]
E3m7 - how to get supercharge inside blood waterfall?
![Screenshot (56)](https://github.com/freedoom/freedoom/assets/100768714/b1ff2e4e-3892-4105-bc50-c96f0d9a2ac4)
Couldn't find any switch. This is present in both gzdoom and crispy.

E3m8 - enemy didn't teleport https://github.com/freedoom/freedoom/assets/100768714/3e89faba-7b0c-4650-aed9-e9ab6e71fb2c

E3m9 - Bonus placed too close to wall
![Screenshot (59)](https://github.com/freedoom/freedoom/assets/100768714/b8b19fe4-f689-4ac9-96ca-60ac687515b6)
![Screenshot (60)](https://github.com/freedoom/freedoom/assets/100768714/5d40dd88-dece-4ce0-9a24-8ff873822330)

**Comment by andOlga** [comment]
To grab the soulsphere, jump into this passage here...

![image](https://github.com/freedoom/freedoom/assets/462484/9421e172-3760-446f-be0f-9e3ab8458e9f)

...and then run towards it as fast as you can.

![image](https://github.com/freedoom/freedoom/assets/462484/c997603e-9f77-46e4-b819-b734ae7c5ab7)

Now how the heck you're supposed to figure this out, your guess is as good as mine 😅

**Comment by mc776** [comment]
E3M8 and E3M9 can be fixed easily https://github.com/freedoom/freedoom/compare/master...e3m8-9fix

The soul sphere secret is pretty damn obscure, but it's not impossible to chance upon the solution by accident - if anyone's got ideas to make it more deducible without making it insultingly obvious please feel free to share, though personally this doesn't pass my "this is impossible without checking the map editor or having someone tell you" threshold just yet.
